= Article 6

Assistance

1.   La présente directive ne s'applique pas à l'activité d'assistance pour autant qu'elle remplisse toutes les conditions suivantes:

. a) l'assistance est fournie à l'occasion d'un accident ou d'une panne affectant un véhicule routier, lorsque l'accident ou la panne survient sur le territoire de l'État membre du fournisseur de la garantie;

. b) l'engagement au titre de l'assistance est limité aux opérations suivantes:i)le dépannage sur place, pour lequel le fournisseur de la garantie utilise, dans la plupart des circonstances, son personnel et son matériel propres;ii)l'acheminement du véhicule jusqu'au lieu de réparation le plus proche ou le plus approprié où la réparation pourra être effectuée, ainsi que l'éventuel accompagnement, normalement par le même moyen de secours, du conducteur et des passagers, jusqu'au lieu le plus proche d'où ils pourront poursuivre leur voyage par d'autres moyens; etiii)lorsque l'État membre d'origine du fournisseur de la garantie le prévoit, l'acheminement du véhicule, éventuellement accompagné par le conducteur et les passagers, jusqu'à leur domicile, leur point de départ ou leur destination originelle à l'intérieur du même État membre; et

. i) le dépannage sur place, pour lequel le fournisseur de la garantie utilise, dans la plupart des circonstances, son personnel et son matériel propres;

. ii) l'acheminement du véhicule jusqu'au lieu de réparation le plus proche ou le plus approprié où la réparation pourra être effectuée, ainsi que l'éventuel accompagnement, normalement par le même moyen de secours, du conducteur et des passagers, jusqu'au lieu le plus proche d'où ils pourront poursuivre leur voyage par d'autres moyens; et

. iii) lorsque l'État membre d'origine du fournisseur de la garantie le prévoit, l'acheminement du véhicule, éventuellement accompagné par le conducteur et les passagers, jusqu'à leur domicile, leur point de départ ou leur destination originelle à l'intérieur du même État membre; et

. c) l'assistance n'est pas fournie par une entreprise soumise à la présente directive.

2.   Dans les cas visés au paragraphe 1, point b) i) et ii), la condition que l'accident ou la panne soit survenu sur le territoire de l'État membre du fournisseur de la garantie ne s'applique pas lorsque le bénéficiaire est membre de l'organisme fournissant la garantie et que le dépannage ou l'acheminement du véhicule est effectué sur simple présentation de la carte de membre, sans paiement de surprime, par un organisme similaire du pays concerné sur la base d'un accord de réciprocité ou, dans le cas de l'Irlande et du Royaume-Uni, lorsque l'assistance est fournie par un même organisme opérant dans ces deux États.

3.   La présente directive ne s'applique pas dans le cas des opérations visées au paragraphe 1, point b) iii), si l'accident ou la panne est survenu sur le territoire de l'Irlande ou, en ce qui concerne le Royaume-Uni, sur le territoire de l'Irlande du Nord et que le véhicule, éventuellement accompagné par le conducteur et les passagers, est acheminé jusqu'à leur domicile, à leur point de départ ou à leur destination originelle à l'intérieur de l'un ou de l'autre de ces territoires.

4.   La présente directive ne s'applique pas aux opérations d'assistance effectuées par l'Automobile Club du Grand-Duché de Luxembourg lorsque l'accident ou la panne affectant un véhicule routier est survenu à l'extérieur du territoire du Grand-Duché de Luxembourg et que l'assistance consiste en l'acheminement du véhicule accidenté ou en panne, éventuellement accompagné par le conducteur et les passagers, jusqu'à leur domicile.