= Article 245

Contrôle des transactions intragroupe

1.   Le contrôle des transactions intragroupe est exercé conformément aux paragraphes 2 et 3 du présent article, à l'article 246 et au chapitre III.

2.   Les États membres imposent aux entreprises d'assurance et de réassurance ou aux sociétés holding d'assurance de déclarer régulièrement et au moins annuellement au contrôleur du groupe toutes les transactions intragroupe significatives effectuées par les entreprises d'assurance et de réassurance appartenant à un groupe, y compris celles effectuées avec une personne physique ayant des liens étroits avec une entreprise du groupe.

En outre, les États membres exigent que les transactions intragroupe très significatives soient déclarées aussi rapidement que possible.

Les informations nécessaires sont soumises au contrôleur du groupe par l'entreprise d'assurance ou de réassurance qui est à la tête du groupe ou, lorsque le groupe n'est pas dirigé par une entreprise d'assurance ou de réassurance, par la société holding d'assurance ou par l'entreprise d'assurance ou de réassurance du groupe désignée par ledit contrôleur après consultation des autres autorités de contrôle concernées et du groupe.

Les transactions intragroupe font l'objet d'un contrôle prudentiel exercé par le contrôleur du groupe.

3.   Le contrôleur du groupe identifie, après avoir consulté les autres autorités de contrôle concernées ainsi que le groupe, le type de transactions intragroupe que les entreprises d'assurance et de réassurance d'un groupe donné déclarent en toutes circonstances. L'article 244, paragraphe 3, est applicablemutatis mutandis.

4.   La Commission peut arrêter des mesures d'exécution concernant la définition et l'identification d'une transaction intragroupe importante ainsi que sa déclaration, aux fins des paragraphes 2 et 3.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

Section 3

Gestion des risques et contrôle interne