= Article 244

Contrôle de la concentration de risques

1.   Le contrôle de la concentration de risques au niveau des groupes est exercé conformément aux paragraphes 2 et 3 du présent article, à l'article 246 et au chapitre III.

2.   Les États membres imposent aux entreprises d'assurance et de réassurance ou aux sociétés holding d'assurance de déclarer régulièrement et au moins annuellement au contrôleur du groupe toute concentration de risques importante au niveau du groupe.

Les informations nécessaires sont soumises au contrôleur du groupe par l'entreprise d'assurance ou de réassurance qui est à la tête du groupe ou, lorsque le groupe n'est pas dirigé par une entreprise d'assurance ou de réassurance, par la société holding d'assurance ou par l'entreprise d'assurance ou de réassurance du groupe désignée par ledit contrôleur après consultation des autres autorités de contrôle concernées et du groupe.

Les concentrations de risques font l'objet d'un contrôle prudentiel exercé par le contrôleur du groupe.

3.   Le contrôleur du groupe identifie, après avoir consulté les autres autorités de contrôle concernées ainsi que le groupe, le type de risque que les entreprises d'assurance et de réassurance d'un groupe donné déclarent en toutes circonstances.

Pour définir le type de risque ou donner leur avis sur celui-ci, le contrôleur du groupe et les autres autorités de contrôle concernées tiennent compte du groupe concerné et de sa structure de gestion des risques.

Pour identifier les concentrations de risques significatives à déclarer, le contrôleur du groupe, après avoir consulté les autres autorités de contrôle concernées et le groupe, impose des seuils appropriés basés sur le capital de solvabilité requis, sur les provisions techniques ou sur les deux.

Lors du contrôle des concentrations de risques, le contrôleur du groupe est particulièrement attentif au risque possible de contagion dans le groupe, au risque de conflit d'intérêts et au niveau ou au volume des risques.

4.   La Commission peut arrêter des mesures d'exécution concernant la définition et l'identification d'une concentration de risques importante ainsi que sa déclaration, aux fins des paragraphes 2 et 3.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.