= Article 227

Entreprises d'assurance et de réassurance liées d'un pays tiers

1.   Pour le calcul, conformément à l'article 233, de la solvabilité du groupe d'une entreprise d'assurance ou de réassurance qui est une entreprise participante d'une entreprise d'assurance ou de réassurance d'un pays tiers, cette dernière est traitée, aux seules fins de ce calcul, comme une entreprise d'assurance ou de réassurance liée.

Toutefois, lorsque le pays tiers dans lequel cette entreprise a son siège social la soumet à un régime d'agrément et lui impose un régime de solvabilité au moins équivalent à celui établi par le titre I, chapitre VI, les États membres peuvent prévoir que le calcul tient compte, en ce qui concerne cette entreprise, du capital de solvabilité requis et des fonds propres éligibles pour le couvrir, tels que définis par le pays tiers concerné.

2.   Il appartient au contrôleur du groupe de vérifier, à la demande de l'entreprise participante ou de sa propre initiative, si le régime du pays tiers est au moins équivalent.

Pour ce faire, le contrôleur du groupe consulte les autres autorités de contrôle concernées, ainsi que le CECAPP, avant de se prononcer sur l'équivalence.

3.   La Commission peut arrêter des mesures d'exécution précisant les critères qui permettent d'évaluer si le régime de solvabilité d'un pays tiers équivaut ou non à celui établi par le titre I, chapitre VI.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

4.   La Commission peut décider, après consultation du comité européen des assurances et des pensions professionnelles et en conformité avec la procédure de réglementation visée à l'article 301, paragraphe 2, en prenant en compte les critères arrêtés en vertu du paragraphe 3 du présent article, si le régime de solvabilité du pays tiers équivaut ou non à celui établi par le titre I, chapitre VI.

Ces décisions sont régulièrement réexaminées pour tenir compte de toute modification éventuellement apportée au régime de solvabilité établi par le titre I, chapitre VI, et au régime de solvabilité du pays tiers.

5.   Lorsque la Commission arrête une décision sur l'équivalence du régime de solvabilité d'un pays tiers conformément au paragraphe 4, le paragraphe 2 ne s'applique pas.

Lorsque la Commission a constaté par une décision, conformément au paragraphe 4, que le régime de solvabilité d'un pays tiers n'est pas équivalent, l'option visée au paragraphe 1, second alinéa, qui permet de tenir compte du capital de solvabilité requis et des fonds propres éligibles, tels que définis par le pays tiers concerné, n'est pas applicable et l'entreprise d'assurance ou de réassurance d'un pays tiers est soumise exclusivement au paragraphe 1, premier alinéa.