= Article 181

Assurance non-vie

1.   Les États membres ne peuvent pas exiger l'approbation préalable ou la notification systématique des conditions générales et particulières des polices d'assurance, des tarifs et des formulaires et autres imprimés qu'une entreprise d'assurance se propose d'utiliser dans ses relations avec les preneurs d'assurance.

Les États membres ne peuvent exiger la communication non systématique de ces conditions de polices d'assurance et de ces autres documents que dans le but de contrôler le respect des dispositions nationales relatives aux contrats d'assurance. Ces exigences ne peuvent constituer, pour l'entreprise d'assurance, une condition préalable de l'exercice de son activité.

2.   Un État membre qui impose l'obligation de souscrire une assurance peut exiger des entreprises d'assurance qu'elles communiquent à son autorité de contrôle, préalablement à leur diffusion, les conditions générales et particulières de cette assurance.

3.   Les États membres ne peuvent maintenir ni introduire des obligations de notification ou d'approbation préalables des majorations de tarifs proposées qu'en tant qu'élément d'un système général de contrôle des prix.