= Article 48

Fonction actuarielle

1.   Les entreprises d'assurance et de réassurance mettent en place une fonction actuarielle efficace afin de:

. a) coordonner le calcul des provisions techniques;

. b) garantir le caractère approprié des méthodologies, des modèles sous-jacents et des hypothèses utilisés pour le calcul des provisions techniques;

. c) apprécier la suffisance et la qualité des données utilisées dans le calcul des provisions techniques;

. d) comparer les meilleures estimations aux observations empiriques;

. e) informer l'organe d'administration, de gestion ou de contrôle de la fiabilité et du caractère adéquat du calcul des provisions techniques;

. f) superviser le calcul des provisions techniques dans les cas visés à l'article 82;

. g) émettre un avis sur la politique globale de souscription;

. h) émettre un avis sur l'adéquation des dispositions prises en matière de réassurance; et

. i) contribuer à la mise en œuvre effective du système de gestion des risques visé à l'article 44, en particulier pour ce qui concerne la modélisation des risques sous-tendant le calcul des exigences de capital prévu au chapitre VI, sections 4 et 5, et pour ce qui concerne l'évaluation visée à l'article 45.

2.   La fonction actuarielle est exercée par des personnes qui ont une connaissance des mathématiques actuarielles et financières à la mesure de la nature, de l'ampleur et de la complexité des risques inhérents à l'activité de l'entreprise d'assurance ou de réassurance et qui peuvent démontrer une expérience pertinente à la lumière des normes professionnelles et autres normes applicables.