= Article 50

Mesures d'exécution

1.   La Commission arrête des mesures d'exécution visant à préciser:

. a) les éléments des systèmes visés aux articles 41, 44, 46 et 47 et, en particulier, les domaines que doivent couvrir la gestion actif-passif et la politique d'investissement, visées à l'article 44, paragraphe 2, des entreprises d'assurance et de réassurance;

. b) les fonctions visées aux articles 44 et 46 à 48;

. c) les exigences énoncées à l'article 42 et les fonctions qui y sont soumises;

. d) les conditions dans lesquelles la sous-traitance peut être pratiquée, en particulier la sous-traitance à des prestataires de services situés dans des pays tiers.

2.   S'il est nécessaire d'assurer la convergence appropriée de l'évaluation visée à l'article 45, paragraphe 1, point a), la Commission peut arrêter des mesures d'exécution visant à préciser les éléments d'une telle évaluation.

3.   Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

Section 3

Informations à destination du public