== Article 43

=== Preuve d'honorabilité

1.   Lorsqu'un État membre exige de ses ressortissants une preuve d'honorabilité, la preuve qu'ils n'ont pas été déclarés antérieurement en faillite ou les deux, il accepte comme preuve suffisante, pour les ressortissants des autres États membres, la production d'un extrait du casier judiciaire ou, à défaut, d'un document équivalent délivré par une autorité judiciaire ou administrative compétente de l'État membre d'origine ou de provenance de ces ressortissants étrangers, dont il résulte que ces exigences sont satisfaites.

2.   Lorsque le document visé au paragraphe 1 n'est pas délivré par l'État membre d'origine ou de provenance du ressortissant étranger concerné, il peut être remplacé par une déclaration sous serment – ou, dans les États membres où un tel serment n'est pas prévu, par une déclaration solennelle – faite par le ressortissant étranger concerné devant une autorité judiciaire ou administrative compétente ou, le cas échéant, un notaire de l'État membre d'origine ou de provenance dudit ressortissant étranger.

Cette autorité ou ce notaire délivre une attestation faisant foi de cette déclaration sous serment ou de cette déclaration solennelle.

La déclaration d'absence de faillite visée au premier alinéa peut être faite également devant un organisme professionnel qualifié de l'État membre concerné.

3.   Les documents et certificats visés aux paragraphes 1 et 2 ne peuvent pas être produits plus de trois mois après leur délivrance.

4.   Les États membres désignent les autorités et organismes compétents pour la délivrance des documents visés aux paragraphes 1 et 2 et en informent immédiatement les autres États membres et la Commission.

Chaque État membre indique également aux autres États membres et à la Commission les autorités ou organismes auxquels doivent être présentés les documents visés aux paragraphes 1 et 2, à l'appui de la demande d'exercer, sur le territoire de cet État membre, les activités visées à l'article 2.