= Article 42

Exigences de compétence et d'honorabilité applicables aux personnes qui dirigent effectivement l'entreprise ou qui occupent d'autres fonctions clés

1.   Les entreprises d'assurance et de réassurance veillent à ce que toutes les personnes qui dirigent effectivement l'entreprise ou qui occupent d'autres fonctions clés satisfassent en permanence aux exigences suivantes:

. a) leurs qualifications, connaissances et expérience professionnelles sont propres à permettre une gestion saine et prudente (compétence); et

. b) leur réputation et leur intégrité sont de bon niveau (honorabilité).

2.   Les entreprises d'assurance et de réassurance communiquent aux autorités de contrôle tout changement survenu dans l'identité des personnes qui dirigent effectivement l'entreprise ou qui assument d'autres fonctions-clés, ainsi que toute information nécessaire pour apprécier si toute personne nouvellement nommée pour la gestion de l'entreprise satisfait aux exigences de compétence et d'honorabilité.

3.   Les entreprises d'assurance et de réassurance informent leurs autorités de contrôle du remplacement de toute personne visée aux paragraphes 1 et 2, parce qu'elle ne remplissait plus les exigences énoncées au paragraphe 1.