== Article 45

=== Évaluation interne des risques et de la solvabilité

1.   Dans le cadre de son système de gestion des risques, chaque entreprise d'assurance et de réassurance procède à une évaluation interne des risques et de la solvabilité.

Cette évaluation porte au moins sur les éléments suivants:

. a) le besoin global de solvabilité, compte tenu du profil de risque spécifique, des limites approuvées de tolérance au risque et de la stratégie commerciale de l'entreprise;

. b) le respect permanent des exigences de capital prévues au chapitre VI, sections 4 et 5, et des exigences concernant les provisions techniques prévues au chapitre VI, section 2;

. c) la mesure dans laquelle le profil de risque de l'entreprise s'écarte des hypothèses qui sous-tendent le capital de solvabilité requis prévu à l'article 101, paragraphe 3, calculé à l'aide de la formule standard conformément au chapitre VI, section 4, sous-section 2, ou avec un modèle interne partiel ou intégral conformément au chapitre VI, section 4, sous-section 3.

2.   Aux fins du paragraphe 1, point a), l'entreprise concernée met en place des procédures qui sont proportionnées à la nature, à l'ampleur et à la complexité des risques inhérents à son activité et qui lui permettent d'identifier et d'évaluer de manière adéquate les risques auxquels elle est exposée à court et long terme, ainsi que ceux auxquels elle est exposée, ou pourrait être exposée. L'entreprise démontre la pertinence des méthodes qu'elle utilise pour cette évaluation.

3.   Dans le cas visé au paragraphe 1, point c), lorsqu'un modèle interne est utilisé, l'évaluation est effectuée parallèlement au recalibrage qui aligne les résultats du modèle interne sur la mesure de risque et le calibrage qui sous-tendent le capital de solvabilité requis.

4.   L'évaluation interne des risques et de la solvabilité fait partie intégrante de la stratégie commerciale et il en est tenu systématiquement compte dans les décisions stratégiques de l'entreprise.

5.   Les entreprises d'assurance et de réassurance procèdent à l'évaluation visée au paragraphe 1 sur une base régulière et immédiatement à la suite de toute évolution notable de leur profil de risque.

6.   Les entreprises d'assurance et de réassurance informent les autorités de contrôle des conclusions de chaque évaluation interne des risques et de la solvabilité, dans le cadre des informations à fournir en vertu de l'article 35.

7.   L'évaluation interne des risques et de la solvabilité ne sert pas à calculer un montant de capital requis. Le capital de solvabilité requis n'est ajusté que conformément aux articles 37, 231 à 233 et 238.