= Article 44

Gestion des risques

1.   Les entreprises d'assurance et de réassurance mettent en place un système de gestion des risques efficace, qui comprenne les stratégies, processus et procédures d'information nécessaires pour déceler, mesurer, contrôler, gérer et déclarer, en permanence, les risques, aux niveaux individuel et agrégé, auxquels elles sont ou pourraient être exposées ainsi que les interdépendances entre ces risques.

Ce système de gestion des risques est efficace, parfaitement intégré à la structure organisationnelle et aux procédures de prise de décision de l'entreprise d'assurance ou de réassurance et dûment pris en compte par les personnes qui dirigent effectivement l'entreprise ou qui occupent d'autres fonctions clés.

2.   Le système de gestion des risques couvre les risques à prendre en considération dans le calcul du capital de solvabilité requis conformément à l'article 101, paragraphe 4, ainsi que les risques n'entrant pas ou n'entrant pas pleinement dans ce calcul.

Le système de gestion des risques couvre au moins les domaines suivants:

. a) la souscription et le provisionnement;

. b) la gestion actif-passif;

. c) les investissements, en particulier dans les instruments dérivés et engagements similaires;

. d) la gestion du risque de liquidité et de concentration;

. e) la gestion du risque opérationnel;

. f) la réassurance et les autres techniques d'atténuation du risque.

Les politiques écrites concernant la gestion des risques visées à l'article 41, paragraphe 3, comprennent des politiques concernant le deuxième alinéa, points a) à f), du présent paragraphe.

3.   En ce qui concerne le risque d'investissement, les entreprises d'assurance et de réassurance démontrent qu'elles satisfont aux dispositions du chapitre VI, section 6.

4.   Les entreprises d'assurance et de réassurance prévoient une fonction de gestion des risques, qui est structurée de façon à faciliter la mise en œuvre du système de gestion des risques.

5.   Pour les entreprises d'assurance et de réassurance utilisant un modèle interne partiel ou intégral qui a été approuvé conformément aux articles 112 et 113, la fonction de gestion des risques recouvre les tâches supplémentaires suivantes:

. a) conception et mise en œuvre du modèle interne;

. b) test et validation du modèle interne;

. c) suivi documentaire du modèle interne et de toute modification qui lui est apportée;

. d) analyse de la performance du modèle interne et production de rapports de synthèse concernant cette analyse;

. e) information de l'organe d'administration, de gestion ou de contrôle concernant la performance du modèle interne en suggérant des éléments à améliorer, et communication à cet organe de l'état d'avancement des efforts déployés pour remédier aux faiblesses précédemment détectées.