= Article 41

Exigences générales en matière de gouvernance

1.   Les États membres exigent de toutes les entreprises d'assurance et de réassurance qu'elles mettent en place un système de gouvernance efficace, qui garantisse une gestion saine et prudente de l'activité.

Ce système comprend au moins une structure organisationnelle transparente adéquate, avec une répartition claire et une séparation appropriée des responsabilités, ainsi qu'un dispositif efficace de transmission des informations. Il satisfait aux exigences énoncées aux articles 42 à 49.

Le système de gouvernance fait l'objet d'un réexamen interne régulier.

2.   Le système de gouvernance est proportionné à la nature, à l'ampleur et à la complexité des opérations de l'entreprise d'assurance ou de réassurance.

3.   Les entreprises d'assurance et de réassurance disposent de politiques écrites concernant au moins leur gestion des risques, leur contrôle interne, leur audit interne et, le cas échéant, la sous-traitance. Elles veillent à ce que ces politiques soient mises en œuvre.

Ces politiques écrites sont réexaminées au mois une fois par an. Elles sont soumises à l'approbation préalable de l'organe d'administration, de gestion ou de contrôle et elles sont adaptées compte tenu de tout changement important affectant le système ou le domaine concerné.

4.   Les entreprises d'assurance et de réassurance prennent des mesures raisonnables afin de veiller à la continuité et à la régularité dans l'accomplissement de leurs activités, y compris par l'élaboration de plans d'urgence. À cette fin, elles utilisent des systèmes, des ressources et des procédures appropriés et proportionnés.

5.   Les autorités de contrôle disposent des moyens, méthodes et pouvoirs appropriés pour vérifier le système de gouvernance des entreprises d'assurance et de réassurance et pour évaluer les risques émergents détectés par ces entreprises et susceptibles d'affecter leur solidité financière.

Les États membres veillent à ce que les autorités de contrôle disposent des pouvoirs nécessaires pour exiger que le système de gouvernance soit amélioré et renforcé de façon à satisfaire aux exigences énoncées aux articles 42 à 49.