== Article 158

=== Entreprises de réassurance ne se conformant pas aux dispositions légales

1.   Lorsque les autorités de contrôle d'un État membre constatent qu'une entreprise de réassurance ayant une succursale ou opérant en libre prestation de services sur le territoire de cet État membre ne respecte pas les dispositions légales qui lui sont applicables dans cet État membre, elles demandent à l'entreprise en question de mettre fin à cette situation irrégulière. Parallèlement, elles en informent l'autorité de contrôle de l'État membre d'origine.

2.   Lorsque, en dépit des mesures prises par l'État membre d'origine ou parce que ces mesures apparaissent inadéquates, l'entreprise de réassurance persiste à enfreindre les dispositions légales qui lui sont applicables dans l'État membre d'accueil, les autorités de contrôle de l'État membre d'accueil peuvent, après en avoir informé les autorités de contrôle de l'État membre d'origine, prendre les mesures appropriées pour prévenir ou réprimer de nouvelles irrégularités y compris, pour autant que cela soit absolument nécessaire, en empêchant l'entreprise de réassurance de continuer à conclure de nouveaux contrats de réassurance sur le territoire de l'État membre d'accueil.

Les États membres veillent à ce que les documents juridiques nécessaires à de telles mesures puissent être signifiés sur leur territoire aux entreprises de réassurance.

3.   Toute mesure qui est prise en application des paragraphes 1 et 2 et qui comporte des sanctions ou des restrictions à l'exercice de l'activité de réassurance est motivée et est notifiée à l'entreprise de réassurance concernée.

Section 4

Informations statistiques