= Article 159

Informations statistiques relatives aux activités transfrontalières

Chaque entreprise d'assurance communique à l'autorité de contrôle compétente de son État membre d'origine, de manière distincte pour les opérations effectuées en vertu du droit d'établissement et pour celles effectuées dans le cadre de la libre prestation de services, le montant des primes, sinistres et commissions, sans déduction de la réassurance, par État membre et comme suit:

. a) pour l'assurance non-vie, par groupe de branches visées à l'annexe V;

. b) pour l'assurance vie, pour chacune des branches I à IX, visées à l'annexe II.

En ce qui concerne la branche 10 de la partie A de l'annexe I, à l'exclusion de la responsabilité du transporteur, l'entreprise concernée informe également cette autorité de contrôle de la fréquence et du coût moyen des sinistres.

Les autorités de contrôle de l'État membre d'origine communiquent les informations visées aux premier et deuxième alinéas dans un délai raisonnable et sous une forme agrégée aux autorités de contrôle de chacun des États membres concernés qui lui en font la demande.

Section 5

Traitement des contrats des succursales en cas de liquidation