== Article 72

=== Rôle des personnes chargées du contrôle des comptes

1.   Les États membres prévoient au moins que les personnes agréées au sens de la huitième directive 84/253/CEE du Conseil du 10 avril 1984 fondée sur l'article 54, paragraphe 3, point g), du traité, concernant l'agrément des personnes chargées du contrôle légal des documents comptables(34), qui procèdent, au sein d'une entreprise d'assurance ou de réassurance, au contrôle légal des comptes visé à l'article 51 de la directive 78/660/CEE, à l'article 37 de la directive 83/349/CEE ou à l'article 31 de la directive 85/611/CEE ou à toute autre mission légale, ont l'obligation de signaler sans délai aux autorités de contrôle tout fait ou décision concernant cette entreprise, dont elles ont eu connaissance dans l'exercice de cette mission et qui est de nature à entraîner l'une des conséquences suivantes:

. a) violer, sur le fond, les dispositions législatives, réglementaires ou administratives qui fixent les conditions d'agrément ou qui régissent, de manière spécifique, l'exercice de l'activité des entreprises d'assurance et de réassurance;

. b) porter atteinte à la continuité de l'exploitation de l'entreprise d'assurance ou de réassurance;

. c) entraîner le refus de la certification des comptes ou l'émission de réserves;

. d) entraîner le non-respect du capital de solvabilité requis;

. e) entraîner le non-respect du minimum de capital requis.

Les personnes visées au premier alinéa signalent également les faits ou décisions dont elles viendraient à avoir connaissance dans le cadre d'une mission visée au premier alinéa, exercée dans une entreprise qui a des liens étroits découlant d'une relation de contrôle avec l'entreprise d'assurance ou de réassurance auprès de laquelle elles s'acquittent de cette mission.

2.   La divulgation de bonne foi aux autorités de contrôle, par les personnes agréées au sens de la directive 84/253/CEE de faits ou décisions visés au paragraphe 1 ne constitue pas une violation d'une quelconque restriction à la divulgation d'informations imposée par contrat ou par une disposition législative, réglementaire ou administrative et n'entraîne pour ces personnes aucune responsabilité d'aucune sorte.

CHAPITRE V

Exercice simultané des activités d'assurance vie et non-vie