= Article 259

Compte rendu du CECAPP

1.   Le CECAPP participe, chaque année, au Parlement européen, à une audition générale en commission parlementaire. Lorsque cette participation coïncide avec l'obligation de faire rapport imposée au CECAPP par l'article 71, paragraphe 3, il est satisfait à cette obligation, en ce qui concerne le Parlement européen, par la participation du CECAPP à ladite audition.

2.   Lors de l'audition visée au paragraphe 1, le CECAPP rend notamment compte de toutes les expériences pertinentes et significatives acquises quant aux activités de contrôle et à la coopération entre contrôleurs dans le cadre du titre III, notamment en ce qui concerne:

. a) la procédure de nomination du contrôleur d'un groupe ainsi que le nombre et la répartition géographique des contrôleurs de groupe;

. b) le fonctionnement du collège des contrôleurs, en particulier l'implication et l'engagement des autorités de contrôle qui ne sont pas le contrôleur du groupe.

3.   Le CECAPP peut également, aux fins du paragraphe 1, s'il y a lieu, rendre compte des principaux enseignements tirés des examens visés à l'article 248, paragraphe 6.

CHAPITRE IV

Pays tiers