= Article 248

Droits et obligations du contrôleur du groupe et des autres contrôleurs – Collège des contrôleurs

1.   Les droits et obligations du contrôleur du groupe en matière de contrôle du groupe comportent ce qui suit:

. a) coordonner la collecte et la diffusion des informations utiles ou essentielles, dans la marche normale des affaires comme dans les situations d'urgence, y compris la diffusion des informations importantes pour le contrôle exercé par une autorité de contrôle;

. b) assurer le contrôle prudentiel et l'évaluation de la situation financière du groupe;

. c) évaluer le respect, par le groupe, des règles relatives à la solvabilité, à la concentration de risques et aux transactions intragroupe qui figurent aux articles 218 à 245;

. d) évaluer le système de gouvernance du groupe, conformément à l'article 246, ainsi que le respect, par les membres de l'organe d'administration, de gestion ou de contrôle de l'entreprise participante, des exigences énoncées aux articles 42 et 257;

. e) planifier et coordonner, par des réunions régulières se tenant au moins une fois l'an ou par tout autre moyen approprié, les activités de contrôle, dans la marche normale des affaires comme dans les situations d'urgence, en coopération avec les autorités de contrôle concernées, en tenant compte de la nature, de l'ampleur et de la complexité des risques inhérents à l'activité de toutes les entreprises faisant partie du groupe;

. f) effectuer les autres tâches et prendre les autres mesures et décisions incombant au contrôleur du groupe en vertu de la présente directive ou dérivant de l'application de la présente directive, notamment mener le processus de validation de tout modèle interne au niveau du groupe comme exposé aux articles 231 et 233 et mener le processus conduisant à autoriser l'application du régime prévu par les articles 237 à 240.

2.   Afin de faciliter l'exercice des tâches de contrôle du groupe visées au paragraphe 1, un collège des contrôleurs, présidé par le contrôleur du groupe, est constitué.

Dans le but de promouvoir la convergence de leurs activités et décisions respectives, le collège des contrôleurs veille à ce que la coopération, les échanges d'informations et les consultations entre les autorités de contrôle membres du collège des contrôleurs se déroulent bien conformément au titre III.

3.   La composition du collège des contrôleurs inclut le contrôleur du groupe et les autorités de contrôle de tous les États membres dans lesquels une entreprise filiale a son siège social.

Les autorités de contrôle dont dépendent les succursales importantes et les entreprises liées sont également autorisées à participer au collège des contrôleurs. Toutefois, leur participation se limite uniquement à la réalisation de l'objectif consistant à assurer un échange efficace des informations.

Le bon fonctionnement du collège des contrôleurs peut exiger que certaines activités soient menées par un nombre réduit d'autorités de contrôle au sein de celui-ci.

4.   Sans préjudice de toute mesure arrêtée en vertu de la présente directive, la création et le fonctionnement du collège des contrôleurs sont basés sur des accords de coordination conclus par le contrôleur du groupe et les autres autorités de contrôle concernées.

En cas de divergence de vues concernant ces accords de coordination, tout membre du collège des contrôleurs peut saisir le CECAPP.

Le contrôleur du groupe, après consultation des autorités de contrôle concernées, tient dûment compte de tout avis émis par le CECAPP dans un délai de deux mois à compter de la réception avant de prendre sa décision finale. La décision est dûment motivée et elle comporte une explication de tout écart significatif par rapport aux positions adoptées par le CECAPP. Le contrôleur du groupe transmet sa décision aux autres autorités de contrôle concernées.

5.   Sans préjudice de toute mesure arrêtée en vertu de la présente directive, les accords de coordination visés au paragraphe 4 précisent les procédures:

. a) que doivent suivre les autorités de contrôle concernées pour prendre des décisions conformément aux articles 231, 232 et 247;

. b) pour la consultation au titre du paragraphe 4 du présent article et de l'article 218, paragraphe 5.

Sans préjudice des droits et devoirs conférés par la présente directive au contrôleur du groupe et aux autres autorités de contrôle, les accords de coordination peuvent confier des tâches supplémentaires au contrôleur du groupe ou à d'autres autorités de contrôle lorsqu'il en résulte un contrôle plus efficace du groupe et que les activités de contrôle des membres du collège des contrôleurs, pour ce qui relève de leur responsabilité individuelle, ne s'en trouvent pas entravées.

En outre, les accords de coordination peuvent préciser les procédures applicables à:

. a) la consultation entre les autorités de contrôle concernées, notamment dans les cas visés aux articles 213 à 217, 219 à 221, 227, 244 à 246, 250, 256, 260 et 262;

. b) la coopération avec d'autres autorités de contrôle.

6.   Le CECAPP élabore des orientations pour le fonctionnement opérationnel des collèges des contrôleurs, sur la base d'un examen approfondi de leurs travaux afin d'évaluer le niveau de convergence existant entre eux. Cet examen a lieu au moins tous les trois ans. Les États membres veillent à ce que le contrôleur du groupe transmette au CECAPP les informations pertinentes pour cet examen sur le fonctionnement des collèges des contrôleurs et sur toutes les difficultés rencontrées.

7.   La Commission arrête des mesures d'exécution pour la coordination du contrôle du groupe aux fins des paragraphes 1 à 6, y compris la définition de ce qu'est une «succursale importante».

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.