== Article 255

=== Vérification des informations

1.   Les États membres veillent à ce que leurs autorités de contrôle puissent procéder sur leur territoire, directement ou par l'intermédiaire de personnes qu'elles mandatent à cet effet, à la vérification sur place des informations visées à l'article 254 dans les locaux de chacune des entreprises suivantes:

. a) l'entreprise d'assurance ou de réassurance soumise au contrôle du groupe;

. b) les entreprises liés à cette entreprise d'assurance ou de réassurance;

. c) les entreprises mères de cette entreprise d'assurance ou de réassurance;

. d) les entreprises liées d'une entreprise mère de cette entreprise d'assurance ou de réassurance.

2.   Lorsque les autorités de contrôle souhaitent, dans des cas déterminés, vérifier les informations relatives à une entreprise, réglementée ou non, qui appartient à un groupe et est située dans un autre État membre, elles demandent aux autorités de contrôle de cet autre État membre de faire en sorte que cette vérification soit effectuée.

Les autorités qui reçoivent une telle demande y donnent suite, dans le cadre de leurs compétences, soit en procédant directement à cette vérification, soit en autorisant un réviseur ou un expert à y procéder, soit en autorisant l'autorité qui a présenté la demande à y procéder elle-même. Le contrôleur du groupe est informé des mesures prises.

Lorsqu'elle ne procède pas directement à la vérification, l'autorité de contrôle qui a présenté la demande peut, si elle le souhaite, y participer.