= Article 258

Mesures visant au respect des dispositions applicables

1.   Lorsque les entreprises d'assurance ou de réassurance d'un groupe ne se conforment pas aux exigences visées aux articles 218 à 246, ou lorsque ces exigences sont respectées mais que la solvabilité risque malgré tout d'être compromise, ou lorsque les transactions intragroupe ou les concentrations de risques menacent la situation financière desdites entreprises d'assurance ou de réassurance, les mesures nécessaires pour remédier dès que possible à cette situation sont imposées par:

. a) le contrôleur du groupe en ce qui concerne la société holding d'assurance;

. b) les autorités de contrôle en ce qui concerne les entreprises d'assurance et de réassurance.

Lorsque, dans le cas visé au premier alinéa, point a), le contrôleur du groupe n'est pas l'une des autorités de contrôle de l'État membre dans lequel la société holding d'assurance a son siège social, le contrôleur du groupe informe ces autorités de ses conclusions afin de leur permettre de prendre les mesures nécessaires.

Lorsque, dans le cas visé au premier alinéa, point b), le contrôleur du groupe n'est pas l'une des autorités de contrôle de l'État membre dans lequel l'entreprise d'assurance ou de réassurance a son siège social, le contrôleur du groupe informe ces autorités de ses conclusions afin de leur permettre de prendre les mesures nécessaires.

Sans préjudice du paragraphe 2, les États membres déterminent les mesures que leurs autorités de contrôle peuvent prendre à l'égard des sociétés holding d'assurance.

Les autorités de contrôle concernées, y compris le contrôleur du groupe, coordonnent, s'il y a lieu, leurs mesures visant au respect des dispositions applicables.

2.   Sans préjudice de leurs dispositions de droit pénal, les États membres veillent à ce que des sanctions ou des mesures puissent être imposées aux sociétés holding d'assurance qui enfreignent les dispositions législatives, réglementaires ou administratives prises pour la mise en œuvre du présent titre, ou à la personne qui gère effectivement ces sociétés. Les autorités de contrôle coopèrent étroitement pour veiller à ce que ces sanctions ou mesures soient effectives, en particulier lorsque le siège social de la société holding d'assurance n'est pas le lieu où se trouve son administration centrale ou son principal établissement.

3.   La Commission peut arrêter des mesures d'exécution pour la coordination des mesures visées aux paragraphes 1 et 2 visant au respect des dispositions applicables.

Ces mesures d'exécution, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.