= Article 256

Rapport sur la solvabilité et la situation financière du groupe

1.   Les États membres requièrent des entreprises d'assurance et de réassurance participantes ou des sociétés holding d'assurance qu'elles publient annuellement un rapport sur la solvabilité et la situation financière au niveau du groupe. Les articles 51 et 53 à 55 s'appliquentmutatis mutandis.

2.   Lorsqu'une entreprise d'assurance ou de réassurance participante ou une société holding d'assurance le décide, elle peut, sous réserve de l'accord du contrôleur du groupe, publier un rapport unique sur la solvabilité et la situation financière contenant les éléments suivants:

. a) les informations au niveau du groupe qui doivent être publiées conformément au paragraphe 1;

. b) les informations relatives à toute filiale du groupe qui doivent être identifiables individuellement et publiées conformément aux articles 51 et 53 à 55.

Avant de donner l'accord prévu au premier alinéa, le contrôleur du groupe consulte les membres du collège des contrôleurs et tient dûment compte de l'avis et des réserves exprimés par eux.

3.   Lorsque le rapport visé au paragraphe 2 ne contient pas les informations que l'autorité de contrôle ayant agréé une filiale du groupe demande aux entreprises comparables de publier, l'autorité de contrôle concernée est habilitée, si cette omission est substantielle, à exiger que la filiale concernée publie les informations complémentaires nécessaires.

4.   La Commission arrête des mesures d'exécution précisant, en ce qui concerne le rapport unique sur la solvabilité et la situation financière, les informations qui doivent faire l'objet d'une publication et les moyens d'y procéder.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.