== Article 249

=== Coopération et échange d'informations entre les autorités de contrôle

1.   Les autorités responsables du contrôle des diverses entreprises d'assurance et de réassurance appartenant à un groupe et le contrôleur de ce groupe coopèrent étroitement, en particulier dans les cas ou une entreprise d'assurance ou de réassurance connaît des difficultés financières.

Afin d'assurer que les autorités de contrôle, y compris le contrôleur du groupe, disposent des mêmes informations pertinentes disponibles, sans préjudice de leurs responsabilités respectives et indépendamment du fait qu'elles soient établies ou non dans le même État membre, elles échangent entre elles ces informations pour permettre et faciliter l'exercice des tâches de contrôle des autres autorités au titre de la présente directive. À cette fin, les autorités de contrôle concernées et le contrôleur du groupe se communiquent sans délai toute information pertinente dès qu'elle devient disponible. Les informations visées au présent alinéa comprennent, sans s'y limiter, les informations concernant des actions du groupe et des autorités de contrôle, ainsi que les informations fournies par le groupe.

2.   Les autorités responsables du contrôle des diverses entreprises d'assurance et de réassurance appartenant à un groupe et le contrôleur de ce groupe convoquent chacune immédiatement une réunion de toutes les autorités de contrôle impliquées dans le contrôle du groupe au moins dans les circonstances suivantes:

. a) quand elles ont connaissance de l'existence d'une violation sérieuse de l'exigence relative au capital de solvabilité requis ou d'une violation de l'exigence relative au minimum de capital requis, de la part d'une entreprise d'assurance ou de réassurance particulière;

. b) quand elles constatent un écart important par rapport au capital de solvabilité requis, au niveau du groupe, calculé sur la base des données consolidées, ou au capital de solvabilité requis du groupe sur une base agrégée, selon la méthode de calcul appliquée conformément au titre III, chapitre II, section 1, sous-section 4;

. c) lorsque toute autre circonstance exceptionnelle se produit ou s'est produite.

3.   La Commission arrête des mesures d'exécution déterminant les éléments devant être systématiquement rassemblés par le contrôleur du groupe et transmis aux autres autorités de contrôle concernées ou transmis au contrôleur du groupe par les autres autorités de contrôle concernées.

La Commission arrête des mesures d'exécution précisant les éléments essentiels ou pertinents pour le contrôle au niveau du groupe en vue d'améliorer la convergence des informations communiquées aux fin du contrôle.

Les mesures visées au présent paragraphe, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.