= Article 250

Consultation entre autorités de contrôle

1.   Sans préjudice de l'article 248, avant toute décision importante pour les tâches de contrôle des autres autorités de contrôle, les autorités de contrôle concernées se consultent, au sein du collège des contrôleurs, sur ce qui suit:

. a) les modifications de la structure de l'actionnariat, de l'organisation ou de la gestion des entreprises d'assurance ou de réassurance d'un groupe, requérant l'approbation ou l'autorisation des autorités de contrôle; et

. b) les principales sanctions et les mesures exceptionnelles prises par les autorités de contrôle, y compris l'application d'une exigence de capital supplémentaire s'ajoutant au capital de solvabilité requis conformément à l'article 37 et l'application de toute limitation de l'utilisation d'un modèle interne pour le calcul du capital de solvabilité requis conformément au titre I, chapitre VI, section 4, sous-section 3.

Aux fins du point b), le contrôleur du groupe est toujours consulté.

En outre, les autorités de contrôle concernées se consultent avant toute décision lorsque celle-ci est fondée sur les informations reçues d'autres autorités de contrôle.

2.   Sans préjudice de l'article 248, une autorité de contrôle peut décider de ne pas opérer de consultation en cas d'urgence ou lorsque cette consultation risquerait de compromettre l'efficacité de la décision. En pareil cas, l'autorité de contrôle informe sans délai les autres autorités de contrôle concernées.