== Article 52

=== Informations communiquées au CECAPP et par lui

1.   Les États membres exigent des autorités de contrôle qu'elles fournissent annuellement les informations suivantes au CECAPP:

. a) le montant moyen des exigences de capital supplémentaire par entreprise et la répartition des exigences de capital supplémentaire imposées par les autorités de contrôle durant l'année précédente, en pourcentage du capital de solvabilité requis et selon la ventilation suivante:i)pour l'ensemble des entreprises d'assurance et de réassurance;ii)pour les entreprises d'assurance vie;iii)pour les entreprises d'assurance non-vie;iv)pour les entreprises d'assurance exerçant leurs activités à la fois en vie et en non-vie;v)pour les entreprises de réassurance;

. i) pour l'ensemble des entreprises d'assurance et de réassurance;

. ii) pour les entreprises d'assurance vie;

. iii) pour les entreprises d'assurance non-vie;

. iv) pour les entreprises d'assurance exerçant leurs activités à la fois en vie et en non-vie;

. v) pour les entreprises de réassurance;

. b) pour chacune des publications prévues au point a), la proportion d'exigences de capital supplémentaire imposées respectivement en vertu de l'article 37, paragraphe 1, points a), b) et c).

2.   Le CECAPP publie annuellement les informations suivantes:

. a) pour l'ensemble des États membres, la répartition totale des exigences de capital supplémentaire, en pourcentage du capital de solvabilité requis, pour chacune des catégories d'entreprises suivantes:i)l'ensemble des entreprises d'assurance et de réassurance;ii)les entreprises d'assurance vie;iii)les entreprises d'assurance non-vie;iv)les entreprises d'assurance exerçant leurs activités à la fois en vie et en non-vie;v)les entreprises de réassurance;

. i) l'ensemble des entreprises d'assurance et de réassurance;

. ii) les entreprises d'assurance vie;

. iii) les entreprises d'assurance non-vie;

. iv) les entreprises d'assurance exerçant leurs activités à la fois en vie et en non-vie;

. v) les entreprises de réassurance;

. b) pour chaque État membre séparément, la répartition des exigences de capital supplémentaire, en pourcentage du capital de solvabilité requis, pour l'ensemble des entreprises d'assurance et de réassurance dudit État membre;

. c) pour chacune des publications visées aux points a) et b), la proportion d'exigences de capital supplémentaire imposées respectivement en vertu de l'article 37, paragraphe 1, points a), b) et c).

3.   Le CECAPP communique au Parlement européen, au Conseil et à la Commission les informations visées au paragraphe 2, assorties d'un rapport mettant en évidence le degré de convergence du contrôle, dans le recours aux exigences de capital supplémentaire, entre les autorités de contrôle des différents États membres.