= Article 54

Rapport sur la solvabilité et la situation financière: actualisations et communication spontanée d'informations supplémentaires

1.   En cas d'événement majeur affectant significativement la pertinence des informations communiquées en vertu des articles 51 et 53, les entreprises d'assurance et de réassurance publient des informations appropriées sur la nature et les effets dudit événement majeur.

Aux fins du premier alinéa, sont au moins considérées comme des événements majeurs les circonstances suivantes:

. a) lorsqu'un écart par rapport au minimum de capital requis est observé et que les autorités de contrôle considèrent que l'entreprise ne sera pas en mesure de leur soumettre un plan réaliste de financement à court terme ou qu'elles n'obtiennent pas ce plan dans un délai d'un mois à compter de la date où l'écart a été observé;

. b) lorsqu'un écart important par rapport au capital de solvabilité requis est observé et que les autorités de contrôle n'obtiennent pas de programme réaliste de rétablissement dans un délai de deux mois à compter de la date où l'écart a été observé.

En ce qui concerne le deuxième alinéa, point a), les autorités de contrôle exigent de l'entreprise concernée qu'elle publie immédiatement le montant de l'écart constaté, assorti d'une explication quant à son origine et ses conséquences et quant à toute mesure corrective qui aurait été prise. Si, en dépit d'un plan de financement à court terme initialement considéré comme réaliste, un écart par rapport au minimum de capital requis n'a pas été corrigé trois mois après qu'il a été constaté, il est publié à l'expiration de ce délai, avec une explication quant à son origine et ses conséquences y compris quant aux mesures correctives prises et à toute nouvelle mesure corrective prévue.

En ce qui concerne le deuxième alinéa, point b), les autorités de contrôle exigent de l'entreprise concernée qu'elle publie immédiatement le montant de l'écart constaté, assorti d'une explication quant à son origine et ses conséquences et quant à toute mesure corrective qui aurait été prise. Si, en dépit d'un programme de rétablissement initialement considéré comme réaliste, un écart important par rapport au capital de solvabilité requis n'a pas été corrigé six mois après qu'il a été constaté, il est publié à l'expiration de ce délai, avec une explication quant à son origine et ses conséquences, y compris quant aux mesures correctives prises et à toute nouvelle mesure corrective prévue.

2.   Les entreprises d'assurance et de réassurance peuvent publier spontanément toute information ou explication, relative à leur solvabilité et à leur situation financière dont la publication n'est pas déjà exigée en vertu des articles 51 et 53 et du paragraphe 1 du présent article.