= Article 53

Rapport sur la solvabilité et la situation financière: principes applicables

1.   Les entreprises d'assurance et de réassurance sont autorisées par les autorités de contrôle à ne pas publier une information dans les cas suivants:

. a) la publication de cette information conférerait aux concurrents de l'entreprise concernée un avantage indu important;

. b) l'entreprise est tenue au secret ou à la confidentialité en raison d'obligations à l'égard des preneurs ou de toute autre relation avec une contrepartie.

2.   Lorsque la non-publication d'une information est autorisée par l'autorité de contrôle, l'entreprise concernée l'indique dans son rapport sur sa solvabilité et sa situation financière et en explique les raisons.

3.   Les autorités de contrôle autorisent les entreprises d'assurance et de réassurance à utiliser – ou à se référer à – des informations publiées en vertu d'autres exigences législatives ou réglementaires, dans la mesure où ces informations sont équivalentes, tant dans leur nature que dans leur portée, aux informations exigées en vertu de l'article 51.

4.   Les paragraphes 1 et 2 ne s'appliquent pas aux informations visées à l'article 51, paragraphe 1, point e).