= Article 139

Non-conformité du minimum de capital requis

1.   Les entreprises d'assurance et de réassurance informent immédiatement l'autorité de contrôle lorsqu'elles constatent que le minimum de capital requis n'est plus conforme, ou qu'il risque de ne plus l'être dans les trois prochains mois.

2.   Dans un délai d'un mois à compter de la constatation de la non-conformité du minimum de capital requis, l'entreprise d'assurance ou de réassurance concernée soumet à l'approbation de l'autorité de contrôle un plan de financement réaliste à court terme en vue de ramener, dans un délai de trois mois après cette constatation, les fonds propres de base éligibles au moins au niveau du minimum de capital requis ou de réduire son profil de risque pour garantir la conformité du minimum de capital requis.

3.   L'autorité de contrôle de l'État membre d'origine peut en outre restreindre ou interdire la libre disposition des actifs de l'entreprise d'assurance ou de réassurance. Elle en informe les autorités de contrôle des États membres d'accueil. Ces dernières prennent, à la demande de l'autorité de contrôle de l'État membre d'origine, les mêmes mesures. L'autorité de contrôle de l'État membre d'origine désigne les actifs devant faire l'objet de ces mesures.