= Article 144

Retrait de l'agrément

1.   L'autorité de contrôle de l'État membre d'origine peut retirer l'agrément accordé à une entreprise d'assurance ou de réassurance lorsque l'entreprise concernée:

. a) ne fait pas usage de l'agrément dans un délai de douze mois, y renonce expressément ou a cessé d'exercer son activité pendant une période supérieure à six mois, à moins que l'État membre concerné ne prévoie que l'agrément devient caduc dans ces cas;

. b) ne satisfait plus aux conditions d'agrément;

. c) manque gravement aux obligations qui lui incombent en vertu de la réglementation qui lui est applicable.

L'autorité de contrôle de l'État membre d'origine retire l'agrément accordé à une entreprise d'assurance ou de réassurance lorsque l'entreprise concernée ne dispose plus du minimum de capital requis et que l'autorité de contrôle considère que le plan de financement présenté est manifestement insuffisant ou que l'entreprise concernée ne se conforme pas au plan approuvé dans les trois mois qui suivent la constatation de la non-conformité du minimum de capital requis.

2.   En cas de retrait ou de caducité de l'agrément, l'autorité de contrôle de l'État membre d'origine en informe les autorités de contrôle des autres États membres, lesquelles prennent les mesures appropriées pour empêcher l'entreprise d'assurance ou de réassurance concernée de commencer de nouvelles opérations sur leur territoire.

L'autorité de contrôle de l'État membre d'origine prend, en collaboration avec ces autorités, toute mesure nécessaire pour sauvegarder les intérêts des assurés et restreint notamment la libre disposition des actifs de l'entreprise d'assurance conformément à l'article 140.

3.   Toute décision de retrait de l'agrément est dûment motivée et est notifiée à l'entreprise d'assurance ou de réassurance concernée.

CHAPITRE VIII

Droit d'établissement et libre prestation de services

Section 1

Établissement des entreprises d'assurance