== Article 142

=== Programme de rétablissement et plan de financement

1.   Le programme de rétablissement visé à l'article 138, paragraphe 2, et le plan de financement visé à l'article 139, paragraphe 2, comprennent au moins les indications ou justifications concernant les éléments suivants:

. a) une estimation des frais de gestion, notamment des frais généraux courants et des commissions;

. b) une estimation des recettes et des dépenses pour les affaires directes, les acceptations en réassurance et les cessions en réassurance;

. c) un bilan prévisionnel;

. d) une estimation des moyens financiers destinés à la couverture des provisions techniques ainsi que du capital de solvabilité requis et du minimum de capital requis;

. e) la politique générale en matière de réassurance.

2.   Lorsqu'elles ont exigé la présentation du programme de rétablissement visé à l'article 138, paragraphe 2, ou du plan de financement visé à l'article 139, paragraphe 2, conformément au paragraphe 1 du présent article, les autorités de contrôle s'abstiennent de délivrer l'attestation visée à l'article 39, aussi longtemps qu'elles jugent que les droits des preneurs ou les obligations contractuelles de l'entreprise de réassurance sont menacés.