= Article 138

Non-conformité du capital de solvabilité requis

1.   Les entreprises d'assurance et de réassurance informent immédiatement l'autorité de contrôle lorsqu'elles constatent que le capital de solvabilité requis n'est plus conforme, ou qu'il risque de ne plus l'être dans les trois prochains mois.

2.   Dans un délai de deux mois à compter de la constatation de la non-conformité du capital de solvabilité requis, l'entreprise d'assurance ou de réassurance concernée soumet un programme de rétablissement réaliste à l'approbation de l'autorité de contrôle.

3.   L'autorité de contrôle exige de l'entreprise d'assurance ou de réassurance concernée qu'elle prenne les mesures nécessaires pour rétablir, dans un délai de six mois après la constatation de la non-conformité du capital de solvabilité requis, le niveau de fonds propres éligibles couvrant le capital de solvabilité requis ou réduire son profil de risque afin de garantir la conformité du capital de solvabilité requis.

L'autorité de contrôle peut, s'il y a lieu, prolonger cette période de trois mois.

4.   En cas de baisse exceptionnelle sur les marchés financiers, l'autorité de contrôle peut prolonger la période visée au paragraphe 3, deuxième alinéa, pour une durée appropriée en prenant en compte tous les facteurs pertinents.

L'entreprise d'assurance ou de réassurance concernée soumet tous les trois mois à son autorité de contrôle un rapport d'étape exposant les mesures prises et les progrès accomplis pour rétablir le niveau de fonds propres éligibles correspondant au capital de solvabilité requis ou pour réduire son profil de risque afin de garantir la conformité du capital de solvabilité requis.

La prolongation visée au premier alinéa est retirée lorsque le rapport d'étape montre qu'aucun progrès significatif n'a été accompli par l'entreprise afin de rétablir le niveau de fonds propres éligibles correspondant au capital de solvabilité requis ou de réduire le profil de risque afin de garantir la conformité du capital de solvabilité requis, entre la date de la constatation de la non-conformité du capital de solvabilité requis et la date de remise du rapport d'étape.

5.   Dans des circonstances exceptionnelles, lorsqu'elle est d'avis que la situation financière de l'entreprise concernée va continuer à se détériorer, l'autorité de contrôle peut également restreindre ou interdire la libre disposition de ses actifs. Elle informe les autorités de contrôle des États membres d'accueil de toute mesure prise. Ces dernières prennent, à la demande de l'autorité de contrôle de l'État membre d'origine, les mêmes mesures. L'autorité de contrôle de l'État membre d'origine désigne les actifs devant faire l'objet de ces mesures.