== Article 179

=== Obligations connexes

1.   Les entreprises d'assurance non-vie peuvent offrir et conclure des contrats d'assurance obligatoire dans les conditions énoncées au présent article.

2.   Lorsqu'un État membre impose l'obligation de souscrire une assurance, un contrat d'assurance ne satisfait à cette obligation que s'il est conforme aux dispositions spécifiques relatives à cette assurance qui sont prévues par cet État membre.

3.   Lorsqu'un État membre impose une obligation d'assurance et que l'entreprise d'assurance est tenue de déclarer toute cessation de garantie aux autorités de contrôle, cette cessation n'est opposable aux tiers lésés que dans les conditions prévues par cet État membre.

4.   Chaque État membre communique à la Commission les risques pour lesquels sa législation impose une obligation d'assurance, en indiquant:

. a) les dispositions juridiques spécifiques relatives à cette assurance;

. b) les éléments qui doivent figurer dans l'attestation que l'entreprise d'assurance non-vie doit délivrer à l'assuré, lorsque cet État membre exige une preuve que l'obligation d'assurance a été remplie.

Un État membre peut exiger que les éléments visés au premier alinéa, point b), comprennent une déclaration de l'entreprise d'assurance selon laquelle le contrat est conforme aux dispositions spécifiques relatives à cette assurance.

La Commission publie les éléments visés au premier alinéa, point b), auJournal officiel de l'Union européenne.

Section 3

Intérêt général