= Article 272

Informations des créanciers connus et droit de production des créances

1.   Lorsque la législation de l'État membre d'origine exige la production d'une créance en vue de sa reconnaissance ou prévoit la notification obligatoire d'une mesure d'assainissement aux créanciers ayant leur résidence habituelle, leur domicile ou leur siège social dans cet État membre, les autorités compétentes de l'État membre d'origine ou l'administrateur informent également les créanciers connus qui ont leur résidence habituelle, leur domicile ou leur siège social dans un autre État membre, conformément à l'article 281 et à l'article 283, paragraphe 1.

2.   Lorsque la législation de l'État membre d'origine prévoit le droit pour les créanciers ayant leur résidence habituelle, leur domicile ou leur siège social dans cet État membre de produire leurs créances ou de présenter des observations relatives à leurs créances, les créanciers ayant leur résidence habituelle, leur domicile ou leur siège social dans un autre État membre bénéficient de ce même droit conformément à l'article 282 et à l'article 283, paragraphe 2.

CHAPITRE III

Procédure de liquidation