== Article 271

=== Publication des décisions relatives aux mesures d'assainissement

1.   Lorsqu'un recours est possible dans l'État membre d'origine contre une mesure d'assainissement, les autorités compétentes de l'État membre d'origine, l'administrateur ou toute personne habilitée à cet effet dans l'État membre d'origine assurent la publication de la décision relative à une mesure d'assainissement conformément aux modalités prévues dans l'État membre d'origine en matière de publication et, en outre, publient dès que possible auJournal officiel de l'Union européenneun extrait du document établissant la mesure d'assainissement.

Les autorités de contrôle des autres États membres qui ont été informées de la décision relative à une mesure d'assainissement conformément à l'article 270 peuvent assurer la publication de cette décision sur leur territoire de la manière qu'elles jugent appropriée.

2.   Les publications prévues au paragraphe 1 indiquent l'autorité compétente de l'État membre d'origine, le droit applicable conformément à l'article 269, paragraphe 3, ainsi que l'administrateur désigné, le cas échéant. Elles sont assurées dans la langue officielle ou dans une des langues officielles de l'État membre dans lequel l'information est publiée.

3.   Les mesures d'assainissement s'appliquent indépendamment des dispositions concernant la publication énoncées aux paragraphes 1 et 2 et produisent leurs pleins effets à l'égard des créanciers à moins que les autorités compétentes de l'État membre d'origine ou le droit de cet État membre n'en disposent autrement.

4.   Lorsque les mesures d'assainissement affectent exclusivement les droits des actionnaires, des associés ou des employés d'une entreprise d'assurance, considérés en tant que tels, les paragraphes 1, 2 et 3 ne s'appliquent pas, sauf si le droit applicable aux mesures d'assainissement en dispose autrement.

Les autorités compétentes déterminent la manière dont les parties visées au premier alinéa doivent être informées conformément au droit applicable.