= Article 269

Adoption de mesures d'assainissement – Droit applicable

1.   Seules les autorités compétentes de l'État membre d'origine sont habilitées à décider de mesures d'assainissement concernant une entreprise d'assurance, y compris pour ses succursales.

2.   Les mesures d'assainissement n'empêchent pas l'ouverture d'une procédure de liquidation par l'État membre d'origine.

3.   Les mesures d'assainissement sont régies par les lois, règlements et procédures applicables dans l'État membre d'origine, sauf dispositions contraires des articles 285 à 292.

4.   Les mesures d'assainissement prises selon la législation de l'État membre d'origine produisent leurs pleins effets dans toute la Communauté sans aucune autre formalité, y compris à l'égard des tiers dans les autres États membres, même lorsque la législation de ces autres États membres ne prévoit pas de telles mesures d'assainissement ou bien soumet leur mise en œuvre à des conditions qui ne sont pas remplies.

5.   Les mesures d'assainissement produisent leurs effets dans toute la Communauté dès qu'elles produisent leurs effets dans l'État membre d'origine.