== Article 260

=== Entreprises mères ayant leur siège en dehors de la Communauté: vérification de l'équivalence

1.   Dans le cas visé à l'article 213, paragraphe 2, point c), les autorités de contrôle concernées vérifient si les entreprises d'assurance et de réassurance dont l'entreprise mère a son siège social en dehors de la Communauté sont soumises à un contrôle, par une autorité de contrôle d'un pays tiers, équivalent à celui prévu par le présent titre au niveau du groupe pour les entreprises d'assurance et de réassurance visées à l'article 213, paragraphe 2, points a) et b).

La vérification est effectuée par l'autorité de contrôle qui jouerait le rôle de contrôleur du groupe si les critères énoncés à l'article 247, paragraphe 2, devaient s'appliquer, à la demande de l'entreprise mère ou de l'une des entreprises d'assurance et de réassurance agréées dans la Communauté, ou de sa propre initiative, sauf si la Commission s'est préalablement prononcée sur l'équivalence du pays tiers concerné. Ce faisant, cette autorité de contrôle consulte les autres autorités de contrôle concernées ainsi que le CECAPP, avant de se prononcer.

2.   La Commission peut arrêter des mesures d'exécution précisant les critères permettant d'évaluer si le régime prudentiel d'un pays tiers pour le contrôle des groupes équivaut ou non à celui établi par le présent titre. Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

3.   La Commission peut décider, après consultation du comité européen des assurances et des pensions professionnelles et en conformité avec la procédure de réglementation visée à l'article 301, paragraphe 2, en prenant en compte les critères arrêtés en vertu du paragraphe 2, si le régime prudentiel de contrôle des groupes dans un pays tiers équivaut ou non à celui établi par le présent titre.

Ces décisions sont régulièrement réexaminées pour tenir compte de toute modification éventuellement apportée au régime prudentiel de contrôle des groupes établi par le présent titre ou à celui du pays tiers, ainsi que de toute autre modification réglementaire pouvant avoir une incidence sur la décision relative à l'équivalence.

Lorsqu'une décision a été adoptée par la Commission à l'égard d'un pays tiers conformément au premier alinéa, elle est considérée comme déterminante pour la vérification visée au paragraphe 1.