== Article 264

=== Coopération avec les autorités de contrôle de pays tiers

1.   La Commission peut soumettre des propositions au Conseil en vue de négocier des accords avec un ou plusieurs pays tiers concernant les modes d'exercice du contrôle des groupes à l'égard:

. a) des entreprises d'assurance ou de réassurance ayant pour entreprises participantes des entreprises au sens de l'article 213 dont le siège social est situé dans un pays tiers; et

. b) des entreprises d'assurance ou de réassurance de pays tiers ayant pour entreprises participantes des entreprises au sens de l'article 213 dont le siège social est situé dans la Communauté.

2.   Les accords visés au paragraphe 1 ont notamment pour finalité de garantir:

. a) que les autorités de contrôle des États membres puissent obtenir les informations nécessaires au contrôle, au niveau du groupe, des entreprises d'assurance et de réassurance dont le siège social est situé dans la Communauté et qui ont des filiales ou détiennent des participations dans des entreprises hors de la Communauté; et

. b) que les autorités de contrôle des pays tiers puissent obtenir les informations nécessaires au contrôle, au niveau du groupe, des entreprises d'assurance et de réassurance de pays tiers dont le siège social est situé sur leur territoire et qui ont des filiales ou détiennent des participations dans des entreprises dans un ou plusieurs États membres.

3.   Sans préjudice de l'article 300, paragraphes 1 et 2, du traité, la Commission, assistée du comité européen des assurances et des pensions professionnelles, évalue l'issue des négociations visées au paragraphe 1.

CHAPITRE V

Sociétés holding mixtes d'assurance