= Article 263

Entreprises mères ayant leur siège en dehors de la Communauté: niveaux

Lorsque l'entreprise mère visée à l'article 260 est elle-même filiale d'une société holding d'assurance ayant son siège social en dehors de la Communauté ou d'une entreprise d'assurance ou de réassurance d'un pays tiers, les États membres procèdent à la vérification prévue par l'article 260 uniquement au niveau de l'entreprise mère supérieure qui est une société holding d'assurance d'un pays tiers, une entreprise d'assurance d'un pays tiers ou une entreprise de réassurance d'un pays tiers.

Cependant, les États membres permettent à leurs autorités de contrôle de décider, en l'absence d'un contrôle équivalent au sens de l'article 260, de procéder à une nouvelle vérification à un niveau inférieur où existe une entreprise mère d'entreprises d'assurance ou de réassurance, qu'il s'agisse d'une société holding d'assurance d'un pays tiers, d'une entreprise d'assurance d'un pays tiers ou d'une entreprise de réassurance d'un pays tiers.

Dans ce cas, l'autorité de contrôle visée à l'article 260, paragraphe 1, deuxième alinéa, explique sa décision au groupe.

L'article 262 s'appliquemutatis mutandis.