== Article 262

=== Entreprises mères ayant leur siège en dehors de la Communauté: absence d'équivalence

1.   À défaut de contrôle équivalent tel que visé à l'article 260, les États membres appliquent aux entreprises d'assurance et de réassurance soit les articles 218 à 258,mutatis mutandiset à l'exception des articles 236 à 243, soit l'une des méthodes exposées au paragraphe 2.

Les principes généraux et méthodes exposés aux articles 218 à 258 s'appliquent au niveau de la société holding d'assurance, de l'entreprise d'assurance du pays tiers ou de l'entreprise de réassurance du pays tiers.

Aux seules fins du calcul de la solvabilité du groupe, l'entreprise mère est considérée comme une entreprise d'assurance ou de réassurance soumise aux conditions établies au titre I, chapitre VI, section 3, sous-sections 1, 2 et 3, en ce qui concerne les fonds propres éligibles à la couverture du capital de solvabilité requis et à l'une des exigences suivantes:

. a) un capital de solvabilité requis déterminé conformément aux principes de l'article 226 s'il s'agit d'une société holding d'assurance;

. b) un capital de solvabilité requis déterminé conformément aux principes de l'article 227 s'il s'agit d'une entreprise d'assurance ou de réassurance d'un pays tiers.

2.   Les États membres permettent à leurs autorités de contrôle d'appliquer d'autres méthodes garantissant un contrôle approprié des entreprises d'assurance et de réassurance appartenant à un groupe. Ces méthodes doivent avoir été approuvées par le contrôleur du groupe, après consultation des autres autorités de contrôle concernées.

Les autorités de contrôle peuvent, en particulier, exiger la constitution d'une société holding d'assurance ayant son siège social dans la Communauté, et appliquer le présent titre aux entreprises d'assurance et de réassurance du groupe dirigé par cette société holding d'assurance.

Les méthodes choisies doivent permettre la réalisation des objectifs de contrôle des groupes conformément au présent titre et elles sont communiquées aux autres autorités de contrôle concernées ainsi qu'à la Commission.