== Article 236

=== Filiales d'une entreprise d'assurance ou de réassurance: conditions

Les États membres prévoient que les règles énoncées aux articles 238 et 239 s'appliquent à toute entreprise d'assurance ou de réassurance qui est la filiale d'une entreprise d'assurance ou de réassurance, lorsque toutes les conditions suivantes sont réunies:

. a) la filiale, à l'égard de laquelle le contrôleur du groupe n'a pas pris la décision visée à l'article 214, paragraphe 2, est incluse dans le contrôle du groupe réalisé par ledit contrôleur au niveau de l'entreprise mère conformément au présent titre;

. b) les procédures de gestion des risques et les mécanismes de contrôle interne de l'entreprise mère couvrent la filiale et les autorités de contrôle concernées sont satisfaites de la gestion prudente de la filiale par l'entreprise mère;

. c) l'entreprise mère a reçu l'accord visé à l'article 246, paragraphe 4, troisième alinéa;

. d) l'entreprise mère a reçu l'accord visé à l'article 256, paragraphe 2;

. e) l'entreprise mère a demandé l'autorisation d'être assujettie aux articles 238 et 239 et sa demande a fait l'objet d'une décision favorable prise conformément à la procédure prévue à l'article 237.