== Article 237

=== Filiales d'une entreprise d'assurance ou de réassurance: décision relative à la demande

1.   En cas de demande d'autorisation d'assujettissement aux règles énoncées aux articles 238 et 239, les autorités de contrôle concernées travaillent ensemble au sein du collège des contrôleurs, en pleine concertation, en vue de décider s'il convient ou non d'accorder l'autorisation demandée et, le cas échéant, pour en définir les conditions.

La demande visée au premier alinéa n'est adressée qu'à l'autorité de contrôle ayant agréé la filiale. Ladite autorité de contrôle informe les autres autorités de contrôle au sein du collège des contrôleurs et leur communique la demande complète sans délai.

2.   Les autorités de contrôle concernées font tout ce qui est en leur pouvoir pour parvenir à une décision conjointe sur la demande dans un délai de trois mois à compter de la réception de la demande complète par toutes les autorités de contrôle au sein du collège des contrôleurs.

3.   Au cours de la période visée au paragraphe 2, en cas de divergence de vues au sujet de l'approbation de la demande visée au paragraphe 1, le contrôleur du groupe ou toute autre autorité de contrôle concernée peut consulter le CECAPP. Lorsque le CECAPP est consulté, toutes les autorités de contrôle concernées en sont informées et la période visée au paragraphe 2 est prolongée d'un mois.

Lorsque le CECAPP a été consulté, les autorités de contrôle concernées examinent dûment cet avis avant de prendre leur décision conjointe.

4.   L'autorité de contrôle ayant agréé la filiale notifie au demandeur la décision conjointe visée aux paragraphes 2 et 3, qui est dûment motivée et comporte, lorsque le CECAPP a été consulté, l'explication de toute divergence significative par rapport aux positions adoptées par le CECAPP. La décision conjointe est considérée comme déterminante et est appliquée par les autorités de contrôle concernées.

5.   À défaut de décision conjointe des autorités de contrôle concernées dans les délais prescrits aux paragraphes 2 et 3, le contrôleur du groupe se prononce lui-même sur la demande.

Lorsqu'il prend sa décision, le contrôleur du groupe tient dûment compte:

. a) de l'avis et des réserves exprimés par les autorités de contrôle concernées dans les délais impartis;

. b) des réserves exprimées par les autres autorités de contrôle au sein du collège des contrôleurs dans les délais impartis;

. c) lorsque le CECAPP a été consulté, de l'avis de ce comité.

La décision est dûment motivée et elle comporte une explication de toute divergence importante par rapport aux réserves exprimées par les autres autorités de contrôle concernées et à l'avis du CECAPP. Le contrôleur du groupe transmet une copie de la décision au demandeur et aux autres autorités de contrôle concernées.