= Article 242

Réexamen

1.   Au plus tard le 31 octobre 2014, la Commission procède à l'évaluation de l'application du titre III, notamment en ce qui concerne la coopération des autorités de contrôle au sein du collège des contrôleurs, et le bon fonctionnement de ce collège, le statut juridique du CECAPP et les pratiques de contrôle pour le recours aux exigences de capital supplémentaire, et elle présente au Parlement européen et au Conseil un rapport, accompagné, s'il y a lieu, de propositions de modification de la présente directive.

2.   Au plus tard le 31 octobre 2015, la Commission procède à l'évaluation des avantages d'un renforcement du contrôle de groupe et de la gestion du capital au sein d'un groupe d'entreprises d'assurance ou de réassurance, en se référant à sa communication COM(2008)0119, ainsi qu'au rapport du 16 octobre 2008 de la commission des affaires économiques et monétaires du Parlement européen sur cette proposition (A6-0413/2008). Cette évaluation inclut d'éventuelles mesures en vue de renforcer une bonne gestion transfrontalière des groupes d'assurance, notamment leur gestion des risques et des actifs. Dans le cadre de son évaluation, la Commission tient notamment compte des développements et avancées en ce qui concerne:

. a) un cadre harmonisé en matière d'intervention précoce;

. b) les pratiques centralisées de gestion des risques au niveau du groupe et le fonctionnement des modèles internes de groupe, y compris les simulations de crise;

. c) les transactions intragroupe et les concentrations de risques;

. d) l'évolution des comportements de diversification et des effets de concentration;

. e) un cadre juridiquement contraignant pour la médiation dans des conflits portant sur le contrôle;

. f) un cadre harmonisé des procédures de transfert d'actifs, d'insolvabilité et de liquidation qui lève dans le droit national sur les sociétés les obstacles au transfert d'actifs;

. g) un niveau équivalent de protection des preneurs et des bénéficiaires dans les entreprises d'un même groupe, notamment dans les situations de crise;

. h) une solution harmonisée et financée de manière adéquate à l'échelon de l'Union européenne pour les régimes de garantie des assurances;

. i) un cadre harmonisé et juridiquement contraignant, associant les autorités compétentes, les banques centrales et les ministères des finances à la gestion, à la résolution et au partage du poids budgétaire des crises, en alignant pouvoirs de contrôle et responsabilités budgétaires.

La Commission présente au Parlement européen et au Conseil un rapport, accompagné, s'il y a lieu, de propositions de modification de la présente directive.