== Article 240

=== Filiales d'une entreprise d'assurance ou de réassurance: fin des dérogations accordées aux filiales

1.   Les règles énoncées aux articles 238 et 239 cessent d'être applicables dans les cas suivants:

. a) la condition visée à l'article 236, point a), n'est plus respectée;

. b) la condition visée à l'article 236, point b), n'est plus respectée et le groupe ne rétablit pas le respect de cette condition dans un délai approprié;

. c) les conditions visées à l'article 236, points c) et d), ne sont plus respectées.

Dans le cas visé au premier alinéa, point a), lorsque le contrôleur du groupe décide, après avoir consulté le collège des contrôleurs, de ne plus inclure la filiale dans le contrôle du groupe qu'il effectue, il en informe immédiatement l'autorité de contrôle concernée et l'entreprise mère.

Aux fins de l'article 236, points b), c) et d), l'entreprise mère a la responsabilité de veiller à ce que les conditions soient respectées en permanence. Si ce n'est pas le cas, l'entreprise mère en informe sans délai le contrôleur du groupe et le contrôleur de la filiale concernée. L'entreprise mère présente un plan visant à rétablir le respect de la condition dans un délai approprié.

Sans préjudice du troisième alinéa, le contrôleur du groupe vérifie au moins une fois par an, de sa propre initiative, que les conditions visées à l'article 236, points b), c) et d), continuent d'être respectées. Le contrôleur du groupe procède également à cette vérification à la demande de l'autorité de contrôle concernée, lorsque cette dernière a de sérieux doutes concernant le respect permanent de ces conditions.

Lorsque la vérification fait apparaître des déficiences, le contrôleur du groupe impose à l'entreprise mère de présenter un plan visant à rétablir le respect de la condition dans un délai approprié.

Lorsque, après avoir consulté le collège des contrôleurs, le contrôleur du groupe estime que le plan visé au troisième ou au cinquième alinéa est insuffisant ou, ultérieurement, qu'il n'est pas mis en œuvre dans le délai convenu, il en conclut que les conditions visées à l'article 236, points b), c) et d), ne sont plus respectées et il en informe sans délai l'autorité de contrôle concernée.

2.   Le régime prévu par les articles 238 et 239 s'applique à nouveau lorsque l'entreprise mère présente une nouvelle demande et obtient une décision favorable conformément à la procédure prévue à l'article 237.