== Article 239

=== Filiales d'une entreprise d'assurance ou de réassurance: non-conformité au capital de solvabilité requis et au minimum de capital requis

1.   En cas de non-conformité au capital de solvabilité requis et sans préjudice de l'article 138, l'autorité de contrôle ayant agréé la filiale communique sans délai au collège des contrôleurs le programme de rétablissement soumis par la filiale en vue, dans un délai de six mois après la constatation de sa non-conformité au capital de solvabilité requis, de rétablir le niveau de fonds propres éligibles ou de réduire son profil de risque afin d'assurer sa conformité au capital de solvabilité requis.

Le collège des contrôleurs fait tout ce qui est en son pouvoir pour parvenir à un accord sur la proposition de l'autorité de contrôle quant à l'approbation du programme de rétablissement, dans un délai de quatre mois à compter du premier constat de non-conformité au capital de solvabilité requis.

À défaut d'un tel accord, l'autorité de contrôle ayant agréé la filiale décide si le programme de rétablissement devrait être approuvé, en tenant dûment compte de l'avis et des réserves exprimés par les autres autorités de contrôle au sein du collège des contrôleurs.

2.   Si l'autorité de contrôle ayant agréé la filiale détecte une dégradation des conditions financières, conformément à l'article 136, elle notifie sans délai au collège des contrôleurs les mesures qu'elle propose de prendre. Sauf dans des situations d'urgence, les mesures à prendre sont débattues au sein du collège des contrôleurs.

Le collège des contrôleurs fait tout ce qui est en son pouvoir pour parvenir, dans un délai d'un mois à compter de la notification, à un accord sur les mesures à prendre qui sont proposées.

À défaut d'un tel accord, l'autorité de contrôle ayant agréé la filiale décide si les mesures proposées devraient être approuvées, en tenant dûment compte de l'avis et des réserves exprimés par les autres autorités de contrôle au sein du collège des contrôleurs.

3.   En cas de non-conformité au minimum de capital requis et sans préjudice de l'article 139, l'autorité de contrôle ayant agréé la filiale communique sans délai au collège des contrôleurs le plan de financement à court terme soumis par la filiale en vue, dans un délai de trois mois après la première constatation de sa non-conformité au minimum de capital requis, de rétablir le niveau de fonds propres éligibles permettant d'atteindre le minimum de capital requis ou de réduire son profil de risque afin d'assurer sa conformité au minimum de capital requis. Le collège des contrôleurs est aussi tenu informé de toute mesure prise pour faire appliquer le minimum de capital requis au niveau de la filiale.