== Article 76

=== Dispositions générales

1.   Les États membres veillent à ce que les entreprises d'assurance et de réassurance établissent des provisions techniques pour tous leurs engagements d'assurance et de réassurance vis-à-vis des preneurs et des bénéficiaires des contrats d'assurance ou de réassurance.

2.   La valeur des provisions techniques correspond au montant actuel que les entreprises d'assurance et de réassurance devraient payer si elles transféraient sur le champ leurs engagements d'assurance et de réassurance à une autre entreprise d'assurance ou de réassurance.

3.   Le calcul des provisions techniques utilise, en étant cohérent avec elles, les informations fournies par les marchés financiers et les données généralement disponibles sur les risques de souscription (cohérence avec le marché).

4.   Les provisions techniques sont calculées d'une manière prudente, fiable et objective.

5.   Suivant les principes énoncés aux paragraphes 2, 3 et 4 et compte tenu de ceux énoncés à l'article 75, paragraphe 1, le calcul des provisions techniques est effectué conformément aux articles 77 à 82 et 86.