= Article 86

Mesures d'exécution

La Commission arrête des mesures d'exécution prévoyant ce qui suit:

. a) les méthodologies actuarielles et statistiques à utiliser pour calculer la meilleure estimation visée à l'article 77, paragraphe 2;

. b) la courbe des taux sans risque pertinents à utiliser pour calculer la meilleure estimation visée à l'article 77, paragraphe 2;

. c) les circonstances dans lesquelles les provisions techniques sont à calculer comme un tout ou comme la somme d'une meilleure estimation et d'une marge de risque, et les méthodes à utiliser lorsqu'elles sont calculées comme un tout;

. d) les méthodes et hypothèses à utiliser aux fins du calcul de la marge de risque, y compris la détermination du montant de fonds propres éligibles nécessaire pour faire face aux engagements d'assurance et de réassurance et le calibrage du taux du coût du capital;

. e) les lignes d'activité selon lesquelles les engagements d'assurance et de réassurance doivent être segmentées aux fins du calcul des provisions techniques;

. f) les normes à respecter en vue de garantir le caractère approprié, l'exhaustivité et l'exactitude des données utilisées dans le calcul des provisions techniques, et les circonstances particulières dans lesquelles il conviendrait d'user d'approximations, y compris par approches au cas par cas, pour le calcul de la meilleure estimation;

. g) les méthodologies à utiliser pour calculer l'ajustement pour défaut de la contrepartie, visé à l'article 81, visant à tenir compte des pertes probables pour défaut de la contrepartie;

. h) si nécessaire, les méthodes et techniques simplifiées à utiliser pour calculer les provisions techniques, afin de garantir que les méthodes actuarielles et statistiques visées aux points a) et d) sont proportionnées à la nature, à l'ampleur et à la complexité des risques supportés par les entreprises d'assurance et de réassurance, y compris les entreprises captives d'assurance et de réassurance.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

Section 3

Fonds propres

Sous-section 1

Détermination des fonds propres