== Article 75

=== Valorisation des actifs et des passifs

1.   Les États membres veillent à ce que, sauf indication contraire, les entreprises d'assurance et de réassurance valorisent leurs actifs et leurs passifs comme suit:

. a) les actifs sont valorisés au montant pour lequel ils pourraient être échangés dans le cadre d'une transaction conclue, dans des conditions de concurrence normales, entre des parties informées et consentantes;

. b) les passifs sont valorisés au montant pour lequel ils pourraient être transférés ou réglés dans le cadre d'une transaction conclue, dans des conditions de concurrence normales, entre des parties informées et consentantes.

Lors de la valorisation des passifs au titre du point b), aucun ajustement visant à tenir compte de la qualité de crédit propre à l'entreprise d'assurance ou de réassurance n'est effectué.

2.   La Commission arrête des mesures d'exécution exposant les méthodes et les hypothèses à utiliser lors de la valorisation des actifs et des passifs prévue au paragraphe 1.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

Section 2

Règles relatives aux provisions techniques