== Article 186

=== Délai de renonciation

1.   Les États membres prévoient que les preneurs d'un contrat d'assurance vie individuelle disposent d'un délai compris entre quatorze et trente jours, à compter du moment où ils sont informés que le contrat est conclu, pour renoncer aux effets de ce contrat.

La notification par les preneurs de leur renonciation au contrat a pour effet de les libérer pour l'avenir de toute obligation découlant de ce contrat.

Les autres effets juridiques et les conditions de la renonciation sont réglés par le droit applicable au contrat, notamment en ce qui concerne les modalités selon lesquelles le preneur est informé que le contrat est conclu.

2.   Les États membres peuvent ne pas appliquer le paragraphe 1 dans les cas suivants:

. a) lorsqu'un contrat a une durée égale ou inférieure à six mois;

. b) lorsque, en raison de la situation du preneur d'assurance ou des conditions dans lesquelles le contrat est conclu, le preneur n'a pas besoin de bénéficier d'une protection spéciale.

Lorsque les États membres font usage de l'option prévue au premier alinéa, ils l'indiquent dans leur législation.

CHAPITRE II

Dispositions propres à l'assurance non-vie

Section 1

Dispositions générales