== Article 185

=== Informations à l'attention des preneurs d'assurance

1.   Avant la conclusion du contrat d'assurance vie, sont communiquées au preneur d'assurance au moins les informations mentionnées aux paragraphes 2 à 4.

2.   Les informations suivantes concernant l'entreprise d'assurance vie sont communiquées:

. a) dénomination ou raison sociale et forme juridique de l'entreprise;

. b) nom de l'État membre où sont situés le siège social et, le cas échéant, la succursale avec laquelle le contrat sera conclu;

. c) adresse du siège social et, le cas échéant, de la succursale avec laquelle le contrat sera conclu;

. d) une référence concrète au rapport sur la solvabilité et la situation financière prévu à l'article 51, qui permet au preneur d'assurance d'accéder facilement à ces informations.

3.   Les informations suivantes concernant l'engagement sont communiquées:

. a) définition de chaque garantie et de chaque option;

. b) durée du contrat;

. c) modalités de résiliation du contrat;

. d) modalités de paiement des primes et durée des paiements;

. e) modalités de calcul et d'attribution des participations aux bénéfices;

. f) indications des valeurs de rachat et de réduction et nature des garanties y afférentes;

. g) informations sur les primes relatives à chaque garantie, qu'elle soit principale ou complémentaire, lorsque de telles informations se révèlent appropriées;

. h) énumération des valeurs de référence utilisées (unités de compte) dans les contrats à capital variable;

. i) indications sur la nature des actifs représentatifs des contrats à capital variable;

. j) modalités d'exercice du droit de renonciation;

. k) indications générales relatives au régime fiscal applicable au type de police;

. l) dispositions relatives au traitement des plaintes des preneurs d'assurance, assurés ou bénéficiaires, au sujet des contrats, y compris, le cas échéant, l'existence d'une instance chargée d'examiner les plaintes, sans préjudice de la possibilité d'intenter une action en justice;

. m) droit applicable au contrat lorsque les parties n'ont pas de liberté de choix ou, lorsque les parties ont la liberté de choisir le droit applicable, droit que l'entreprise d'assurance vie propose de choisir.

4.   En outre, des informations spécifiques sont fournies afin de permettre de bien percevoir les risques sous-jacents au contrat qui sont assumés par le preneur d'assurance.

5.   Le preneur d'assurance doit être tenu informé pendant toute la durée du contrat de toute modification concernant les informations suivantes:

. a) les conditions générales et particulières de la police;

. b) la dénomination ou la raison sociale de l'entreprise d'assurance vie, sa forme juridique ou l'adresse de son siège social et, le cas échéant, de sa succursale avec laquelle le contrat a été conclu;

. c) toutes informations énumérées au paragraphe 3, points d) à j), en cas de modification des conditions de la police ou du droit applicable au contrat;

. d) chaque année, des informations concernant la situation de la participation aux bénéfices.

Dans le cas où l'assureur, en rapport avec l'offre ou la conclusion d'un contrat d'assurance vie, indique des chiffres relatifs au montant de possibles versements en sus et au-delà des versements convenus par contrat, l'assureur fournit au preneur un exemple de calcul dans lequel le possible versement à échéance est exposé, en appliquant la base de calcul des primes, sur la base de trois taux d'intérêt différents. Ceci ne s'applique pas aux assurances et contrats à terme. L'assureur informe le preneur, de manière claire et compréhensible, que cet exemple de calcul n'est que l'application d'un modèle fondé sur de pures hypothèses et que le preneur ne tire de cet exemple de calcul aucun droit contractuel.

Dans le cas d'assurances avec participation aux bénéfices, l'assureur informe le preneur, annuellement et par écrit, de la situation des droits du preneur, en incluant la participation aux bénéfices. En outre, lorsqu'il a indiqué des chiffres sur la possible évolution future de la participation aux bénéfices, l'assureur informe le preneur des différences entre l'évolution constatée et les données initiales.

6.   Les informations visées aux paragraphes 2 à 5 doivent être formulées de manière claire et précise, par écrit, et être fournies dans une langue officielle de l'État membre de l'engagement.

Toutefois, ces informations peuvent être rédigées dans une autre langue si le preneur le demande et le droit de l'État membre le permet ou si le preneur a la liberté de choisir le droit applicable.

7.   L'État membre de l'engagement ne peut exiger des entreprises d'assurance vie la fourniture d'informations supplémentaires par rapport à celles énumérées aux paragraphes 2 à 5 que si ces informations sont nécessaires à la compréhension effective par le preneur des éléments essentiels de l'engagement.

8.   Les modalités de mise en œuvre des paragraphes 1 à 7 sont arrêtées par l'État membre de l'engagement.