= Article 31

Transparence et obligation de rendre des comptes

1.   Les autorités de contrôle exercent leurs fonctions d'une manière transparente et en rendant compte de leur action, tout en veillant dûment à la protection des informations confidentielles.

2.   Les États membres veillent à ce que les informations suivantes soient publiées:

. a) le texte des dispositions législatives, réglementaires et administratives ainsi que le texte des orientations générales appliquées en matière de réglementation de l'assurance;

. b) les critères généraux et méthodes, y compris les outils développés conformément à l'article 34, paragraphe 4, utilisés dans le cadre du processus de contrôle prudentiel prévu à l'article 36;

. c) des données statistiques agrégées sur les principaux aspects de l'application du cadre prudentiel;

. d) la manière dont ont été exercées les options prévues dans la présente directive;

. e) les objectifs du contrôle et les principales fonctions et activités exercées à ce titre.

La publication effectuée conformément au premier alinéa doit être suffisante afin de pouvoir comparer les approches du contrôle respectivement adoptées par les autorités de contrôle des différents États membres.

Les informations sont publiées sous un format commun et elles sont régulièrement actualisées. Les informations visées au premier alinéa, points a) à e), sont disponibles à une adresse électronique unique dans chaque État membre.

3.   Les États membres prévoient des procédures transparentes pour la nomination et le licenciement des membres des organes de direction et de gestion de leurs autorités de contrôle.

4.   La Commission arrête des mesures d'exécution concernant le paragraphe 2, qui précisent les principaux éléments au sujet desquels des données statistiques agrégées doivent être publiées, ainsi que le format, la structure, le contenu et la date des publications.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.