= Article 30

Autorités de contrôle et champ d'application du contrôle

1.   Le contrôle financier des entreprises d'assurance et de réassurance, y compris celui des activités qu'elles exercent par le moyen de succursales ou en libre prestation de services, relève de la compétence exclusive de l'État membre d'origine.

2.   Le contrôle financier prévu au paragraphe 1 inclut la vérification, pour l'ensemble des activités de l'entreprise d'assurance ou de réassurance, de sa solvabilité, de ses provisions techniques, de ses actifs et de ses fonds propres éligibles, conformément aux règles établies ou aux pratiques suivies dans l'État membre d'origine, en vertu des dispositions adoptées au niveau communautaire

Dans le cas où les entreprises d'assurance concernées sont agréées pour couvrir les risques classés dans la branche 18 de la partie A de l'annexe I, le contrôle s'étend aussi aux moyens techniques dont les entreprises d'assurance disposent pour mener à bien les opérations d'assistance qu'elles se sont engagées à effectuer, dans la mesure où la législation de l'État membre d'origine prévoit un contrôle de ces moyens.

3.   Si les autorités de contrôle de l'État membre où le risque est situé ou de l'État membre de l'engagement, ou bien, s'il s'agit d'une entreprise de réassurance, celles de l'État membre d'accueil, ont des raisons de considérer que les activités d'une entreprise d'assurance ou de réassurance pourraient porter atteinte à sa solidité financière, elles en informent les autorités de contrôle de l'État membre d'origine de ladite entreprise.

Les autorités de contrôle de l'État membre d'origine vérifient que l'entreprise respecte les principes prudentiels définis dans la présente directive.