= Article 29

Principes généraux du contrôle

1.   Le contrôle repose sur une approche prospective et fondée sur les risques. Il inclut la vérification continue du bon fonctionnement de l'activité d'assurance ou de réassurance, ainsi que du respect, par les entreprises d'assurance et de réassurance, des dispositions applicables en matière de contrôle.

2.   Le contrôle des entreprises d'assurance et de réassurance combine de manière appropriée les examens sur pièces et les inspections sur place.

3.   Les États membres veillent à ce que les exigences énoncées dans la présente directive soient appliquées de façon proportionnée eu égard à la nature, à l'ampleur et à la complexité des risques inhérents à l'activité d'une entreprise d'assurance ou de réassurance.

4.   La Commission veille à ce que les mesures d'exécution prennent en compte le principe de proportionnalité, garantissant ainsi l'application proportionnée de la présente directive, en particulier pour les petites entreprises d'assurance.