= Article 36

Processus de contrôle prudentiel

1.   Les États membres veillent à ce que les autorités de contrôle examinent et évaluent les stratégies, les processus et les procédures de communication d'informations établis par les entreprises d'assurance et de réassurance en vue de se conformer aux dispositions législatives, réglementaires et administratives adoptées en vertu de la présente directive.

Cet examen et cette évaluation comprennent l'appréciation des exigences qualitatives relatives au système de gouvernance, l'appréciation des risques auxquels les entreprises concernées sont exposées ou pourraient être exposées et l'appréciation de leur capacité à mesurer ces risques compte tenu de l'environnement dans lequel elles opèrent.

2.   En particulier, les autorités de contrôle examinent et évaluent s'il est satisfait:

. a) aux exigences concernant le système de gouvernance prévues au chapitre IV, section 2, notamment l'évaluation interne des risques et de la solvabilité;

. b) aux exigences concernant les provisions techniques prévues au chapitre VI, section 2;

. c) aux exigences de capital prévues au chapitre VI, sections 4 et 5;

. d) aux règles d'investissement prévues au chapitre VI, section 6;

. e) aux exigences concernant la quantité et la qualité des fonds propres prévues au chapitre VI, section 3;

. f) lorsque l'entreprise d'assurance ou de réassurance utilise un modèle interne intégral ou partiel, aux exigences applicables aux modèles internes intégraux et partiels prévues au chapitre VI, section 4, sous-section 3, qui doivent être respectées en permanence.

3.   Les autorités de contrôle disposent d'outils de suivi appropriés, qui leur permettent de détecter toute détérioration de la situation financière d'une entreprise d'assurance ou de réassurance et de vérifier de quelle manière il y est porté remède.

4.   Les autorités de contrôle évaluent l'adéquation des méthodes et pratiques appliquées par les entreprises d'assurance et de réassurance en vue de détecter les éventuels aléas ou changements de la conjoncture économique qui pourraient avoir un impact défavorable sur la situation financière globale de l'entreprise concernée.

Les autorités de contrôle évaluent la capacité desdites entreprises à surmonter ces éventuels aléas ou changements de la conjoncture économique.

5.   Les autorités de contrôle disposent des pouvoirs nécessaires pour exiger des entreprises d'assurance et de réassurance qu'elles remédient aux faiblesses et carences détectées dans le cadre du processus de contrôle prudentiel.

6.   Il est procédé régulièrement aux examens, évaluations et appréciations visés aux paragraphes 1, 2 et 4.

Les autorités de contrôle définissent la fréquence minimale et la portée desdits examens, évaluations et appréciations, en tenant compte de la nature, de l'ampleur et de la complexité des activités des entreprises d'assurance ou de réassurance concernées.