= Article 38

Suivi des activités et des fonctions données en sous-traitance

1.   Sans préjudice de l'article 49, les États membres veillent à ce que les entreprises d'assurance et de réassurance qui donnent une fonction ou une activité d'assurance ou de réassurance en sous-traitance prennent les mesures nécessaires pour faire en sorte de réunir les conditions suivantes:

. a) le prestataire de services doit coopérer avec les autorités de contrôle de l'entreprise d'assurance ou de réassurance, pour ce qui concerne la fonction ou l'activité donnée en sous-traitance;

. b) l'entreprise d'assurance ou de réassurance, les personnes chargées du contrôle de ses comptes et les autorités de contrôle doivent avoir effectivement accès aux données afférentes aux fonctions ou aux activités données en sous-traitance;

. c) les autorités de contrôle doivent avoir effectivement accès aux locaux du prestataire de services et doivent pouvoir exercer ce droit d'accès.

2.   L'État membre dans lequel le prestataire de services est situé permet aux autorités de contrôle de l'entreprise d'assurance ou de réassurance de procéder elles-mêmes, ou par l'intermédiaire de personnes qu'elles mandatent à cet effet, à des inspections sur place dans les locaux du prestataire de services. L'autorité de contrôle de l'entreprise d'assurance ou de réassurance informe l'autorité compétente de l'État membre du prestataire de service avant de procéder à l'inspection sur place. Dans le cas d'une entité non soumise à contrôle, l'autorité adéquate est l'autorité de contrôle.

Les autorités de contrôle de l'État membre de l'entreprise d'assurance ou de réassurance peuvent déléguer ces inspections sur place aux autorités de contrôle de l'État membre dans lequel le prestataire de services est situé.