== Article 34

=== Pouvoirs généraux de contrôle

1.   Les États membres veillent à ce que les autorités de contrôle aient le pouvoir de prendre des mesures préventives et correctives en vue de garantir le respect, par les entreprises d'assurance et de réassurance, des dispositions législatives, réglementaires et administratives auxquelles ces entreprises sont tenues de se conformer dans chaque État membre.

2.   Les autorités de contrôle ont le pouvoir de prendre toutes mesures nécessaires, y compris, s'il y a lieu, des mesures de nature administrative ou financière, à l'égard des entreprises d'assurance ou de réassurance et des membres de leur organe d'administration, de gestion ou de contrôle.

3.   Les États membres veillent à ce que les autorités de contrôle aient le pouvoir d'exiger toute information nécessaire à l'exercice du contrôle conformément à l'article 35.

4.   Les États membres veillent à ce que les autorités de contrôle aient le pouvoir de mettre en place, indépendamment du calcul du capital de solvabilité requis et, s'il y a lieu, les outils quantitatifs nécessaires dans le cadre du processus de contrôle prudentiel pour apprécier la capacité des entreprises d'assurance ou de réassurance à faire face à d'éventuels aléas ou changements de la conjoncture économique qui pourraient avoir un impact défavorable sur leur situation financière globale. Les autorités de contrôle ont le pouvoir d'exiger que les tests correspondants soient réalisés par les entreprises.

5.   Les autorités de contrôle ont le pouvoir de procéder à des investigations sur place dans les locaux des entreprises d'assurance et de réassurance.

6.   Les pouvoirs de contrôle sont exercés en temps utile et d'une manière proportionnée.

7.   Les pouvoirs visés aux paragraphes 1 à 5, accordés à l'égard des entreprises d'assurance et de réassurance, s'appliquent également à l'égard des activités données par celles-ci en sous-traitance.

8.   Les pouvoirs visés aux paragraphes 1 à 5 et 7 sont exercés, au besoin, de manière coercitive et, s'il y a lieu, moyennant le recours aux instances judiciaires.