= Article 39

Transfert de portefeuille

1.   Dans les conditions prévues par le droit national, les États membres autorisent les entreprises d'assurance et de réassurance dont le siège social est situé sur leur territoire à transférer tout ou partie de leur portefeuille de contrats, qu'il ait été souscrit en vertu du droit d'établissement ou de la libre prestation de services, à une entreprise cessionnaire établie dans la Communauté.

Un tel transfert n'est autorisé que si les autorités de contrôle de l'État membre d'origine de l'entreprise cessionnaire attestent que celle-ci possède, compte tenu du transfert, les fonds propres éligibles nécessaires pour couvrir le capital de solvabilité requis visé à l'article 100, premier alinéa.

2.   Dans le cas des entreprises d'assurance, les paragraphes 3 à 6 s'appliquent.

3.   Lorsqu'une succursale envisage de transférer tout ou partie de son portefeuille de contrats, l'État membre dans lequel cette succursale est située est consulté.

4.   Dans les cas visés aux paragraphes 1 et 3, les autorités de contrôle de l'État membre d'origine de l'entreprise d'assurance cédante autorisent le transfert après avoir reçu l'accord des autorités des États membres dans lesquels les contrats ont été souscrits, soit en vertu du droit d'établissement, soit en vertu de la libre prestation de services.

5.   Les autorités des États membres consultés font connaître leur avis ou leur accord aux autorités de l'État membre d'origine de l'entreprise d'assurance cédante dans les trois mois suivant la réception de la demande de consultation.

En cas de silence des autorités consultées à l'expiration de ce délai, ce silence est assimilé à un accord tacite.

6.   Un transfert de portefeuille autorisé conformément aux paragraphes 1 à 5 fait l'objet d'une mesure de publicité dans les conditions prévues par le droit national de l'État membre d'origine, de l'État membre où le risque est situé ou de l'État membre de l'engagement, soit avant, soit après l'obtention de l'autorisation.

Ce transfert est opposable de plein droit aux preneurs d'assurance, aux assurés, ainsi qu'à toute autre personne ayant des droits ou des obligations découlant des contrats transférés.

Les premier et second alinéas du présent paragraphe n'affectent pas le droit des États membres de prévoir la faculté pour les preneurs d'assurance de résilier le contrat dans un délai déterminé à partir du transfert.

CHAPITRE IV

Conditions régissant l'activité

Section 1

Responsabilité de l'organe d'administration, de gestion ou de controle