== Article 35

=== Informations à fournir aux fins du contrôle

1.   Les États membres exigent des entreprises d'assurance et de réassurance qu'elles fournissent aux autorités de contrôle les informations nécessaires aux fins du contrôle. Celles-ci comprennent au minimum les informations nécessaires à l'exécution des tâches suivantes, dans le cadre de la mise en œuvre du processus visé à l'article 36:

. a) évaluer le système de gouvernance appliqué par les entreprises, leurs activités, les principes d'évaluation qu'elles appliquent à des fins de solvabilité, les risques auxquels elles sont exposées et leurs systèmes de gestion des risques, la structure de leur capital, leurs besoins en capital et la gestion de leur capital;

. b) prendre toute décision appropriée qu'appelle l'exercice de leurs droits et fonctions en matière de contrôle.

2.   Les États membres veillent à ce que les autorités de contrôle soient dotées des pouvoirs suivants:

. a) définir la nature, la portée et le format des informations visées au paragraphe 1, dont elles exigent communication de la part des entreprises d'assurance et de réassurance aux moments suivants:i)à des moments prédéfinis;ii)lorsque des événements prédéfinis se produisent;iii)lors d'enquêtes concernant la situation d'une entreprise d'assurance ou de réassurance;

. i) à des moments prédéfinis;

. ii) lorsque des événements prédéfinis se produisent;

. iii) lors d'enquêtes concernant la situation d'une entreprise d'assurance ou de réassurance;

. b) obtenir toute information relative aux contrats détenus par des intermédiaires ou aux contrats conclus avec des tiers; et

. c) exiger des informations de la part d'experts extérieurs, tels que des contrôleurs des comptes et des actuaires.

3.   Les informations visées aux paragraphes 1 et 2 comprennent ce qui suit:

. a) des éléments qualitatifs ou quantitatifs, ou toute combinaison appropriée de ces éléments;

. b) des éléments historiques, actuels ou prospectifs, ou toute combinaison appropriée de ces éléments; et

. c) des données provenant de sources internes ou externes, ou toute combinaison appropriée de ces données.

4.   Les informations visées aux paragraphes 1 et 2 sont conformes aux principes suivants:

. a) elles reflètent la nature, l'ampleur et la complexité des activités de l'entreprise concernée, et notamment les risques inhérents à cette activité;

. b) elles sont accessibles, complètes pour tout ce qui est important, comparables et cohérentes dans la durée; et

. c) elles sont pertinentes, fiables et compréhensibles.

5.   Les États membres exigent des entreprises d'assurance et de réassurance qu'elles mettent en place des structures et systèmes appropriés pour satisfaire aux exigences des paragraphes 1 à 4, ainsi qu'une politique écrite, approuvée par l'organe d'administration, de gestion ou de contrôle de l'entreprise d'assurance ou de réassurance, qui garantisse l'adéquation permanente des informations communiquées.

6.   La Commission arrête des mesures d'exécution précisant les informations visées aux paragraphes 1 à 4, en vue de garantir, dans une mesure appropriée, la convergence des informations communiquées en vue du contrôle.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec à la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.