== Article 268

=== Définitions

1.   Aux fins du présent titre, on entend par:

. a) «autorités compétentes»: les autorités administratives ou judiciaires des États membres compétentes pour les mesures d'assainissement ou les procédures de liquidation;

. b) «succursale»: la présence permanente d'une entreprise d'assurance sur le territoire d'un État membre autre que l'État membre d'origine, qui exerce une activité d'assurance;

. c) «mesures d'assainissement»: les mesures comportant une intervention des autorités compétentes, qui sont destinées à préserver ou à rétablir la situation financière d'une entreprise d'assurance et qui affectent les droits préexistants de parties autres que l'entreprise d'assurance elle-même, y compris, mais pas uniquement, les mesures qui comportent la possibilité d'une suspension des paiements, d'une suspension des mesures d'exécution ou d'une réduction des créances;

. d) «procédure de liquidation»: une procédure collective entraînant la réalisation des actifs d'une entreprise d'assurance et la répartition du produit entre les créanciers, les actionnaires ou les associés, selon le cas, qui implique nécessairement une intervention des autorités compétentes, y compris lorsque cette procédure collective est clôturée par un concordat ou une autre mesure analogue, que la procédure soit ou non fondée sur l'insolvabilité et qu'elle soit volontaire ou obligatoire;

. e) «administrateur»: une personne ou un organe nommé par les autorités compétentes aux fins de mettre en œuvre des mesures d'assainissement;

. f) «liquidateur»: une personne ou un organe nommé par les autorités compétentes ou par les organes statutaires d'une entreprise d'assurance aux fins de mettre en œuvre une procédure de liquidation;

. g) «créance d'assurance»: le montant qui est dû par une entreprise d'assurance à des assurés, des preneurs d'assurance, des bénéficiaires ou à toute victime disposant d'un droit d'action direct à l'encontre de l'entreprise d'assurance et qui résulte d'un contrat d'assurance ou de toute opération visée à l'article 2, paragraphe 3, points b) et c), dans l'activité d'assurance directe, y compris le montant mis en réserve pour ces personnes lorsque certains éléments de la dette ne sont pas encore connus.

La prime due par une entreprise d'assurance du fait de la non-conclusion ou de la résiliation, avant l'ouverture de la procédure de liquidation, d'un contrat d'assurance ou d'une opération visés au premier alinéa, point g), conformément au droit applicable à ce contrat ou à cette opération est aussi considérée comme une créance d'assurance.

2.   Aux fins de l'application du présent titre aux mesures d'assainissement et aux procédures de liquidation concernant une succursale, située dans un État membre, d'une entreprise d'assurance d'un pays tiers, on entend par:

. a) «État membre d'origine»: l'État membre dans lequel la succursale a reçu un agrément conformément aux articles 145 à 149;

. b) «autorités de contrôle»: les autorités de contrôle de l'État membre d'origine;

. c) «autorités compétentes»: les autorités compétentes de l'État membre d'origine.

CHAPITRE II

Mesures d'assainissement