== Article 183

=== Informations générales à l'attention des preneurs d'assurance

1.   Avant la conclusion du contrat d'assurance non-vie, le preneur doit être informé par l'entreprise d'assurance non-vie:

. a) du droit applicable au contrat, lorsque les parties n'ont pas de liberté de choix;

. b) du fait que les parties ont la liberté de choisir le droit applicable et du droit que l'assureur propose de choisir.

L'entreprise d'assurance informe également le preneur d'assurance des dispositions relatives au traitement des plaintes des preneurs d'assurance au sujet des contrats, y compris, le cas échéant, de l'existence d'une instance chargée d'examiner les plaintes, sans préjudice de la possibilité pour le preneur d'assurance d'intenter une action en justice.

2.   Les obligations visées au paragraphe 1 ne s'appliquent que lorsque le preneur d'assurance est une personne physique.

3.   Les modalités de mise en œuvre des paragraphes 1 et 2 sont établies par l'État membre où le risque est situé.