= Article 184

Information supplémentaire à fournir pour une assurance non-vie proposée en vertu du droit d'établissement ou de la libre prestation de services

1.   Lorsqu'une assurance non-vie est proposée en vertu du droit d'établissement ou de la libre prestation de services, le preneur d'assurance doit être informé, avant la conclusion de tout engagement, du nom de l'État membre où est situé le siège social ou, le cas échéant, la succursale avec lequel ou laquelle le contrat sera conclu.

Tous les documents fournis au preneur d'assurance comportent l'information visée au premier alinéa.

Les obligations énoncées aux premier et deuxième alinéas ne concernent pas les grands risques.

2.   Le contrat ou tout autre document accordant la couverture ainsi que la proposition d'assurance dans le cas où elle lie le preneur indiquent l'adresse du siège social ou, le cas échéant, de la succursale de l'entreprise d'assurance non-vie qui accorde la couverture.

Les États membres peuvent exiger que le nom et l'adresse du représentant de l'entreprise d'assurance non-vie visé à l'article 148, paragraphe 2, point a), figurent également dans les documents visés au premier alinéa du présent paragraphe.

Sous-section 2

Assurance vie