== Article 146

=== Communication des informations

1.   À moins que les autorités de contrôle de l'État membre d'origine n'aient des raisons de douter, compte tenu de l'activité envisagée, de l'adéquation du système de gouvernance, de la situation financière de l'entreprise d'assurance ou de l'honorabilité ou de la compétence du mandataire général exigées conformément à l'article 42, elles communiquent les informations visées à l'article 145, paragraphe 2, dans les trois mois à compter de la réception de toutes ces informations, aux autorités de contrôle de l'État membre d'accueil et en avisent l'entreprise d'assurance concernée.

Les autorités de contrôle de l'État membre d'origine attestent également que l'entreprise d'assurance dispose du capital de solvabilité requis et du minimum de capital requis calculés conformément aux articles 100 et 129.

2.   Lorsque les autorités de contrôle de l'État membre d'origine refusent de communiquer les informations visées à l'article 145, paragraphe 2, aux autorités de contrôle de l'État membre d'accueil, elles font connaître les motifs de ce refus à l'entreprise d'assurance concernée dans les trois mois suivant la réception de toutes les informations concernées.

Ce refus ou l'absence de réaction peuvent faire l'objet d'un recours juridictionnel dans l'État membre d'origine.

3.   Avant que la succursale de l'entreprise d'assurance ne commence à exercer ses activités, les autorités de contrôle de l'État membre d'accueil disposent, le cas échéant, de deux mois à compter de la réception des informations visées au paragraphe 1 pour indiquer aux autorités de contrôle de l'État membre d'origine les conditions dans lesquelles, pour des raisons d'intérêt général, ces activités doivent être exercées dans l'État membre d'accueil. Les autorités de contrôle de l'État membre d'origine communiquent ces informations à l'entreprise d'assurance concernée.

L'entreprise d'assurance peut établir sa succursale et commencer ses activités à partir de la date à laquelle l'autorité de contrôle de l'État membre d'origine a reçu cette communication ou, en l'absence de toute communication, dès l'échéance du délai prévu au premier alinéa.

Section 2

Libre prestation de services: entreprises d'assurance

Sous-section 1

Dispositions générales