== Article 145

=== Conditions d'établissement d'une succursale

1.   Les États membres veillent à ce qu'une entreprise d'assurance qui désire établir une succursale sur le territoire d'un autre État membre le notifie aux autorités de contrôle de son État membre d'origine.

Est assimilée à une succursale toute présence permanente d'une entreprise sur le territoire d'un État membre, même lorsque cette présence n'a pas pris la forme d'une succursale mais s'exerce par le moyen d'un simple bureau géré par le propre personnel de l'entreprise, ou par une personne indépendante mais mandatée pour agir en permanence pour l'entreprise comme le ferait une agence.

2.   Les États membres exigent que toute entreprise d'assurance qui désire établir une succursale sur le territoire d'un autre État membre communique les informations suivantes lorsqu'elle effectue la notification prévue au paragraphe 1:

. a) le nom de l'État membre sur le territoire duquel elle envisage d'établir la succursale;

. b) son programme d'activités, dans lequel sont indiqués au moins le type d'opérations envisagées et la structure de l'organisation de la succursale;

. c) le nom d'une personne dotée des pouvoirs suffisants pour engager à l'égard des tiers l'entreprise d'assurance ou, dans le cas du Lloyd's, les souscripteurs intéressés, et pour la ou les représenter dans les relations avec les autorités et les juridictions de l'État membre d'accueil (ci-après dénommée «mandataire général»);

. d) l'adresse à laquelle les documents peuvent lui être réclamés et délivrés dans l'État membre d'accueil, notamment les communications au mandataire général.

En ce qui concerne le Lloyd's, en cas de litiges éventuels dans l'État membre d'accueil découlant d'engagements souscrits, les assurés ne peuvent être traités de manière moins favorable que si le litige mettait en cause des entreprises de type classique.

3.   Dans le cas où une entreprise d'assurance non-vie entend faire couvrir par sa succursale les risques classés dans la branche 10 de la partie A de l'annexe I, à l'exclusion de la responsabilité du transporteur, elle doit produire une déclaration selon laquelle elle est devenue membre du bureau national et du fonds national de garantie de l'État membre d'accueil.

4.   En cas de modification du contenu de l'une des informations notifiées conformément au paragraphe 2, point b), c) ou d), l'entreprise d'assurance notifie par écrit cette modification aux autorités de contrôle de l'État membre d'origine et de l'État membre où se situe cette succursale un mois au moins avant d'effectuer le changement, pour que les autorités de contrôle de l'État membre d'origine et celles de l'État membre où se situe cette succursale puissent remplir leurs obligations respectives aux termes de l'article 146.