== Article 150

=== Assurance obligatoire de la responsabilité civile résultant de la circulation des véhicules automoteurs

1.   Lorsqu'une entreprise d'assurance non-vie, par l'intermédiaire d'un établissement situé dans un État membre, couvre un risque classé dans la branche 10 de la partie A de l'annexe I, à l'exclusion de la responsabilité du transporteur, et situé dans un autre État membre, l'État membre d'accueil exige que cette entreprise devienne membre de son bureau national et de son fonds national de garantie et participe à leur financement.

2.   La contribution financière visée au paragraphe 1 n'est versée que pour des risques classés dans la branche 10 de la partie A de l'annexe I, à l'exclusion de la responsabilité du transporteur, couverts en régime de prestation de services. Elle est calculée sur la même base que pour les entreprises d'assurance non-vie couvrant ces risques par l'intermédiaire d'un établissement situé dans cet État membre.

Le calcul est fonction des recettes des primes des entreprises d'assurance provenant de cette branche dans l'État membre d'accueil ou du nombre de risques de cette branche couverts dans ledit État membre.

3.   L'État membre d'accueil peut exiger d'une entreprise d'assurance offrant des services qu'elle respecte les règles de cet État membre en matière de couverture de risques aggravés, dans la mesure où elles s'appliquent aux entreprises d'assurance non-vie établies dans cet État.