= Article 152

Représentation

1.   Aux fins visées à l'article 151, l'État membre d'accueil exige de l'entreprise d'assurance non-vie qu'elle désigne un représentant résidant ou établi sur son territoire qui réunit toutes les informations nécessaires en relation avec les dossiers d'indemnisation et dispose de pouvoirs suffisants pour représenter l'entreprise auprès des personnes qui ont subi un préjudice et qui pourraient réclamer une indemnisation, y compris le paiement de celle-ci, et pour la représenter ou, si cela est nécessaire, pour la faire représenter, en ce qui concerne ces demandes d'indemnisation, devant les juridictions et les autorités de cet État membre.

Ce représentant peut aussi être appelé à représenter l'entreprise d'assurance non-vie devant les autorités de contrôle de l'État membre d'accueil, pour ce qui est du contrôle de l'existence et de la validité des polices d'assurance de la responsabilité civile résultant de la circulation des véhicules automoteurs.

2.   L'État membre d'accueil ne peut exiger du représentant qu'il entreprenne, pour le compte de l'entreprise d'assurance non-vie qui l'a désigné, des activités autres que celles décrites au paragraphe 1.

3.   La désignation du représentant ne constitue pas en soi l'ouverture d'une succursale aux fins de l'article 145.

4.   Lorsque l'entreprise d'assurance a omis de désigner un représentant, les États membres peuvent donner leur accord à ce que le représentant chargé du règlement des sinistres désigné conformément à l'article 4 de la directive 2000/26/CE assume le rôle du représentant visé au paragraphe 1 du présent article.

Section 3

Compétences des autorités de contrôle de l'État membre d'accueil

Sous-section 1

Assurance