== Article 104

=== Conception du capital de solvabilité requis de base

1.   Le capital de solvabilité requis de base se compose de modules de risque individuels qui sont agrégés conformément au point 1 de l'annexe IV.

Il comprend au moins les modules de risque suivants:

. a) le risque de souscription en non-vie;

. b) le risque de souscription en vie;

. c) le risque de souscription en santé;

. d) le risque de marché;

. e) le risque de contrepartie.

2.   Aux fins du paragraphe 1, points a), b) et c), les opérations d'assurance et de réassurance sont affectées au module de risque de souscription qui reflète le mieux la nature technique des risques sous-jacents.

3.   Les coefficients de corrélation appliqués aux fins de l'agrégation des modules de risque visés au paragraphe 1 ainsi que le calibrage des exigences de capital pour chaque module de risque aboutissent à un capital de solvabilité requis global satisfaisant aux principes énoncés à l'article 101.

4.   Chacun des modules de risque visés au paragraphe 1 est calibré sur la base d'une mesure de la valeur en risque (Value-at-Risk), avec un niveau de confiance de 99,5 % à l'horizon d'un an.

S'il y a lieu, il est tenu compte des effets de diversification dans la conception de chaque module de risque.

5.   Pour toutes les entreprises d'assurance et de réassurance, la même conception et les mêmes spécifications sont utilisées pour les modules de risque, tant pour le capital de solvabilité requis de base que pour tout calcul simplifié prévu à l'article 109.

6.   En ce qui concerne les risques résultant de catastrophes, des spécifications géographiques peuvent, s'il y a lieu, être utilisées aux fins du calcul des modules «risque de souscription en vie», «risque de souscription en non-vie» et «risque de souscription en santé».

7.   Sous réserve de l'accord des autorités de contrôle, les entreprises d'assurance et de réassurance peuvent, lorsqu'elles calculent les modules «risque de souscription en vie», «risque de souscription en non-vie» et «risque de souscription en santé», remplacer, dans la conception de la formule standard, un sous-ensemble de ses paramètres par des paramètres qui sont propres à l'entreprise concernée.

Ces paramètres sont calibrés sur la base des données internes de l'entreprise concernée ou de données directement pertinentes pour les opérations de cette entreprise, sur la base de méthodes standardisées.

Avant de donner leur accord, les autorités de contrôle vérifient l'exhaustivité, l'exactitude et le caractère approprié des données utilisées.