= Article 107

Exigence de capital pour risque opérationnel

1.   L'exigence de capital pour risque opérationnel reflète les risques opérationnels, dans la mesure où ceux-ci ne sont pas déjà pris en considération dans les modules de risque visés à l'article 104. Cette exigence est calibrée conformément à l'article 101, paragraphe 3.

2.   Dans le cas des contrats d'assurance vie où le risque d'investissement est supporté par le preneur, le calcul de l'exigence de capital pour risque opérationnel tient compte du montant des dépenses annuelles encourues aux fins de ces engagements d'assurance.

3.   Dans le cas des opérations d'assurance et de réassurance autres que celles visées au paragraphe 2, le calcul de l'exigence de capital pour risque opérationnel tient compte du volume de ces opérations, en termes d'encaissement de primes et de provisions techniques détenues pour faire face aux engagements d'assurance et de réassurance correspondants. L'exigence de capital pour risque opérationnel ne dépasse alors pas 30 % du capital de solvabilité requis de base afférent aux opérations d'assurance et de réassurance concernées.