= Article 9

Opérations et activités

En ce qui concerne l'assurance vie, la présente directive ne s'applique pas aux opérations et activités suivantes:

. 1) les opérations des organismes de prévoyance et de secours qui accordent des prestations variables selon les ressources disponibles et exigent de chacun de leurs adhérents une contribution forfaitaire appropriée;

. 2) les opérations effectuées par des organisations, autres que les entreprises visées à l'article 2, qui ont pour objet de fournir aux travailleurs, salariés ou non, groupés dans le cadre d'une entreprise ou d'un groupement d'entreprises ou d'un secteur professionnel ou interprofessionnel, des prestations en cas de décès, en cas de vie ou en cas de cessation ou de réduction d'activités, que les engagements résultant de ces opérations soient ou non couverts intégralement et à tout moment par des provisions mathématiques;

. 3) les activités exercées dans le domaine des pensions par les entreprises d'assurance pension visées par la loi relative aux pensions des salariés (TyEL) et les autres actes législatifs finlandais en la matière, pour autant:a)que les entreprises d'assurance pension qui, en vertu de la loi finlandaise, sont déjà tenues d'avoir des systèmes de compatibilité et de gestion séparés pour leurs activités dans le domaine des pensions aient mis en place, à compter du 1erjanvier 1995, des entités juridiques distinctes pour exercer ces activités; etb)que les autorités finlandaises autorisent sans discrimination tous les ressortissants et toutes les sociétés des États membres à exercer, conformément à la législation finlandaise, les activités visées à l'article 2 relatives à la présente exemption soit en détenant une entreprise ou un groupe d'assurance existant ou en y prenant une participation, soit en créant de nouvelles entreprises ou de nouveaux groupes d'assurance, y compris les entreprises d'assurance pension, ou en y prenant une participation.

. a) que les entreprises d'assurance pension qui, en vertu de la loi finlandaise, sont déjà tenues d'avoir des systèmes de compatibilité et de gestion séparés pour leurs activités dans le domaine des pensions aient mis en place, à compter du 1erjanvier 1995, des entités juridiques distinctes pour exercer ces activités; et

. b) que les autorités finlandaises autorisent sans discrimination tous les ressortissants et toutes les sociétés des États membres à exercer, conformément à la législation finlandaise, les activités visées à l'article 2 relatives à la présente exemption soit en détenant une entreprise ou un groupe d'assurance existant ou en y prenant une participation, soit en créant de nouvelles entreprises ou de nouveaux groupes d'assurance, y compris les entreprises d'assurance pension, ou en y prenant une participation.