== Article 206

=== Assurance maladie remplaçant la sécurité sociale

1.   Tout État membre dans lequel les contrats relatifs à la branche 2 de la partie A de l'annexe I peuvent se substituer partiellement ou entièrement à la couverture «maladie» fournie par le régime légal de sécurité sociale peut exiger:

. a) que ces contrats soient conformes aux dispositions légales spécifiques arrêtées par cet État membre pour protéger l'intérêt général dans cette branche d'assurance;

. b) que les conditions générales et particulières de cette assurance soient communiquées aux autorités de contrôle de cet État membre préalablement à leur utilisation.

2.   Les États membres peuvent exiger que la technique de l'assurance maladie visée au paragraphe 1 soit analogue à celle de l'assurance vie lorsque toutes les conditions suivantes sont remplies:

. a) les primes versées sont calculées sur la base de tables de fréquence des maladies et autres données statistiques pertinentes, dans le cas de l'État membre où le risque est situé, selon les méthodes mathématiques appliquées en matière d'assurance;

. b) une réserve de vieillissement est constituée;

. c) l'assureur ne peut annuler le contrat que pendant un certain laps de temps fixé par l'État membre où le risque est situé;

. d) le contrat prévoit la possibilité d'augmenter les primes ou de réduire les versements, même pour les contrats en cours;

. e) le contrat prévoit la possibilité pour le preneur d'assurance d'abandonner son contrat existant pour un nouveau contrat conforme au paragraphe 1, proposé par la même entreprise d'assurance ou la même succursale et tenant compte des droits qu'il a acquis.

Dans le cas visé au premier alinéa, point e), il est tenu compte de la réserve de vieillissement et un nouvel examen médical ne peut être exigé qu'en cas d'extension de la couverture.

Les autorités de contrôle de l'État membre concerné publient les tables de fréquence des maladies et autres données statistiques pertinentes visées au premier alinéa, point a), et les transmettent aux autorités de contrôle de l'État membre d'origine.

Les primes doivent être suffisantes, selon des hypothèses actuarielles raisonnables, pour permettre aux entreprises d'assurance de remplir tous leurs engagements compte tenu de tous les aspects de leur situation financière. L'État membre d'origine exige que la base technique du calcul des primes soit communiquée à ses autorités de contrôle avant que le produit ne soit diffusé.

Les troisième et quatrième alinéas s'appliquent également en cas de modification de contrats existants.

Section 6

Assurance des accidents du travail