= Article 21

Conditions des contrats et tarifs

1.   Les États membres ne peuvent pas exiger l'approbation préalable ou la notification systématique des conditions générales et particulières des polices d'assurance, des tarifs, des bases techniques, utilisées notamment pour le calcul des tarifs et des provisions techniques, et des formulaires et autres imprimés que l'entreprise se propose d'utiliser dans ses relations avec les preneurs d'assurance ou avec les entreprises cédantes ou rétrocédantes.

Cependant, dans le cas de l'assurance vie et dans le seul but de contrôler le respect des dispositions nationales relatives aux principes actuariels, l'État membre d'origine peut exiger la notification systématique des bases techniques utilisées pour le calcul des tarifs et des provisions techniques. Cette exigence ne peut constituer, pour l'entreprise d'assurance vie, une condition préalable d'agrément.

2.   Les États membres ne peuvent maintenir ni introduire des obligations de notification ou d'approbation préalables des majorations de tarifs proposées qu'en tant qu'élément d'un système général de contrôle des prix.

3.   Les États membres peuvent soumettre les entreprises sollicitant ou ayant obtenu l'agrément pour la branche 18 de la partie A de l'annexe I au contrôle des moyens directs ou indirects en personnel et matériel, y compris la qualification des équipes médicales et la qualité de l'équipement dont elles disposent pour faire face à leurs engagements relevant de cette branche.

4.   Les États membres peuvent maintenir ou introduire des dispositions législatives, réglementaires ou administratives qui prévoient l'approbation des statuts et la communication de tout autre document nécessaire à l'exercice normal du contrôle.