= Article 16

Risques accessoires

1.   Une entreprise d'assurance qui a obtenu l'agrément pour un risque principal appartenant à une branche ou à un groupe de branches tels que mentionnés à l'annexe I peut également garantir des risques compris dans une autre branche sans avoir besoin d'obtenir l'agrément pour ces risques, dès lors que ceux-ci remplissent toutes les conditions suivantes:

. a) ils sont liés au risque principal;

. b) ils concernent l'objet qui est couvert contre le risque principal; et

. c) ils sont garantis par le contrat qui couvre le risque principal.

2.   Par dérogation au paragraphe 1, les risques compris dans les branches 14, 15 et 17 mentionnées à la partie A de l'annexe I ne sont pas considérés comme des risques accessoires d'autres branches.

Toutefois, l'assurance protection juridique, telle que mentionnée à la branche 17, peut être considérée comme un risque accessoire de la branche 18 lorsque les conditions énoncées au paragraphe 1 et l'une des deux conditions suivantes sont remplies:

. a) le risque principal ne concerne que l'assistance fournie aux personnes en difficulté au cours de déplacements, d'absences de leur domicile ou de leur résidence habituelle; ou

. b) l'assurance concerne des litiges ou des risques qui résultent de l'utilisation de navires de mer ou qui sont en rapport avec cette utilisation.