== Article 18

=== Conditions d'agrément

1.   L'État membre d'origine exige que toutes les entreprises qui sollicitent l'agrément:

. a) lorsqu'il s'agit d'entreprises d'assurance, limitent leur objet à l'activité d'assurance et aux opérations qui en découlent directement, à l'exclusion de toute autre activité commerciale;

. b) lorsqu'il s'agit d'entreprises de réassurance, limitent leur objet à l'activité de réassurance et aux opérations liées. Cette exigence peut inclure une fonction de société holding et des activités liées au secteur financier, au sens de l'article 2, point 8), de la directive 2002/87/CE;

. c) présentent un programme d'activités conformément à l'article 23;

. d) détiennent les fonds propres de base éligibles nécessaires pour atteindre le seuil plancher absolu du minimum de capital requis prévu à l'article 129, paragraphe 1, point d);

. e) démontrent qu'elles sont en mesure de détenir les fonds propres éligibles nécessaires pour détenir en permanence le capital de solvabilité requis, conformément à l'article 100;

. f) démontrent qu'elles seront en mesure de détenir les fonds propres de base éligibles nécessaires pour détenir en permanence le minimum de capital requis prévu à l'article 128;

. g) démontrent qu'elles seront en mesure de se conformer au système de gouvernance prévu au chapitre IV, section 2;

. h) pour ce qui concerne l'assurance non-vie, communiquent le nom et l'adresse de tous les représentants chargés du règlement des sinistres désignés conformément à l'article 4 de la directive 2000/26/CE, dans chacun des États membres autres que l'État membre dans lequel l'agrément est demandé lorsque les risques à couvrir sont classés dans la branche 10 de la partie A de l'annexe I de la présente directive, à l'exclusion de la responsabilité du transporteur.

2.   L'entreprise d'assurance qui sollicite l'agrément pour l'extension de ses activités à d'autres branches ou pour l'extension d'un agrément couvrant seulement une partie des risques regroupés dans une branche doit présenter un programme d'activité conformément à l'article 23.

En outre, elle doit apporter la preuve qu'elle dispose des fonds propres éligibles nécessaires pour détenir le capital de solvabilité requis et le minimum de capital requis prévus à l'article 100, premier alinéa, et à l'article 128.

3.   Sans préjudice du paragraphe 2, l'entreprise d'assurance exerçant des activités d'assurance vie qui sollicite un agrément pour l'extension de ses activités aux risques compris dans les branches 1 ou 2 de la partie A de l'annexe I, comme prévu à l'article 73, est tenue de démontrer:

. a) qu'elle détient les fonds propres de base éligibles nécessaires pour atteindre à la fois le seuil plancher absolu du minimum de capital requis dans le cas des entreprises d'assurance vie et le seuil plancher absolu du minimum de capital requis dans le cas des entreprises d'assurance non-vie, tels que visés à l'article 129, paragraphe 1, point d);

. b) qu'elle s'engage à honorer en permanence les obligations financières minimales visées à l'article 74, paragraphe 3.

4.   Sans préjudice du paragraphe 2, l'entreprise d'assurance exerçant des activités d'assurance non-vie pour les risques compris dans les branches 1 ou 2 de la partie A de l'annexe I et qui sollicite un agrément pour l'extension de ses activités aux risques d'assurance vie, comme prévu à l'article 73, est tenue de démontrer:

. a) qu'elle détient les fonds propres de base éligibles nécessaires pour atteindre à la fois le seuil plancher absolu du minimum de capital requis dans le cas des entreprises d'assurance vie et le seuil plancher absolu du minimum de capital requis dans le cas des entreprises d'assurance non-vie, tels que visés à l'article 129, paragraphe 1, point d);

. b) qu'elle s'engage à honorer en permanence les obligations financières minimales visées à l'article 74, paragraphe 3.