= Article 15

Champ d'application de l'agrément

1.   Un agrément octroyé conformément à l'article 14 est valable dans l'ensemble de la Communauté. Il permet aux entreprises d'assurance et de réassurance d'y exercer des activités, l'agrément couvrant aussi le droit d'établissement et de libre prestation de services.

2.   Sous réserve de l'article 14, l'agrément est donné par branche d'assurance directe, telle que mentionnée à l'annexe I, partie A, ou à l'annexe II. Il couvre la branche entière, sauf si le demandeur ne désire garantir qu'une partie des risques relevant de cette branche.

Les risques compris dans une branche ne peuvent être classés dans une autre branche sauf dans les cas visés à l'article 16.

L'agrément peut être accordé pour plusieurs branches, pour autant que la législation nationale de l'État membre admette l'exercice simultané des activités relevant de ces branches.

3.   Pour ce qui concerne l'assurance non-vie, chaque État membre a la faculté d'accorder l'agrément pour les groupes de branches mentionnés à la partie B de l'annexe I.

Les autorités de contrôle peuvent limiter l'agrément demandé pour une branche aux seules activités reprises dans le programme d'activité visé à l'article 23.

4.   Les entreprises soumises à la présente directive ne peuvent pratiquer l'activité d'assistance visée à l'article 6 que si elles ont reçu un agrément pour la branche 18 de la partie A de l'annexe I, sans préjudice de l'article 16, paragraphe 1. Dans ce cas, la présente directive s'applique à ces opérations.

5.   Pour ce qui concerne la réassurance, l'agrément est délivré pour l'activité de réassurance non-vie, l'activité de réassurance vie ou tout type d'activité de réassurance.

La demande d'agrément est examinée au vu du programme d'activité qui doit être présenté en vertu de l'article 18, paragraphe 1, point c), et du respect des conditions d'agrément fixées par l'État membre où l'agrément est sollicité.