= Article 23

Programme d'activité

1.   Le programme d'activité visé à l'article 18, paragraphe 1, point c), comprend les indications ou justifications concernant les éléments suivants:

. a) la nature des risques ou des engagements que l'entreprise d'assurance ou de réassurance concernée se propose de couvrir;

. b) le type de contrats de réassurance que l'entreprise de réassurance se propose de conclure avec des entreprises cédantes;

. c) ses principes directeurs en matière de réassurance et de rétrocession;

. d) les éléments des fonds propres de base correspondant au seuil plancher absolu du minimum de capital requis;

. e) les prévisions relatives aux frais d'installation des services administratifs et du réseau de production, les moyens financiers destinés à faire face à ces frais et, si les risques à couvrir sont classés sous la branche 18 de la partie A de l'annexe I, les moyens dont l'entreprise d'assurance dispose pour la fourniture de l'assistance promise.

2.   Outre les éléments requis au paragraphe 1, le programme d'activité contient, pour les trois premiers exercices:

. a) un bilan prévisionnel;

. b) les prévisions relatives au futur capital de solvabilité requis, tel que prévu au chapitre VI, section 4, sous-section 1, sur la base du bilan prévisionnel visé au point a), ainsi que la méthode de calcul utilisée pour établir ces prévisions;

. c) les prévisions relatives au futur minimum de capital requis, tel que prévu aux articles 128 et 129, sur la base du bilan prévisionnel visé au point a), ainsi que la méthode de calcul utilisée pour établir ces prévisions;

. d) les prévisions relatives aux moyens financiers destinés à la couverture des provisions techniques, du minimum de capital requis et du capital de solvabilité requis;

. e) pour l'assurance non-vie et la réassurance:i)les prévisions relatives aux frais de gestion autres que les frais d'installation, notamment les frais généraux courants et les commissions;ii)les prévisions relatives aux primes ou aux cotisations et aux sinistres;

. i) les prévisions relatives aux frais de gestion autres que les frais d'installation, notamment les frais généraux courants et les commissions;

. ii) les prévisions relatives aux primes ou aux cotisations et aux sinistres;

. f) pour l'assurance vie: un plan faisant apparaître d'une manière détaillée les prévisions de recettes et de dépenses tant pour les opérations directes que pour les acceptations en réassurance et les cessions en réassurance.