= Article 26

Consultation préalable des autorités des autres États membres

1.   Les autorités de contrôle de tout autre État membre concerné sont consultées avant l'octroi d'un agrément à:

. a) une filiale d'une entreprise d'assurance ou de réassurance agréée dans ledit État membre;

. b) une filiale de l'entreprise mère d'une entreprise d'assurance ou de réassurance agréée dans ledit État membre; ou

. c) une entreprise contrôlée par la même personne, physique ou morale, qu'une entreprise d'assurance ou de réassurance agréée dans ledit État membre.

2.   Les autorités d'un État membre concerné qui sont chargées du contrôle des établissements de crédit ou des entreprises d'investissement sont consultées avant l'octroi d'un agrément à une entreprise d'assurance ou de réassurance qui est:

. a) une filiale d'un établissement de crédit ou d'une entreprise d'investissement agréés dans la Communauté;

. b) une filiale de l'entreprise mère d'un établissement de crédit ou d'une entreprise d'investissement agréés dans la Communauté; ou

. c) une entreprise contrôlée par la même personne, physique ou morale, qu'un établissement de crédit ou une entreprise d'investissement agréés dans la Communauté.

3.   Les autorités concernées visées aux paragraphes 1 et 2 se consultent, en particulier, aux fins d'évaluer la qualité des actionnaires ainsi que la compétence et l'honorabilité de toutes les personnes qui dirigent effectivement l'entreprise ou qui occupent d'autres fonctions clés associées à la gestion d'une autre entité du même groupe.

Elles se communiquent mutuellement toute information concernant la qualité des actionnaires ainsi que la compétence et l'honorabilité de toutes les personnes qui dirigent effectivement l'entreprise ou qui occupent d'autres fonctions clés, dès lors que cette information intéresse les autres autorités compétentes concernées tant pour l'octroi d'un agrément que pour le contrôle continu du respect des conditions d'exercice.

CHAPITRE III

Autorités de contrôle et règles générales