== Article 24

=== Actionnaires et associés détenant une participation qualifiée

1.   Les autorités de contrôle de l'État membre d'origine n'accordent pas à une entreprise l'agrément permettant l'accès à l'activité d'assurance ou de réassurance avant d'avoir obtenu communication de l'identité des actionnaires ou des associés, directs ou indirects, personnes physiques ou morales, qui y détiennent une participation qualifiée, et du montant de cette participation.

Ces autorités refusent l'agrément si, compte tenu de la nécessité de garantir une gestion saine et prudente d'une entreprise d'assurance ou de réassurance, elles ne sont pas satisfaites de la qualité des actionnaires ou des associés.

2.   Aux fins du paragraphe 1, les droits de vote visés aux articles 9 et 10 de la directive 2004/109/CE du Parlement européen et du Conseil du 15 décembre 2004 sur l'harmonisation des obligations de transparence concernant l'information sur les émetteurs dont les valeurs mobilières sont admises à la négociation sur un marché réglementé(31), ainsi que les conditions régissant leur agrégation énoncées à l'article 12, paragraphes 4 et 5, de ladite directive sont pris en compte.

Les États membres ne tiennent pas compte des droits de vote ou des actions que des entreprises d'investissement ou des établissements de crédit peuvent détenir à la suite de la prise ferme d'instruments financiers et/ou du placement d'instruments financiers avec engagement ferme visés à l'annexe I, section A, point 6, de la directive 2004/39/CE pour autant que, d'une part, ces droits ne soient pas exercés ni utilisés autrement pour intervenir dans la gestion de l'émetteur et que, d'autre part, ils soient cédés dans un délai d'un an après l'acquisition.