== Article 287

=== Réserve de propriété

1.   L'adoption de mesures d'assainissement ou l'ouverture d'une procédure de liquidation à l'encontre d'une entreprise d'assurance achetant un actif n'affecte pas les droits du vendeur fondés sur une réserve de propriété, lorsque cet actif se trouve, au moment de l'adoption de telles mesures ou de l'ouverture d'une telle procédure, sur le territoire d'un État membre autre que l'État membre dans lequel de telles mesures ont été adoptées ou une telle procédure a été ouverte.

2.   L'adoption de mesures d'assainissement ou l'ouverture d'une procédure de liquidation, après la livraison de l'actif, à l'encontre d'une entreprise d'assurance vendant un actif ne constitue pas une cause de résolution ou de résiliation de la vente et ne fait pas obstacle à l'acquisition par l'acheteur de la propriété de l'actif vendu, lorsque cet actif se trouve, au moment de l'adoption de telles mesures ou de l'ouverture d'une telle procédure, sur le territoire d'un État membre autre que l'État dans lequel de telles mesures ont été adoptées ou une telle procédure a été ouverte.

3.   Les paragraphes 1 et 2 ne font pas obstacle aux actions en nullité, en annulation ou en inopposabilité visées à l'article 274, paragraphe 2, point l).