== Article 286

=== Droits réels des tiers

1.   L'adoption de mesures d'assainissement ou l'ouverture d'une procédure de liquidation n'affecte pas les droits réels d'un créancier ou d'un tiers sur des actifs corporels ou incorporels, meubles ou immeubles – tant des actifs déterminés que des ensembles d'actifs indéterminés dont la composition est sujette à modification – appartenant à l'entreprise d'assurance et qui se trouvent, au moment de l'adoption de telles mesures ou de l'ouverture d'une telle procédure, sur le territoire d'un autre État membre.

2.   Les droits visés au paragraphe 1 sont au moins les suivants:

. a) le droit de réaliser ou de faire réaliser les actifs et d'être désintéressé par le produit ou les revenus de ces actifs, en particulier en vertu d'un gage ou d'une hypothèque;

. b) le droit exclusif de recouvrer une créance, notamment en vertu de la mise en gage ou de la cession de cette créance à titre de garantie;

. c) le droit de revendiquer les actifs, ou d'en réclamer la restitution, entre les mains de quiconque les détient ou en jouit contre la volonté de l'ayant droit;

. d) le droit de percevoir les fruits d'un actif.

3.   Le droit inscrit dans un registre public et opposable aux tiers, qui permet d'obtenir un droit réel au sens du paragraphe 1, est assimilé à un droit réel.

4.   Le paragraphe 1 ne fait pas obstacle aux actions en nullité, en annulation ou en inopposabilité visées à l'article 274, paragraphe 2, point l).