== Article 293

=== Administrateurs et liquidateurs

1.   La désignation d'un administrateur ou d'un liquidateur est établie par la présentation d'une copie, certifiée conforme à l'original, de la décision qui le désigne ou par tout autre certificat établi par les autorités compétentes de l'État membre d'origine.

L'État membre dans lequel l'administrateur ou le liquidateur entend agir peut exiger une traduction dans sa langue officielle ou une de ses langues officielles. Aucune authentification officielle de cette traduction ou autre formalité analogue n'est requise.

2.   Les administrateurs et les liquidateurs sont habilités à exercer sur le territoire de tous les États membres tous les pouvoirs qu'ils sont habilités à exercer sur le territoire de l'État membre d'origine.

Des personnes chargées d'assister ou de représenter les administrateurs et les liquidateurs peuvent être désignées, conformément au droit de l'État membre d'origine, pendant le déroulement de la mesure d'assainissement ou de la procédure de liquidation, notamment dans les États membres d'accueil et en particulier afin d'aider à résoudre des difficultés éventuellement rencontrées par les créanciers dans cet État.

3.   Dans l'exercice de ses pouvoirs conformément au droit de l'État membre d'origine, l'administrateur ou le liquidateur respecte le droit des États membres dans lesquels il entend agir, en particulier quant aux procédures de réalisation des actifs et quant à l'information des travailleurs salariés.

Ces pouvoirs ne peuvent pas inclure l'emploi de la force ou le droit de statuer sur un litige ou un différend.