== Article 246

=== Contrôle du système de gouvernance

1.   Les exigences prévues au titre I, chapitre IV, section 2, s'appliquentmutatis mutandisau niveau du groupe.

Sans préjudice du premier alinéa, les systèmes de gestion des risques et de contrôle interne ainsi que les procédures de déclaration sont appliqués de façon cohérente dans toutes les entreprises rentrant dans le champ d'application du contrôle de groupe conformément à l'article 213, paragraphe 2, points a) et b), afin que ces systèmes et procédures puissent être contrôlés au niveau du groupe.

2.   Sans préjudice du paragraphe 1, les mécanismes de contrôle interne d'un groupe comportent au moins les éléments suivants:

. a) des mécanismes adéquats en ce qui concerne la solvabilité du groupe, permettant d'identifier et de mesurer tous les risques importants encourus et de rattacher d'une manière appropriée les fonds propres éligibles aux risques;

. b) des procédures saines de déclaration et de comptabilité pour contrôler et gérer les transactions intragroupe ainsi que la concentration de risques.

3.   Les systèmes et les procédures de déclaration visés aux paragraphes 1 et 2 sont soumis au contrôle prudentiel du contrôleur du groupe conformément aux dispositions du chapitre III.

4.   Les États membres imposent à l'entreprise d'assurance ou de réassurance participante ou à la société holding d'assurance de procéder au niveau du groupe à l'évaluation requise par l'article 45. L'évaluation interne des risques et de la solvabilité menée au niveau du groupe fait l'objet d'un contrôle prudentiel par le contrôleur du groupe conformément au chapitre III.

Lorsque le calcul de solvabilité est mené au niveau du groupe selon la première méthode, telle que visée à l'article 230, l'entreprise d'assurance ou de réassurance participante ou la société holding d'assurance fournit au contrôleur du groupe une analyse appropriée de la différence entre la somme des différents montants de capital de solvabilité requis pour toutes les entreprises d'assurance ou de réassurance liées appartenant au groupe et le capital de solvabilité requis pour le groupe sur une base consolidée.

Lorsque l'entreprise d'assurance ou de réassurance participante ou la société holding d'assurance le décide, et sous réserve de l'accord du contrôleur du groupe, elle peut procéder en même temps à toutes les évaluations imposées par l'article 45 au niveau du groupe et au niveau de toute filiale du groupe et rédiger un document unique couvrant toutes les évaluations.

Avant de donner l'accord prévu au troisième alinéa, le contrôleur du groupe consulte les membres du collège des contrôleurs et tient dûment compte de leurs avis et de leurs réserves.

Si le groupe choisit l'option prévue au troisième alinéa, il soumet le document simultanément à toutes les autorités de contrôle concernées. Le choix de cette option n'exempte pas les filiales concernées de l'obligation de veiller au respect des exigences de l'article 45.

CHAPITRE III

Mesures visant à faciliter le contrôle des groupes