= Article 190

Opérations de coassurance communautaire

1.   La présente section s'applique aux opérations de coassurance communautaire qui concernent un ou plusieurs risques classés dans les branches 3 à 16 de la partie A de l'annexe I et qui répondent aux conditions suivantes:

. a) le risque est un grand risque;

. b) le risque est couvert par plusieurs entreprises d'assurance en qualité de «coassureurs», dont un est l'apériteur, sans qu'il y ait de solidarité entre eux, au moyen d'un contrat unique, moyennant une prime globale et pour une même durée;

. c) le risque est situé à l'intérieur de la Communauté;

. d) pour garantir le risque, l'apériteur est traité comme s'il était l'entreprise d'assurance qui couvre la totalité du risque;

. e) au moins un des coassureurs participe au contrat par l'intermédiaire de son siège social ou d'une succursale établis dans un État membre autre que celui de l'apériteur;

. f) l'apériteur assume pleinement le rôle directeur qui lui revient dans la pratique de la coassurance et, en particulier, détermine les conditions d'assurance et de tarification.

2.   Les articles 147 à 152 ne s'appliquent qu'à l'apériteur.

3.   Les opérations de coassurance qui ne répondent pas aux conditions du paragraphe 1 demeurent soumises aux dispositions de la présente directive, à l'exclusion de celles figurant dans la présente section.