== Article 148

=== Notification par l'État membre d'origine

1.   Les autorités de contrôle de l'État membre d'origine communiquent, dans un délai d'un mois à compter de la notification prévue à l'article 147, les éléments suivants à l'État membre ou aux États membres sur le territoire duquel ou desquels l'entreprise d'assurance désire exercer des activités dans le cadre de la libre prestation de services:

. a) une attestation indiquant que l'entreprise d'assurance dispose du capital de solvabilité requis et du minimum de capital requis, calculés conformément aux articles 100 et 129;

. b) les branches d'assurance pour lesquelles l'entreprise d'assurance a été agréée;

. c) la nature des risques et des engagements que l'entreprise d'assurance se propose de couvrir dans l'État membre d'accueil.

En même temps, les autorités de contrôle de l'État membre d'origine informent l'entreprise d'assurance concernée de cette communication.

2.   Les États membres sur le territoire desquels une entreprise d'assurance non-vie entend couvrir dans le cadre de la libre prestation de services des risques classés dans la branche 10 de la partie A de l'annexe I, à l'exclusion de la responsabilité du transporteur, peuvent exiger que l'entreprise d'assurance fournisse:

. a) le nom et l'adresse du représentant visé à l'article 18, paragraphe 1, point h);

. b) une déclaration selon laquelle elle est devenue membre du bureau national et du fonds national de garantie de l'État membre d'accueil.

3.   Lorsque les autorités de contrôle de l'État membre d'origine ne communiquent pas les informations visées au paragraphe 1 dans le délai qui y est prévu, elles font connaître dans ce même délai les motifs de ce refus à l'entreprise d'assurance.

Ce refus ou l'absence de réaction peuvent faire l'objet d'un recours juridictionnel dans l'État membre d'origine.

4.   L'entreprise d'assurance peut commencer son activité à partir de la date à laquelle elle a été avisée de la communication prévue au paragraphe 1, premier alinéa.