== Article 154

=== Notification et approbation préalables

1.   L'État membre d'accueil n'arrête pas de dispositions exigeant l'approbation préalable ou la notification systématique des conditions générales et particulières des polices d'assurance, des tarifs ou, dans le cas de l'assurance vie, des bases techniques utilisées notamment pour le calcul des tarifs et des provisions techniques, et des formulaires et autres documents que l'entreprise d'assurance se propose d'utiliser dans ses relations avec les preneurs d'assurance.

2.   Dans le but de contrôler le respect des dispositions nationales relatives aux contrats d'assurance, l'État membre d'accueil ne peut exiger d'une entreprise d'assurance souhaitant effectuer sur son territoire des opérations d'assurance que la notification non systématique des conditions et des autres documents qu'elle se propose d'utiliser, sans que cette exigence puisse constituer pour l'entreprise d'assurance une condition préalable de l'exercice de son activité.

3.   L'État membre d'accueil ne peut maintenir ni introduire des obligations de notification ou d'approbation préalables des majorations de tarifs proposées qu'en tant qu'élément d'un système général de contrôle des prix.