= Article 157

Taxes sur les primes

1.   Sans préjudice d'une harmonisation ultérieure, tout contrat d'assurance est exclusivement soumis aux impôts indirects et taxes parafiscales sur les primes d'assurance dans l'État membre où le risque est situé ou l'État membre de l'engagement.

Aux fins du premier alinéa, les biens meubles contenus dans un immeuble situé sur le territoire d'un État membre, à l'exception des biens en transit commercial, sont considérés comme un risque situé dans cet État membre, même lorsque l'immeuble et son contenu ne sont pas couverts par la même police d'assurance.

Dans le cas de l'Espagne, un contrat d'assurance est également soumis aux surcharges fixées légalement en faveur de l'organisme espagnol «Consorcio de Compensación de Seguros» pour les besoins de ses fonctions en matière de compensation des pertes résultant d'événements extraordinaires survenant dans cet État membre.

2.   Le droit applicable au contrat en vertu de l'article 178 de la présente directive et en vertu du règlement (CE) no593/2008 est sans incidence sur le régime fiscal applicable.

3.   Chaque État membre applique aux entreprises d'assurance qui couvrent des risques ou des engagements situés sur son territoire ses dispositions nationales concernant les mesures destinées à assurer la perception des impôts indirects et taxes parafiscales dus au titre du paragraphe 1.

Sous-section 2

Réassurance