== Article 155

=== Entreprises d'assurance ne se conformant pas aux dispositions légales

1.   Lorsque les autorités de contrôle d'un État membre d'accueil constatent qu'une entreprise d'assurance ayant une succursale ou opérant dans le cadre de la libre prestation de services sur son territoire ne respecte pas les dispositions légales de cet État membre qui lui sont applicables, elles exigent de l'entreprise d'assurance concernée qu'elle mette fin à cette irrégularité.

2.   Si l'entreprise d'assurance concernée ne fait pas le nécessaire, les autorités de contrôle de l'État membre concerné en informent les autorités de contrôle de l'État membre d'origine.

Les autorités de contrôle de l'État membre d'origine prennent, dans les plus brefs délais, toutes les mesures appropriées pour garantir que l'entreprise d'assurance concernée mette fin à cette situation irrégulière.

Les autorités de contrôle de l'État membre d'origine informent les autorités de contrôle de l'État membre d'accueil des mesures qui ont été prises.

3.   Si, en dépit des mesures prises par l'État membre d'origine, ou parce que ces mesures apparaissent inadéquates ou qu'elles font défaut dans cet État, l'entreprise d'assurance persiste à enfreindre les dispositions légales en vigueur dans l'État membre d'accueil, les autorités de contrôle de l'État membre d'accueil peuvent, après en avoir informé les autorités de contrôle de l'État membre d'origine, prendre les mesures appropriées pour prévenir ou réprimer de nouvelles irrégularités, y compris, pour autant que cela soit absolument nécessaire, empêcher l'entreprise de continuer à conclure de nouveaux contrats d'assurance sur le territoire de l'État membre d'accueil.

Les États membres veillent à ce que les documents juridiques nécessaires à de telles mesures puissent être signifiés sur leur territoire aux entreprises d'assurance.

4.   Les paragraphes 1, 2 et 3 n'affectent pas le pouvoir des États membres concernés de prendre, en cas d'urgence, des mesures appropriées pour prévenir ou réprimer les irrégularités sur leur territoire. Ce pouvoir comporte la possibilité d'empêcher une entreprise d'assurance de continuer à conclure de nouveaux contrats d'assurance sur leur territoire.

5.   Les paragraphes 1, 2 et 3 n'affectent pas le pouvoir des États membres de sanctionner les infractions sur leur territoire.

6.   Lorsque l'entreprise d'assurance qui a commis l'infraction dispose d'un établissement ou possède des biens dans l'État membre concerné, les autorités de contrôle de cet État membre peuvent, conformément au droit national, mettre à exécution les sanctions administratives nationales prévues pour cette infraction à l'égard de cet établissement ou de ces biens.

7.   Toute mesure qui est prise en application des paragraphes 2 à 6 et qui comporte des restrictions à l'exercice de l'activité d'assurance est dûment motivée et notifiée à l'entreprise d'assurance concernée.

8.   Les entreprises d'assurance soumettent aux autorités de contrôle de l'État membre d'accueil, à leur demande, tous les documents qui leur sont demandés aux fins de l'application des paragraphes 1 à 7, dans la mesure où une telle obligation s'applique également aux entreprises d'assurance ayant leur siège social dans cet État membre.

9.   Les États membres indiquent à la Commission le nombre et le type de cas qui ont abouti à un refus au titre des articles 146 et 148 et dans lesquels des mesures ont été prises au titre du paragraphe 4 du présent article.

Sur la base de ces informations, la Commission fait rapport au comité européen des assurances et des pensions professionnelles, tous les deux ans.