= Article 202

Exception à la liberté de choix de l'avocat

1.   Les États membres peuvent exempter des dispositions de l'article 201, paragraphe 1, pour l'assurance-protection juridique si toutes les conditions suivantes sont remplies:

. a) l'assurance est limitée à des affaires résultant de l'utilisation de véhicules routiers sur le territoire de l'État membre en question;

. b) l'assurance est liée à un contrat d'assistance à fournir en cas d'accident ou de panne impliquant un véhicule routier;

. c) ni l'entreprise d'assurance de la protection juridique ni l'assureur de l'assistance n'exercent des activités relevant d'une branche de l'assurance de responsabilité;

. d) des dispositions sont prises afin que les conseils juridiques soient fournis et la représentation de chacune des parties d'un litige soit assurée par des avocats tout à fait indépendants, lorsque ces parties sont assurées en protection juridique auprès de la même entreprise d'assurance.

2.   Une exemption accordée en application du paragraphe 1 n'affecte pas l'application de l'article 200.