= Article 200

Gestion des sinistres

1.   L'État membre d'origine veille à ce que les entreprises d'assurance adoptent, suivant l'option choisie par l'État membre ou selon leur choix si l'État membre y consent, au moins l'une des méthodes de gestion des sinistres énoncées aux paragraphes 2, 3 et 4.

Quelle que soit l'option retenue, l'intérêt des assurés couverts en protection juridique est considéré comme garanti de manière équivalente en vertu de la présente section.

2.   Les entreprises d'assurance veillent à ce qu'aucun membre du personnel qui s'occupe de la gestion des sinistres relevant de la protection juridique ou fournit des conseils juridiques y relatifs n'exerce en même temps une activité semblable dans une autre entreprise ayant avec la première entreprise d'assurance des liens financiers, commerciaux ou administratifs et exerçant des activités relevant d'une ou plusieurs autres branches d'assurance énumérées à l'annexe I.

Les entreprises d'assurance multibranches veillent à ce qu'aucun membre du personnel qui s'occupe de la gestion des sinistres relevant de la protection juridique ou fournit des conseils juridiques y relatifs n'exerce en même temps une activité semblable pour une autre branche pratiquée par elles.

3.   Les entreprises d'assurance confient la gestion des sinistres relevant de la protection juridique à une entreprise juridiquement distincte. Il est fait mention de cette entreprise dans le contrat distinct ou le chapitre distinct visés à l'article 199.

Lorsque cette entreprise juridiquement distincte est liée à une entreprise d'assurance qui pratique l'assurance dans une ou plusieurs branches mentionnées à la partie A de l'annexe I, les membres du personnel de l'entreprise juridiquement distincte qui s'occupent de la gestion des sinistres ou fournissent des conseils juridiques relatifs à cette gestion ne peuvent pas exercer en même temps la même activité ou une activité semblable pour l'autre entreprise d'assurance. Les États membres peuvent imposer les mêmes exigences pour les membres de l'organe d'administration, de gestion ou de contrôle.

4.   Le contrat prévoit que dès qu'il est en droit de réclamer une intervention au titre de ce contrat, l'assuré a le droit de confier la défense de ses intérêts à un avocat de son choix ou, dans la mesure où le droit national le permet, à toute autre personne ayant les qualifications appropriées.