== Article 201

=== Libre choix de l'avocat

1.   Tout contrat d'assurance protection juridique prévoit explicitement:

. a) que, lorsqu'il est fait appel à un avocat ou à toute autre personne ayant les qualifications appropriées selon le droit national, pour défendre, représenter ou servir les intérêts de l'assuré dans une procédure judiciaire ou administrative, l'assuré a la liberté de choisir cet avocat ou cette autre personne;

. b) que, chaque fois que surgit un conflit d'intérêts, l'assuré a la liberté de choisir un avocat ou, s'il le préfère et dans la mesure où le droit national le permet, toute autre personne ayant les qualifications appropriées, pour servir ses intérêts.

2.   Aux fins de la présente section, on entend par «avocat» toute personne habilitée à exercer ses activités professionnelles sous une des dénominations prévues par la directive 77/249/CEE du Conseil du 22 mars 1977 tendant à faciliter l'exercice effectif de la libre prestation de services par les avocats(36).