= Article 198

Champ d'application de la présente section

1.   La présente section s'applique à l'assurance-protection juridique visée à la branche 17 de la partie A de l'annexe I, par laquelle une entreprise d'assurance s'engage, moyennant le paiement d'une prime, à prendre en charge des frais de procédure judiciaire et à fournir d'autres services directement liés à la couverture d'assurance, notamment en vue:

. a) d'obtenir une indemnisation pour un dommage subi par l'assuré, à l'amiable ou dans une procédure civile ou pénale;

. b) de défendre ou de représenter l'assuré dans une procédure civile, pénale, administrative ou autre, ou contre une réclamation dont il est l'objet.

2.   La présente section ne s'applique pas:

. a) à l'assurance-protection juridique lorsque celle-ci concerne des litiges ou des risques qui résultent de l'utilisation de navires de mer ou qui sont en rapport avec cette utilisation;

. b) à l'activité exercée par une entreprise d'assurance couvrant la responsabilité civile en vue de défendre ou de représenter son assuré dans toute procédure judiciaire ou administrative, lorsque cette activité est exercée en même temps dans le propre intérêt de cette entreprise d'assurance au titre de cette couverture;

. c) si un État membre le décide, à l'activité d'assurance-protection juridique déployée par un assureur en matière d'assistance qui remplit les conditions suivantes:i)l'activité est effectuée dans un État membre autre que celui où l'assuré a sa résidence habituelle;ii)l'activité fait partie d'un contrat qui ne concerne que l'assistance fournie aux personnes en difficulté au cours de déplacements, d'absences de leur domicile ou de leur résidence habituelle.

. i) l'activité est effectuée dans un État membre autre que celui où l'assuré a sa résidence habituelle;

. ii) l'activité fait partie d'un contrat qui ne concerne que l'assistance fournie aux personnes en difficulté au cours de déplacements, d'absences de leur domicile ou de leur résidence habituelle.

Aux fins du premier alinéa, point c), le contrat indique de façon claire que la couverture en question est limitée aux circonstances visées à ce point et qu'elle est accessoire à l'assistance.