= Article 74

Gestion distincte des activités d'assurance vie et non-vie

1.   La gestion distincte mentionnée à l'article 73 est organisée de telle sorte que l'activité d'assurance vie et l'activité d'assurance non-vie soient séparées.

Il ne peut être porté préjudice aux intérêts respectifs des preneurs d'assurance vie et d'assurance non-vie, et, en particulier, les bénéfices provenant de l'assurance vie profitent aux assurés sur la vie comme si l'entreprise d'assurance vie n'exerçait que l'activité d'assurance vie.

2.   Sans préjudice des articles 100 et 128, les entreprises d'assurance visées à l'article 73, paragraphes 2 et 5, calculent:

. a) un montant notionnel du minimum de capital requis en vie, pour ce qui concerne leurs activités d'assurance ou de réassurance vie, calculé comme si l'entreprise concernée n'exerçait que ces activités, sur la base des comptes séparés visés au paragraphe 6; et

. b) un montant notionnel du minimum de capital requis en non-vie, pour ce qui concerne leurs activités d'assurance ou de réassurance non-vie, calculé comme si l'entreprise concernée n'exerçait que ces activités, sur la base des comptes séparés visés au paragraphe 6.

3.   Au minimum, les entreprises d'assurance visées à l'article 73, paragraphes 2 et 5, couvrent les exigences suivantes par un montant équivalent d'éléments de capital de base éligibles:

. a) le montant notionnel du minimum de capital requis en vie, pour l'activité vie;

. b) le montant notionnel du minimum de capital requis en non-vie, pour l'activité non-vie.

Les obligations financières minimales visées au premier alinéa, se rapportant à l'activité d'assurance vie et à l'activité d'assurance non-vie, ne peuvent être supportées par l'autre activité.

4.   Aussi longtemps que sont remplies les obligations financières minimales visées au paragraphe 3 et sous réserve d'en informer l'autorité de contrôle, l'entreprise peut utiliser, pour couvrir le capital de solvabilité requis visé à l'article 100, les éléments explicites de fonds propres éligibles encore disponibles pour l'une ou l'autre activité.

5.   Les autorités de contrôle analysent les résultats tant des activités de l'assurance vie que de celle de l'assurance non-vie, afin d'assurer le respect des exigences énoncées aux paragraphes 1 à 4.

6.   Les écritures comptables sont établies de façon à faire apparaître séparément les sources de résultats pour l'assurance vie et non-vie. L'ensemble des recettes, notamment les primes, les interventions des réassureurs et revenus financiers, et des dépenses, notamment prestations d'assurance, versements aux provisions techniques, primes de réassurance et dépenses de fonctionnement pour les opérations d'assurance, est ventilé en fonction de leur origine. Les éléments communs aux deux activités sont comptabilisés selon des méthodes de répartition qui sont acceptées par l'autorité de contrôle.

Les entreprises d'assurance établissent, sur la base des écritures comptables, un document dans lequel les éléments de fonds propres de base éligibles couvrant chaque montant notionnel du minimum de capital requis visé au paragraphe 2 sont clairement identifiés conformément à l'article 98, paragraphe 4.

7.   Si le montant des éléments de fonds propres de base éligibles affectés à l'une des activités ne suffit pas à couvrir les obligations financières minimales visées au paragraphe 3, premier alinéa, les autorités de contrôle appliquent à l'activité déficitaire les mesures prévues par la présente directive quels que soient les résultats obtenus dans l'autre activité.

Par dérogation au paragraphe 3, second alinéa, ces mesures peuvent comporter l'autorisation d'un transfert d'éléments explicites des capital de base éligibles d'une activité à l'autre.

CHAPITRE VI

Règles relatives à la valorisation des actifs et des passifs, provisions techniques, fonds propres, capital de solvabilité requis, minimum de capital requis et règles d'investissement

Section 1

Valorisation des actifs et des passifs