== Article 73

=== Exercice simultané des activités d'assurance vie et non-vie

1.   Les entreprises d'assurance ne sont pas autorisées à exercer simultanément les activités d'assurance vie et non-vie.

2.   Par dérogation au paragraphe 1, les États membres peuvent prévoir ce qui suit:

. a) les entreprises qui ont reçu l'agrément pour l'exercice de l'activité d'assurance vie peuvent obtenir un agrément pour l'exercice d'activités d'assurance non-vie restreintes aux risques visés aux branches 1 et 2 de la partie A de l'annexe I;

. b) les entreprises agréées uniquement pour les risques visés aux branches 1 et 2 de la partie A de l'annexe I peuvent obtenir un agrément pour l'exercice de l'activité d'assurance vie.

Chaque activité doit cependant faire l'objet d'une gestion distincte, conformément à l'article 74.

3.   Les États membres peuvent prévoir que les entreprises visées au paragraphe 2 respectent les règles comptables qui régissent les entreprises d'assurance vie pour l'ensemble de leur activité. Les États membres peuvent également prévoir, dans l'attente d'une coordination en la matière, que, en ce qui concerne les règles de la liquidation, les activités relatives aux risques énumérés dans les branches 1 et 2 de la partie A de l'annexe I qui sont exercées par ces entreprises sont régies par les règles applicables aux activités d'assurance vie.

4.   Lorsqu'une entreprise d'assurance non-vie a des liens financiers, commerciaux ou administratifs avec une entreprise d'assurance vie, les autorités de contrôle des États membres d'origine veillent à ce que les comptes des entreprises concernées ne soient pas faussés par des conventions passées entre ces entreprises ou par tout arrangement susceptible d'influencer la répartition des frais et des revenus.

5.   Les entreprises qui, aux dates suivantes, exerçaient simultanément les activités d'assurance vie et non-vie relevant de la présente directive peuvent continuer à les exercer simultanément, à condition d'adopter une gestion distincte, conformément à l'article 74, pour chacune de ces activités:

. a) 1erjanvier 1981 pour les entreprises agréées en Grèce;

. b) 1erjanvier 1986 pour les entreprises agréées en Espagne et au Portugal;

. c) 1erjanvier 1995 pour les entreprises agréées en Autriche, en Finlande et en Suède;

. d) 1ermai 2004 pour les entreprises agréées en République tchèque, en Estonie, à Chypre, en Lettonie, en Lituanie, en Hongrie, à Malte, en Pologne, en Slovaquie et en Slovénie;

. e) 1erjanvier 2007 pour les entreprises agréées en Bulgarie et en Roumanie;

. f) 15 mars 1979 pour toutes les autres entreprises.

L'État membre d'origine peut imposer aux entreprises d'assurance l'obligation de mettre fin, dans le délai qu'il détermine, à l'exercice simultané des activités d'assurance vie et non-vie qu'elles pratiquaient aux dates citées au premier alinéa.