= Article 62

Participations qualifiées et pouvoirs des autorités de contrôle

Les États membres prévoient que, lorsque l'influence exercée par les personnes visées à l'article 57 est susceptible de porter atteinte à une gestion saine et prudente de l'entreprise d'assurance ou de réassurance, l'autorité de contrôle de l'État membre d'origine de cette entreprise, dans le capital de laquelle une participation qualifiée est recherchée ou augmentée prend des mesures appropriées en vue de mettre fin à cette situation. Ces mesures peuvent, par exemple, consister en des injonctions, des sanctions à l'encontre des directeurs ou administrateurs ou la suspension de l'exercice des droits de vote attachés aux actions ou parts détenues par les actionnaires ou associés en question.

Des mesures similaires s'appliquent aux personnes physiques ou morales qui ne respectent pas l'obligation de notification établie à l'article 57.

Lorsqu'une participation est acquise en dépit de l'opposition des autorités de contrôle, les États membres, indépendamment d'autres sanctions à adopter, prévoient:

. 1) la suspension de l'exercice des droits de vote correspondants; ou

. 2) la nullité des votes émis ou la possibilité de les annuler.