== Article 60

=== Acquisitions réalisées par des entreprises financières réglementées

1.   Les autorités de contrôle concernées travaillent en pleine concertation à l'évaluation si le candidat acquéreur est:

. a) un établissement de crédit, une entreprise d'assurance ou de réassurance, une entreprise d'investissement ou une société de gestion au sens de l'article 1erbis, point 2), de la directive 85/611/CEE (ci-après dénommée «société de gestion d'OPCVM») agréés dans un autre État membre ou dans un secteur autre que celui dans lequel l'acquisition est envisagée;

. b) l'entreprise mère d'un établissement de crédit, d'une entreprise d'assurance ou de réassurance, d'une entreprise d'investissement ou d'une société de gestion d'OPCVM agréés dans un autre État membre ou dans un secteur autre que celui dans lequel l'acquisition est envisagée; ou

. c) une personne physique ou morale contrôlant un établissement de crédit, une entreprise d'assurance ou de réassurance, une entreprise d'investissement ou une société de gestion d'OPCVM agréés dans un autre État membre ou dans un secteur autre que celui dans lequel l'acquisition est envisagée.

2.   Les autorités de contrôle échangent, sans délai indu, toute information essentielle ou pertinente pour l'évaluation. Dans ce cadre, elles se communiquent, sur demande, toute information pertinente et de leur propre initiative toute information essentielle. Toute décision de l'autorité de contrôle qui a agréé l'entreprise d'assurance ou de réassurance visée par l'acquisition envisagée mentionne les éventuels avis ou réserves formulés par l'autorité de contrôle responsable du candidat acquéreur.