== Article 57

=== Acquisitions

1.   Les États membres exigent de toute personne physique ou morale, agissant seule ou de concert avec d'autres (ci-après dénommée «candidat acquéreur»), qui a pris la décision soit d'acquérir, directement ou indirectement, une participation qualifiée dans une entreprise d'assurance ou de réassurance soit de procéder, directement ou indirectement, à une augmentation de cette participation qualifiée dans une entreprise d'assurance ou de réassurance, de telle façon que la proportion de droits de vote ou de parts de capital détenue atteigne ou dépasse les seuils de 20 %, de 30 % ou de 50 % ou que l'entreprise d'assurance ou de réassurance devienne sa filiale (ci-après dénommée «l'acquisition envisagée»), qu'elle notifie par écrit au préalable aux autorités de contrôle de l'entreprise d'assurance ou de réassurance dans laquelle elle souhaite acquérir ou augmenter une participation qualifiée le montant envisagé de sa participation et les informations pertinentes visées à l'article 59, paragraphe 4. Les États membres ne sont pas tenus d'appliquer le seuil de 30 % dans les cas où, en vertu de l'article 9, paragraphe 3, point a), de la directive 2004/109/CE, ils appliquent un seuil d'un tiers.

2.   Les États membres prévoient que toute personne physique ou morale qui a pris la décision de cesser de détenir, directement ou indirectement, une participation qualifiée dans une entreprise d'assurance ou de réassurance le notifie par écrit au préalable aux autorités de contrôle de l'État membre d'origine et communique le montant de la participation de ladite personne après la cession envisagée. Une telle personne notifie de même aux autorités de contrôle sa décision de diminuer sa participation qualifiée de telle façon que la proportion de droits de vote ou de parts de capital détenue descende en dessous des seuils de 20 %, de 30 % ou de 50 % ou que l'entreprise d'assurance ou de réassurance cesse d'être une filiale de ladite personne. Les États membres ne sont pas tenus d'appliquer le seuil de 30 % dans les cas où, en vertu de l'article 9, paragraphe 3, point a), de la directive 2004/109/CE, ils appliquent un seuil d'un tiers.