== Article 58

=== Période d'évaluation

1.   Diligemment, et en toute hypothèse dans un délai de deux jours ouvrables après la réception de la notification exigée à l'article 57, paragraphe 1, ainsi qu'après l'éventuelle réception ultérieure des informations visées au paragraphe 2, les autorités de contrôle en accusent réception par écrit au candidat acquéreur.

Les autorités de contrôle disposent d'un maximum de soixante jours ouvrables à compter de la date de l'accusé écrit de réception de la notification et de tous les documents dont l'État membre exige communication avec la notification sur la base de la liste visée à l'article 59, paragraphe 4, (ci-après dénommé «période d'évaluation») pour procéder à l'évaluation prévue à l'article 59, paragraphe 1 (ci-après dénommée «évaluation»).

Les autorités de contrôle informent le candidat acquéreur de la date d'expiration de la période d'évaluation au moment de la délivrance de l'accusé de réception.

2.   Les autorités de contrôle peuvent, pendant la période d'évaluation, s'il y a lieu, et au plus tard le cinquantième jour ouvrable de la période d'évaluation, demander un complément d'information nécessaire pour mener à bien l'évaluation. Cette demande est faite par écrit et précise les informations complémentaires nécessaires.

Pendant la période comprise entre la date de la demande d'informations par les autorités de contrôle et la réception d'une réponse du candidat acquéreur à cette demande, la période d'évaluation est suspendue. Cette suspension ne peut excéder vingt jours ouvrables. Les autorités de contrôle ont la faculté de formuler d'autres demandes visant à recueillir des informations complémentaires ou des clarifications, mais ces demandes ne donnent pas lieu à une suspension de la période d'évaluation.

3.   Les autorités de contrôle peuvent porter la suspension visée au paragraphe 2, deuxième alinéa, à trente jours ouvrables si le candidat acquéreur:

. a) est établi hors de la Communauté ou relève d'une réglementation non communautaire; ou

. b) est une personne physique ou morale qui n'est pas soumise à un contrôle en vertu de la présente directive ou de la directive 85/611/CEE du Conseil du 20 décembre 1985 portant coordination des dispositions législatives, réglementaires et administratives concernant certains organismes de placement collectif en valeurs mobilières (OPCVM)(32)ou des directives 2004/39/CE ou 2006/48/CE.

4.   Si les autorités de contrôle décident, au terme de l'évaluation, de s'opposer à l'acquisition envisagée, elles en informent, par écrit, le candidat acquéreur, dans un délai de deux jours ouvrables et sans dépasser la période d'évaluation, en indiquant les motifs de cette décision. Sous réserve du droit national, un exposé approprié des motifs de la décision peut être rendu accessible au public à la demande du candidat acquéreur. Un État membre a, néanmoins, le droit d'autoriser l'autorité de contrôle à effectuer cette divulgation en l'absence d'une demande du candidat acquéreur.

5.   Si, au cours de la période d'évaluation, les autorités de contrôle ne s'opposent pas par écrit à l'acquisition envisagée, celle-ci est réputée approuvée.

6.   Les autorités de contrôle peuvent fixer un délai maximal pour la conclusion de l'acquisition envisagée et, le cas échéant, le proroger.

7.   Les États membres n'imposent pas, pour la notification aux autorités de contrôle et l'approbation par ces autorités d'acquisitions directes ou indirectes de droits de vote ou de parts de capital, des exigences plus contraignantes que celles prévues par la présente directive.

8.   La Commission arrête des mesures d'exécution précisant les ajustements des critères fixés à l'article 59, paragraphe 1, pour prendre en compte les évolutions futures et assurer une application uniforme des articles 57 à 63.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.