== Article 59

=== Évaluation

1.   En procédant à l'évaluation de la notification prévue à l'article 57, paragraphe 1, et des informations visées à l'article 58, paragraphe 2, les autorités de contrôle apprécient, afin de garantir une gestion saine et prudente de l'entreprise d'assurance ou de réassurance visée par l'acquisition envisagée et en tenant compte de l'influence probable du candidat acquéreur sur l'entreprise d'assurance ou de réassurance, le caractère approprié du candidat acquéreur et la solidité financière de l'acquisition envisagée en appliquant l'ensemble des critères suivants:

. a) la réputation du candidat acquéreur;

. b) la réputation et l'expérience de toute personne qui assurera la direction des activités de l'entreprise d'assurance ou de réassurance à la suite de l'acquisition envisagée;

. c) la solidité financière du candidat acquéreur, compte tenu notamment du type d'activités exercées et envisagées au sein de l'entreprise d'assurance ou de réassurance visée par l'acquisition envisagée;

. d) la capacité de l'entreprise d'assurance ou de réassurance de satisfaire et de continuer à satisfaire aux obligations prudentielles découlant de la présente directive et, le cas échéant, d'autres directives, notamment la directive 2002/87/CE, en particulier le point de savoir si le groupe auquel elle appartiendra possède une structure qui permet d'exercer un contrôle effectif, d'échanger réellement des informations entre les autorités de contrôle et de déterminer le partage des responsabilités entre les autorités de contrôle;

. e) l'existence de motifs raisonnables de soupçonner qu'une opération ou une tentative de blanchiment de capitaux ou de financement du terrorisme au sens de l'article 1erde la directive 2005/60/CE du Parlement européen et du Conseil du 26 octobre 2005 relative à la prévention de l'utilisation du système financier aux fins du blanchiment de capitaux et du financement du terrorisme(33)est en cours ou a eu lieu en rapport avec l'acquisition envisagée, ou que l'acquisition envisagée pourrait en augmenter le risque.

2.   Les autorités de contrôle ne peuvent s'opposer à l'acquisition envisagée que s'il existe des motifs raisonnables de le faire sur la base des critères fixés au paragraphe 1, ou si les informations fournies par le candidat acquéreur sont incomplètes.

3.   Les États membres n'imposent pas de conditions préalables en ce qui concerne le niveau de participation à acquérir, ni n'autorisent leurs autorités de contrôle à examiner l'acquisition envisagée du point de vue des besoins économiques du marché.

4.   Les États membres publient une liste spécifiant les informations nécessaires pour procéder à l'évaluation et devant être communiquées aux autorités de contrôle au moment de la notification visée à l'article 57, paragraphe 1. Les informations demandées sont proportionnées et adaptées à la nature du candidat acquéreur et de l'acquisition envisagée. Les États membres ne demandent pas d'informations qui ne sont pas pertinentes dans le cadre d'une évaluation prudentielle.

5.   Nonobstant l'article 58, paragraphes 1, 2 et 3, lorsque plusieurs acquisitions ou augmentations envisagées de participations qualifiées concernant la même entreprise d'assurance ou de réassurance ont été notifiées à l'autorité de contrôle, cette dernière traite les candidats acquéreurs d'une façon non discriminatoire.