== Article 219

=== Fréquence du calcul

1.   Le contrôleur du groupe veille à ce que les calculs visés à l'article 218, paragraphes 2 et 3, soient réalisés au moins une fois par an, soit par l'entreprise d'assurance ou de réassurance participante, soit par la société holding d'assurance.

Les données nécessaires à ce calcul et les résultats obtenus sont fournis au contrôleur du groupe par l'entreprise d'assurance ou de réassurance participante ou, lorsque le groupe n'est pas dirigé par une entreprise d'assurance ou de réassurance, par la société holding d'assurance ou l'entreprise du groupe désignée par le contrôleur du groupe après consultation des autres autorités de contrôle concernées et du groupe lui-même.

2.   L'entreprise d'assurance ou de réassurance et la société holding d'assurance surveillent en permanence le montant du capital de solvabilité requis du groupe. Lorsque le profil de risque du groupe s'écarte significativement des hypothèses qui sous-tendaient le dernier capital de solvabilité requis notifié par le groupe, ce capital doit être recalculé sans délai et notifié au contrôleur du groupe.

Lorsque des éléments semblent indiquer que le profil de risque du groupe a significativement changé depuis la date de la dernière notification du capital de solvabilité requis du groupe, le contrôleur du groupe peut exiger que ce capital soit recalculé.

Sous-section 2

Choix de la méthode de calcul et principes généraux