== Article 218

=== Contrôle de la solvabilité du groupe

1.   Le contrôle de la solvabilité du groupe est exercé conformément aux paragraphes 2 et 3 du présent article, à l'article 246 et au chapitre III.

2.   Dans le cas visé à l'article 213, paragraphe 2, point a), les États membres exigent des entreprises d'assurance ou de réassurance participantes qu'elles veillent à ce que le groupe dispose en permanence d'un montant de fonds propres éligibles au moins égal au capital de solvabilité requis du groupe calculé conformément aux sous-sections 2, 3 et 4.

3.   Dans le cas visé à l'article 213, paragraphe 2, point b), les États membres exigent des entreprises d'assurance ou de réassurance faisant partie d'un groupe qu'elles veillent à ce que le groupe dispose en permanence d'un montant de fonds propres éligibles au moins égal au capital de solvabilité requis du groupe calculé conformément à la sous-section 5.

4.   Les exigences visées aux paragraphes 2 et 3 sont soumises au contrôle prudentiel du contrôleur du groupe conformément au chapitre III. L'article 136 et l'article 138, paragraphes 1 à 4, s'appliquentmutatis mutandis.

5.   Dès que l'entreprise participante a constaté et informé le contrôleur du groupe que le capital de solvabilité requis du groupe n'est plus atteint, ou qu'il risque de ne plus l'être dans les trois mois à venir, le contrôleur du groupe en informe les autres autorités de contrôle au sein du collège des contrôleurs, qui analyse la situation du groupe.