== Article 121

=== Normes de qualité statistique

1.   Le modèle interne et, en particulier, le calcul de la distribution de probabilité prévisionnelle qui le sous-tendent satisfont aux critères fixés aux paragraphes 2 à 9.

2.   Les méthodes utilisées pour calculer la distribution de probabilité prévisionnelle sont fondées sur des techniques actuarielles et statistiques adéquates, applicables et pertinentes et elles sont cohérentes avec les méthodes utilisées pour calculer les provisions techniques.

Les méthodes utilisées pour calculer la distribution de probabilité prévisionnelle sont fondées sur des informations actuelles crédibles et sur des hypothèses réalistes.

Les entreprises d'assurance et de réassurance sont en mesure de justifier, auprès des autorités de contrôle, les hypothèses qui sous-tendent leur modèle interne.

3.   Les données utilisées aux fins du modèle interne sont exactes, exhaustives et appropriées.

Les entreprises d'assurance et de réassurance actualisent au moins une fois par an les séries de données qu'elles utilisent aux fins du calcul de la distribution de probabilité prévisionnelle.

4.   Aucune méthode particulière n'est prescrite pour le calcul de la distribution de probabilité prévisionnelle.

Indépendamment de la méthode de calcul retenue, la capacité du modèle interne à classer les risques est suffisante pour garantir qu'il est largement utilisé et qu'il joue un rôle important dans le système de gouvernance de l'entreprise d'assurance ou de réassurance concernée, et notamment dans son système de gestion des risques et ses processus décisionnels, ainsi que dans l'allocation de son capital conformément à l'article 120.

Le modèle interne couvre tous les risques importants auxquels l'entreprise d'assurance ou de réassurance concernée est exposée. Il couvre au minimum les risques répertoriés à l'article 101, paragraphe 4.

5.   Pour ce qui concerne les effets de diversification, les entreprises d'assurance et de réassurance peuvent tenir compte dans leur modèle interne des dépendances existant au sein de catégories de risques données, ainsi qu'entre catégories de risques, sous réserve que les autorités de contrôle jugent adéquat le système utilisé pour mesurer ces effets de diversification.

6.   Les entreprises d'assurance et de réassurance peuvent tenir pleinement compte de l'effet des techniques d'atténuation du risque dans leur modèle interne, pour autant que le risque de crédit et les autres risques découlant de l'utilisation des techniques d'atténuation du risque soient pris en considération de manière adéquate dans le modèle interne.

7.   Les entreprises d'assurance et de réassurance évaluent avec précision, dans leur modèle interne, les risques particuliers liés aux garanties financières et à toute option contractuelle lorsqu'ils ne sont pas négligeables. Elles évaluent également les risques liés aux options offertes au preneur, ainsi qu'aux options contractuelles qui sont offertes aux entreprises d'assurance et de réassurance. À cet effet, elles tiennent compte de l'impact que pourraient avoir d'éventuels changements des conditions financières et non financières sur l'exercice de ces options.

8.   Les entreprises d'assurance et de réassurance peuvent tenir compte, dans leur modèle interne, des décisions futures de gestion qu'elles pourraient raisonnablement mettre en œuvre dans des circonstances particulières.

Dans le cas prévu au premier alinéa, l'entreprise concernée tient compte du temps nécessaire à la mise en œuvre de ces décisions.

9.   Les entreprises d'assurance et de réassurance tiennent compte, dans leur modèle interne, de tous les paiements aux preneurs et aux bénéficiaires qu'elles s'attendent à devoir effectuer, que ces paiements soient ou non contractuellement garantis.