= Article 124

Normes de validation

Les entreprises d'assurance et de réassurance mettent en place un cycle régulier de validation de leur modèle, qui comprend un suivi du fonctionnement du modèle interne, un contrôle de l'adéquation permanente de ses spécifications et une confrontation des résultats qu'il produit aux données tirées de l'expérience.

Le processus de validation du modèle comporte la validation du modèle interne par un procédé statistique efficace permettant aux entreprises d'assurance et de réassurance de démontrer à leurs autorités de contrôle que les exigences de capital en résultant sont appropriées.

Les méthodes statistiques utilisées servent à vérifier le caractère approprié de la distribution de probabilité prévisionnelle par rapport non seulement à l'historique des pertes, mais aussi à toutes les données et informations nouvelles non négligeables y afférentes.

Le processus de validation du modèle comporte une analyse de la stabilité du modèle interne et, en particulier, un test de la sensibilité des résultats qu'il produit à une modification des hypothèses fondamentales qui le sous-tendent. Il comprend également une évaluation de l'exactitude, de l'exhaustivité et du caractère approprié des données utilisées dans le modèle interne.