= Article 4

Exclusion du champ d'application en raison de la taille

1.   Sans préjudice des articles 3 et 5 à 10, la présente directive ne s'applique pas à l'entreprise d'assurance qui remplit toutes les conditions suivantes:

. a) l'encaissement annuel de primes brutes émises par l'entreprise n'excède pas 5 000 000 EUR;

. b) le total des provisions techniques de l'entreprise, déduction non faite des créances découlant des contrats de réassurance et des véhicules de titrisation, visées à l'article 76, n'excède pas 25 000 000 EUR;

. c) lorsque l'entreprise appartient à un groupe, le total des provisions techniques du groupe, déduction non faite des créances découlant des contrats de réassurance et des véhicules de titrisation, n'excède pas 25 000 000 EUR;

. d) l'activité de l'entreprise ne comporte pas d'activités d'assurance ou de réassurance couvrant les risques de responsabilité civile, de crédit et de caution, sauf si ceux-ci constituent des risques accessoires au sens de l'article 16, paragraphe 1;

. e) l'activité de l'entreprise ne comporte pas d'opérations de réassurance qui soit excèdent500 000 EUR d'encaissement de primes brutes émises ou 2 500 000 EUR de provisions techniques, déduction non faite des créances découlant des contrats de réassurance et des véhicules de titrisation, soit représentent plus de 10 % de son encaissement de primes brutes émises ou de ses provisions techniques, déduction non faite des créances découlant des contrats de réassurance et des véhicules de titrisation.

2.   Si un des montants énoncés au paragraphe 1 est dépassé pendant trois années consécutives, la présente directive s'applique à partir de la quatrième année.

3.   Par dérogation au paragraphe 1, la présente directive s'applique à toutes les entreprises sollicitant un agrément en vue d'exercer des activités d'assurance ou de réassurance dont l'encaissement annuel des primes brutes émises ou le montant brut des provisions techniques, déduction non faite des créances découlant de contrats de réassurance et de véhicules de titrisation, dépasseront, selon les prévisions, un des montants énoncés au paragraphe 1 au cours des cinq années suivantes.

4.   La présente directive cesse de s'appliquer aux entreprises d'assurance dont l'autorité de contrôle a vérifié qu'elles réunissent toutes les conditions suivantes:

. a) aucun des seuils énoncés au paragraphe 1 n'a été dépassé pendant les trois années consécutives précédentes; et

. b) aucun des seuils énoncés au paragraphe 1 ne sera, selon les prévisions, dépassé au cours des cinq années à venir.

Le paragraphe 1 du présent article n'est pas applicable tant que l'entreprise d'assurance concernée exerce ses activités conformément aux articles 145 à 149.

5.   Les paragraphes 1 et 4 n'empêchent aucune entreprise de solliciter ou de conserver un agrément au titre de la présente directive.

Sous-section 2

Assurance non-vie