== Article 211

=== Véhicules de titrisation

1.   Les États membres autorisent l'établissement de véhicules de titrisation sur leur territoire, sous réserve d'un agrément préalable par les autorités de contrôle.

2.   Afin de garantir une approche harmonisée pour les véhicules de titrisation, la Commission arrête des mesures d'exécution dans les domaines suivants:

. a) champ de l'agrément;

. b) conditions obligatoires à inclure dans tous les contrats conclus;

. c) exigences de compétence et d'honorabilité visées à l'article 42 pour les personnes gérant le véhicule de titrisation;

. d) exigences de compétence et d'honorabilité pour les actionnaires ou associés détenant une participation qualifiée dans le véhicule de titrisation;

. e) procédures administratives et comptables saines, mécanismes de contrôle interne appropriés et exigences en matière de gestion des risques;

. f) exigences en matière comptable, prudentielle et d'informations statistiques;

. g) exigences de solvabilité.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive, y compris en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

3.   Les véhicules de titrisation agréés avant le 31 octobre 2012 sont soumis au droit de l'État membre qui a agréé le véhicule de titrisation. Toute nouvelle activité de ces véhicules de titrisation commencée après cette date est cependant soumise aux paragraphes 1 et 2.

TITRE III

CONTRÔLE DES ENTREPRISES D'ASSURANCE ET DE RÉASSURANCE FAISANT PARTIE D'UN GROUPE

CHAPITRE I

Contrôle de groupe: définitions, applicabilité, portée et niveaux

Section 1

Définitions