= Article 305

Dérogations et suppression des mesures restrictives

1.   Les États membres peuvent dispenser les entreprises d'assurance non-vie qui, au 31 janvier 1975, ne s'étaient pas conformées aux dispositions des articles 16 et 17 de la directive 73/239/CEE et qui, au 31 juillet 1978, n'atteignaient pas un encaissement annuel de primes ou de cotisations égal au sextuple du fonds minimum de garantie visé à l'article 17, paragraphe 2, de la directive 73/239/CEE, de l'obligation de constituer ce fonds avant la fin de l'exercice pour lequel les primes ou cotisations atteignent le sextuple de ce fonds. Au vu des résultats de l'examen prévu à l'article 298, paragraphe 2, le Conseil décide à l'unanimité, sur proposition de la Commission, à quel moment les États membres doivent supprimer cette dispense.

2.   Les entreprises d'assurance non-vie créées au Royaume-Uni par Royal Charter ou par private Act ou par special public Act peuvent poursuivre leurs activités sous la forme juridique selon laquelle elles étaient constituées au 31 juillet 1973, sans limitation de temps.

Les entreprises d'assurance vie créées au Royaume-Uni par Royal Charter ou par private Act ou par special public Act peuvent poursuivre leur activité sous la forme juridique selon laquelle elles étaient constituées au 15 mars 1979, sans limitation de temps.

Le Royaume-Uni dresse la liste des entreprises visées aux premier et deuxième alinéas et la communique aux autres États membres ainsi qu'à la Commission.

3.   Les sociétés enregistrées au Royaume-Uni au titre du Friendly Societies Act peuvent poursuivre les activités d'assurance sur la vie et d'épargne qu'elles exerçaient, conformément à leur objet social, au 15 mars 1979.

4.   À la demande des entreprises d'assurance non-vie qui satisfont aux obligations prévues par le titre I, chapitre VI, sections 2, 4 et 5, les États membres suppriment les mesures restrictives telles qu'hypothèques, dépôts et cautionnements.