== Article 215

=== Entreprise mère supérieure au niveau communautaire

1.   Lorsque l'entreprise d'assurance ou de réassurance participante ou la société holding d'assurance visée à l'article 213, paragraphe 2, points a) et b), est elle-même une entreprise filiale d'une autre entreprise d'assurance ou de réassurance ou d'une autre société holding d'assurance ayant son siège social dans la Communauté, les articles 218 à 258 ne s'appliquent qu'au niveau de l'entreprise d'assurance ou de réassurance ou société holding d'assurance mère supérieure ayant son siège social dans la Communauté.

2.   Lorsque l'entreprise d'assurance ou de réassurance ou société holding d'assurance mère supérieure ayant son siège social dans la Communauté, visée au paragraphe 1, est une entreprise filiale d'une entreprise assujettie à une surveillance complémentaire conformément à l'article 5, paragraphe 2, de la directive 2002/87/CE, le contrôleur du groupe peut, après consultation des autres autorités de contrôle concernées, décider de ne pas effectuer au niveau de cette entreprise mère supérieure le contrôle de la concentration de risques visé à l'article 244 ou le contrôle des transactions intragroupe visé à l'article 245 ou les deux.