= Article 217

Entreprise mère couvrant plusieurs États membres

1.   Lorsque les États membres autorisent leurs autorités de contrôle à arrêter la décision visée à l'article 216, ils les autorisent également à décider de conclure un accord avec des autorités de contrôle dans les autres États membres où se trouve une autre entreprise mère supérieure liée au niveau national, en vue d'exercer un contrôle du groupe au niveau d'un sous-groupe couvrant plusieurs États membres.

Lorsque les autorités de contrôle concernées ont conclu un accord conformément au premier alinéa, aucun contrôle du groupe n'est effectué au niveau des entreprises mères supérieures visées à l'article 216 qui se trouvent dans des États membres différents de l'État membre où est situé le sous-groupe visé au premier alinéa du présent paragraphe.

2.   L'article 216, paragraphes 2 à 6, s'appliquemutatis mutandis.

3.   La Commission peut arrêter des mesures d'exécution précisant les circonstances dans lesquelles la décision visée au paragraphe 1 peut être prise.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

CHAPITRE II

Situation financière

Section 1

Solvabilité du groupe

Sous-section 1

Dispositions générales