= Article 216

Entreprise mère supérieure au niveau national

1.   Lorsque l'entreprise d'assurance ou de réassurance participante ou la société holding d'assurance ayant son siège social dans la Communauté, visée à l'article 213, paragraphe 2, points a) et b), n'a pas son siège social dans le même État membre que l'entreprise mère supérieure au niveau communautaire visée à l'article 215, les États membres peuvent autoriser leurs autorités de contrôle à décider, après consultation du contrôleur du groupe et de cette entreprise mère supérieure au niveau communautaire, d'assujettir au contrôle du groupe l'entreprise d'assurance ou de réassurance ou société holding d'assurance mère supérieure au niveau national.

Dans ce cas, l'autorité de contrôle explique sa décision au contrôleur du groupe et à l'entreprise mère supérieure au niveau communautaire.

Les articles 218 à 258 s'appliquentmutatis mutandis, sous réserve des dispositions des paragraphes 2 à 6.

2.   L'autorité de contrôle peut limiter le contrôle de groupe de l'entreprise mère supérieure au niveau national à une ou plusieurs sections du chapitre II.

3.   Lorsque l'autorité de contrôle décide d'appliquer les dispositions de la section I du chapitre II à l'entreprise mère supérieure au niveau national, le choix de la méthode effectué conformément à l'article 220 par le contrôleur du groupe en ce qui concerne l'entreprise mère supérieure au niveau communautaire visée à l'article 215 est considéré comme déterminant et est appliqué par l'autorité de contrôle dans l'État membre concerné.

4.   Lorsque l'autorité de contrôle décide d'appliquer à l'entreprise mère supérieure au niveau national les dispositions de la section 1 du chapitre II et que l'entreprise mère supérieure au niveau communautaire visée à l'article 215 a obtenu, conformément à l'article 231 ou à l'article 233, paragraphe 5, l'autorisation de calculer sur la base d'un modèle interne le capital de solvabilité requis du groupe et le capital de solvabilité requis des entreprises d'assurance et de réassurance faisant partie du groupe, cette décision est considérée comme déterminante et est appliquée par l'autorité de contrôle dans l'État membre concerné.

Dans ce cas, lorsque l'autorité de contrôle considère que le profil de risque de l'entreprise mère supérieure au niveau national s'écarte significativement du modèle interne approuvé au niveau communautaire, elle peut décider d'imposer à cette entreprise, en conséquence de l'application de ce modèle et aussi longtemps que cette entreprise ne répond pas de manière satisfaisante aux préoccupations de l'autorité de contrôle, une exigence de capital supplémentaire en ce qui concerne le capital de solvabilité requis du groupe de cette entreprise ou, dans des circonstances exceptionnelles, lorsque cette exigence de capital supplémentaire serait inappropriée, exiger de cette entreprise qu'elle calcule le capital de solvabilité requis du groupe sur la base de la formule standard.

L'autorité de contrôle explique ces décisions à l'entreprise et au contrôleur du groupe.

5.   Lorsque l'autorité de contrôle décide d'appliquer à l'entreprise mère supérieure au niveau national les dispositions de la section 1 du chapitre II, cette entreprise n'est pas autorisée à demander, conformément aux articles 236 ou 243, l'autorisation d'assujettir l'une quelconque de ses filiales aux articles 238 et 239.

6.   Lorsque les États membres autorisent leurs autorités de contrôle à prendre la décision visée au paragraphe 1, ils prévoient qu'aucune de ces décisions ne peut être arrêtée ou maintenue lorsque l'entreprise mère supérieure au niveau national est une filiale de l'entreprise mère supérieure au niveau communautaire visée à l'article 215 et que cette dernière a obtenu, conformément aux articles 237 ou 243, l'autorisation d'assujettir cette filiale aux articles 238 et 239.

7.   La Commission peut arrêter des mesures d'exécution précisant les circonstances dans lesquelles la décision visée au paragraphe 1 peut être prise.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.