= Article 212

Définitions

1.   Aux fins du présent titre, on entend par:

. a) «entreprise participante»: une entreprise qui est soit une entreprise mère, soit une autre entreprise qui détient une participation, soit une entreprise liée à une autre entreprise par une relation au sens de l'article 12, paragraphe 1, de la directive 83/349/CEE;

. b) «entreprise liée»: une entreprise qui est soit une entreprise filiale, soit une autre entreprise dans laquelle une participation est détenue, soit une entreprise liée à une autre entreprise par une relation au sens de l'article 12, paragraphe 1, de la directive 83/349/CEE;

. c) «groupe»: un groupe d'entreprises:i)soit composé d'une entreprise participante, de ses filiales et des entités dans lesquelles l'entreprise participante ou ses filiales détiennent une participation, ainsi que des entreprises liées entre elles par une relation au sens de l'article 12, paragraphe 1, de la directive 83/349/CEE;ii)soit fondé sur l'établissement, par voie contractuelle ou sous une autre forme, de relations financières fortes et durables entre ces entreprises et qui peut inclure des mutuelles ou des associations de type mutuel, à condition:—qu'une de ces entreprises exerce effectivement, au moyen d'une coordination centralisée, une influence dominante sur les décisions, y compris les décisions financières, des autres entreprises faisant partie du groupe, et—que l'établissement et la suppression desdites relations, aux fins du présent titre, soient soumis à l'approbation préalable du contrôleur du groupe;l'entreprise qui exerce la coordination centralisée étant considérée comme l'entreprise mère et les autres entreprises comme des filiales;

. i) soit composé d'une entreprise participante, de ses filiales et des entités dans lesquelles l'entreprise participante ou ses filiales détiennent une participation, ainsi que des entreprises liées entre elles par une relation au sens de l'article 12, paragraphe 1, de la directive 83/349/CEE;

. ii) soit fondé sur l'établissement, par voie contractuelle ou sous une autre forme, de relations financières fortes et durables entre ces entreprises et qui peut inclure des mutuelles ou des associations de type mutuel, à condition:—qu'une de ces entreprises exerce effectivement, au moyen d'une coordination centralisée, une influence dominante sur les décisions, y compris les décisions financières, des autres entreprises faisant partie du groupe, et—que l'établissement et la suppression desdites relations, aux fins du présent titre, soient soumis à l'approbation préalable du contrôleur du groupe;l'entreprise qui exerce la coordination centralisée étant considérée comme l'entreprise mère et les autres entreprises comme des filiales;

. — qu'une de ces entreprises exerce effectivement, au moyen d'une coordination centralisée, une influence dominante sur les décisions, y compris les décisions financières, des autres entreprises faisant partie du groupe, et

. — que l'établissement et la suppression desdites relations, aux fins du présent titre, soient soumis à l'approbation préalable du contrôleur du groupe;

. d) «contrôleur du groupe»: l'autorité de contrôle chargée de contrôler un groupe, déterminée conformément à l'article 247;

. e) «collège des contrôleurs»: une structure permanente, mais souple, de coopération et de coordination entre les autorités de contrôle des États membres concernés;

. f) «société holding d'assurance»: une entreprise mère qui n'est pas une compagnie financière holding mixte au sens de la directive 2002/87/CE et dont l'activité principale consiste à acquérir et à détenir des participations dans des entreprises filiales lorsque ces entreprises filiales sont exclusivement ou principalement des entreprises d'assurance ou de réassurance, ou des entreprises d'assurance ou de réassurance de pays tiers, l'une au moins de ces entreprises filiales étant une entreprise d'assurance ou de réassurance;

. g) «société holding mixte d'assurance»: une entreprise mère, autre qu'une entreprise d'assurance, qu'une entreprise d'assurance d'un pays tiers, qu'une entreprise de réassurance, qu'une entreprise de réassurance d'un pays tiers, qu'une société holding d'assurance ou qu'une compagnie financière holding mixte au sens de la directive 2002/87/CE, qui compte parmi ses filiales au moins une entreprise d'assurance ou de réassurance.

2.   Aux fins du présent titre, les autorités de contrôle considèrent également comme une entreprise mère toute entreprise qui, selon elles, exerce effectivement une influence dominante sur une autre entreprise.

Elles considèrent également comme une entreprise filiale toute entreprise sur laquelle, selon elles, une entreprise mère exerce effectivement une influence dominante.

Elles considèrent aussi comme une participation le fait de détenir, directement ou indirectement, des droits de vote ou du capital dans une entreprise sur laquelle, selon elles, une influence notable est effectivement exercée.

Section 2

Applicabilité et portée