== Article 96

=== Classement des éléments des fonds propres spécifiques à l'assurance

Sans préjudice de l'article 95 et de l'article 97, paragraphe 1, point a), les classements suivants sont appliqués aux fins de la présente directive:

. 1) les fonds excédentaires relevant de l'article 91, paragraphe 2, sont classés au niveau 1;

. 2) les lettres de crédit et les garanties détenues en fiducie par un fiduciaire indépendant au bénéfice de créanciers d'assurance et fournies par des établissements de crédit agréés conformément à la directive 2006/48/CE sont classées au niveau 2;

. 3) toute créance future que les mutuelles ou associations de type mutuel à cotisations variables de propriétaires de navires, qui assurent uniquement les risques classés sous les branches 6, 12 et 17 de la partie A de l'annexe I, peuvent détenir sur leurs membres par voie de rappel de cotisations durant les douze mois à venir, est classée au niveau 2.

Conformément à l'article 94, paragraphe 2, deuxième alinéa, toute créance future que les mutuelles ou associations de type mutuel à cotisations variables peuvent détenir sur leurs membres par voie de rappel de cotisations durant les douze mois à venir et qui n'est pas couverte par le premier alinéa, point 3, est classée au niveau 2 lorsqu'elle présente, en substance, les caractéristiques exposées à l'article 93, paragraphe 1, points a) et b), compte tenu des facteurs visés à l'article 93, paragraphe 2.