= Article 214

Portée du contrôle de groupe

1.   L'exercice du contrôle du groupe conformément à l'article 213 n'implique pas que les autorités de contrôle sont tenues d'exercer un contrôle sur l'entreprise d'assurance d'un pays tiers, l'entreprise de réassurance d'un pays tiers, la société holding d'assurance ou la société holding mixte d'assurance considérées individuellement, sans préjudice de l'article 257 en ce qui concerne les sociétés holding d'assurance.

2.   Le contrôleur du groupe peut décider, au cas par cas, de ne pas inclure une entreprise dans le contrôle de groupe visé à l'article 213:

. a) lorsque l'entreprise est située dans un pays tiers où des obstacles de nature juridique empêchent le transfert des informations nécessaires, sans préjudice de l'article 229;

. b) lorsque l'entreprise à inclure ne présente qu'un intérêt négligeable au regard des objectifs du contrôle de groupe; ou

. c) lorsque l'inclusion de l'entreprise est inappropriée ou pourrait constituer une source de confusion, au regard des objectifs du contrôle de groupe.

Cependant, lorsque plusieurs entreprises du même groupe, considérées individuellement, peuvent être exclues sur la base du premier alinéa, point b), il y a lieu de les inclure dès lors que, collectivement, elles présentent un intérêt non négligeable.

Lorsque, en vertu du premier alinéa, point b) ou c), le contrôleur du groupe estime qu'une entreprise d'assurance ou de réassurance ne devrait pas être incluse dans le contrôle du groupe, il consulte les autres autorités de contrôle concernées avant d'arrêter une décision.

Lorsque, en vertu du premier alinéa, point b) ou c), le contrôleur du groupe n'inclut pas une entreprise d'assurance ou de réassurance dans le contrôle du groupe, les autorités de contrôle de l'État membre où cette entreprise est située peuvent exiger de l'entreprise qui se trouve à la tête du groupe qu'elle leur fournisse toute information de nature à faciliter le contrôle de l'entreprise d'assurance ou de réassurance concernée.

Section 3

Niveaux