== Article 308

=== Droits acquis par les entreprises de réassurance existantes

1.   Les entreprises de réassurance relevant de la présente directive, qui ont été agréées ou habilitées à exercer des activités de réassurance conformément aux dispositions de l'État membre où elles ont leur siège social avant le 10 décembre 2005, sont réputées agréées conformément à l'article 14.

Toutefois, elles sont tenues de se conformer aux dispositions de la présente directive relatives à l'exercice de l'activité de réassurance ainsi qu'aux exigences énoncées à l'article 18, paragraphe 1, point b) et points d) à g), aux articles 19, 20 et 24 et au titre I, chapitre VI, sections 2, 3 et 4.

2.   Les États membres peuvent accorder aux entreprises de réassurance visées au paragraphe 1 qui, au 10 décembre 2005, ne respectaient pas les dispositions de l'article 18, paragraphe 1, point b), des articles 19 et 20 et du titre I, chapitre VI, sections 2, 3 et 4, un délai courant jusqu'au 10 décembre 2008 pour s'y conformer.

CHAPITRE II

Dispositions finales