= Article 280

Publication des décisions relatives aux procédures de liquidation

1.   L'autorité compétente, le liquidateur ou toute personne désignée à cet effet par l'autorité compétente assurent la publicité de la décision d'ouverture de la procédure de liquidation conformément aux modalités prévues dans l'État membre d'origine en matière de publication et, en outre, publient auJournal officiel de l'Union européenneun extrait de la décision de liquidation.

Les autorités de contrôle de tous les autres États membres qui ont été informées de la décision d'ouverture de la procédure de liquidation conformément à l'article 273, paragraphe 3, peuvent assurer la publication de cette décision sur leur territoire de la manière qu'elles jugent appropriée.

2.   La publication visée au paragraphe 1 indique l'autorité compétente de l'État membre d'origine, le droit applicable ainsi que le liquidateur désigné. Elle est assurée dans la langue officielle ou dans une des langues officielles de l'État membre dans lequel l'information est publiée.