== Article 276

=== Registre spécial

1.   Toute entreprise d'assurance tient, à son siège social, un registre spécial des actifs représentant les provisions techniques calculées et placées conformément au droit de l'État membre d'origine.

2.   Lorsqu'une entreprise d'assurance exerce simultanément des activités d'assurance vie et d'assurance non-vie, elle tient, à son siège social, un registre distinct pour chacune de ces activités.

Toutefois, lorsqu'un État membre autorise des entreprises d'assurance à exercer des activités d'assurance vie et à couvrir les risques énumérés dans les branches 1 et 2 de la partie A de l'annexe I, il peut prévoir que ces entreprises d'assurance tiennent un registre unique pour l'ensemble de leurs activités.

3.   À tout moment, la valeur totale des actifs inscrits, déterminée conformément au droit applicable dans l'État membre d'origine, doit être au moins égale à la valeur des provisions techniques.

4.   Lorsqu'un actif inscrit au registre est grevé d'un droit réel, au profit d'un créancier ou d'un tiers, qui a pour résultat de rendre indisponible pour la couverture des engagements une partie de la valeur de cet actif, il est fait état de cette situation dans le registre et il n'est pas tenu compte du montant non disponible dans la valeur totale visée au paragraphe 3.

5.   En cas de liquidation de l'entreprise d'assurance, le sort d'un actif dans le cadre de l'option prévue à l'article 275, paragraphe 1, point a), est déterminé, sauf lorsque les articles 286, 287 ou 288 s'appliquent audit actif, par la législation de l'État membre d'origine:

. a) lorsque l'actif utilisé pour couvrir les provisions techniques est grevé d'un droit réel au profit d'un créancier ou d'un tiers, sans remplir les conditions énoncées au paragraphe 4;

. b) lorsqu'un tel actif est soumis à une réserve de propriété en faveur d'un créancier ou d'un tiers; ou

. c) lorsqu'un créancier est habilité à invoquer la compensation de sa créance avec celle de l'entreprise d'assurance.

6.   Une fois la procédure de liquidation ouverte, la composition des actifs inscrits au registre conformément aux paragraphes 1 à 5 n'est plus modifiée et aucune modification, autre que la correction d'erreurs purement matérielles, ne peut être apportée aux registres sauf autorisation de l'autorité compétente.

Cependant, les liquidateurs ajoutent auxdits actifs leur produit financier ainsi que le montant des primes pures encaissées dans la branche d'assurance concernée entre l'ouverture de la procédure de liquidation et le paiement des créances d'assurance ou jusqu'au transfert de portefeuille.

7.   Lorsque le produit de la réalisation des actifs est inférieur à leur évaluation dans les registres, les liquidateurs en donnent justification aux autorités de contrôle des États membres d'origine.