= Article 281

Information des créanciers connus

1.   Lorsqu'une procédure de liquidation est ouverte, les autorités compétentes de l'État membre d'origine, le liquidateur ou toute personne désignée à cet effet par les autorités compétentes informent sans délai et individuellement par une note écrite chaque créancier connu qui a sa résidence habituelle, son domicile ou son siège social dans un autre État membre.

2.   La note visée au paragraphe 1 porte sur les délais à observer, les sanctions prévues quant à ces délais, l'organe ou l'autorité habilité à recevoir la production des créances ou les observations relatives aux créances et toute autre mesure.

La note indique également si les créanciers dont la créance est privilégiée ou garantie par une sûreté réelle doivent produire leur créance.

Dans le cas des créances d'assurance, la note indique en outre les effets généraux de la procédure de liquidation sur les contrats d'assurance, en particulier la date à laquelle les contrats d'assurance ou les opérations cessent de produire leurs effets ainsi que les droits et obligations de l'assuré concernant le contrat ou l'opération.