== Article 274

=== Droit applicable

1.   La décision d'ouvrir une procédure de liquidation d'une entreprise d'assurance, la procédure de liquidation et leurs effets sont régis par le droit applicable dans l'État membre d'origine, sauf dispositions contraires des articles 285 à 292.

2.   Le droit de l'État membre d'origine détermine au moins:

. a) les actifs qui font l'objet du dessaisissement et le sort des actifs acquis par l'entreprise d'assurance ou dont la propriété lui a été transférée après l'ouverture de la procédure de liquidation;

. b) les pouvoirs respectifs de l'entreprise d'assurance et du liquidateur;

. c) les conditions d'opposabilité d'une compensation;

. d) les effets de la procédure de liquidation sur les contrats en cours auxquels l'entreprise d'assurance est partie;

. e) les effets de la procédure de liquidation sur les poursuites individuelles par les créanciers, à l'exception des instances en cours visées à l'article 292;

. f) les créances à produire au passif de l'entreprise d'assurance et le sort des créances nées après l'ouverture de la procédure de liquidation;

. g) les règles concernant la production, la vérification et l'admission des créances;

. h) les règles de distribution du produit de la réalisation des actifs, le rang des créances et les droits des créanciers qui ont été partiellement désintéressés après l'ouverture de la procédure de liquidation en vertu d'un droit réel ou par l'effet d'une compensation;

. i) les conditions et les effets de la clôture de la procédure de liquidation, notamment par concordat;

. j) les droits des créanciers après la clôture de la procédure de liquidation;

. k) la partie devant supporter les frais et dépens de la procédure de liquidation; et

. l) les règles relatives à la nullité, à l'annulation ou à l'inopposabilité des actes juridiques préjudiciables à l'ensemble des créanciers.