= Article 282

Droit de produire des créances

1.   Tout créancier, y compris les autorités publiques des États membres, qui a sa résidence habituelle, son domicile ou son siège social dans un État membre autre que l'État membre d'origine, a le droit de produire ses créances ou de présenter par écrit des observations relatives à ses créances.

2.   Les créances de tous les créanciers visés au paragraphe 1 bénéficient du même traitement et du même rang que les créances de nature équivalente éventuellement produites par les créanciers ayant leur résidence habituelle, leur domicile ou leur siège social dans l'État membre d'origine. Les autorités compétentes n'opèrent donc aucune discrimination au niveau de la Communauté.

3.   À l'exception des cas où le droit de l'État membre d'origine en dispose autrement, le créancier envoie à l'autorité compétente une copie des pièces justificatives, s'il en existe, et indique:

. a) la nature et le montant de la créance;

. b) la date à laquelle la créance est née;

. c) s'il revendique, pour cette créance, un privilège, une sûreté réelle ou une réserve de propriété;

. d) le cas échéant, quels sont les actifs sur lesquels porte sa sûreté.

Il n'est pas nécessaire d'indiquer la priorité accordée aux créances d'assurance au titre de l'article 275.