= Article 275

Sort des créances d'assurance

1.   Les États membres veillent à ce que les créances d'assurance soient prioritaires par rapport à d'autres créances sur l'entreprise d'assurance d'une ou de chacune des deux manières suivantes:

. a) en ce qui concerne les actifs représentatifs des provisions techniques, les créances d'assurance bénéficient d'une priorité absolue par rapport à toute autre créance sur l'entreprise d'assurance; ou

. b) en ce qui concerne l'ensemble des actifs de l'entreprise d'assurance, les créances d'assurance bénéficient d'une priorité par rapport à toute autre créance sur l'entreprise d'assurance, avec comme seules exceptions possibles:i)des créances détenues par les membres du personnel en raison de leur qualité de salariés;ii)des créances détenues par des organismes publics au titre de l'impôt;iii)des créances détenues par les régimes de sécurité sociale;iv)des créances sur des actifs grevés de droits réels.

. i) des créances détenues par les membres du personnel en raison de leur qualité de salariés;

. ii) des créances détenues par des organismes publics au titre de l'impôt;

. iii) des créances détenues par les régimes de sécurité sociale;

. iv) des créances sur des actifs grevés de droits réels.

2.   Sans préjudice du paragraphe 1, les États membres peuvent prévoir que la totalité ou une partie des dépens résultant de la procédure de liquidation, tels que définis par leur droit national, bénéficient d'une priorité par rapport aux créances d'assurance.

3.   Les États membres qui ont choisi l'option prévue au paragraphe 1, point a), exigent des entreprises d'assurance qu'elles créent et tiennent à jour un registre spécial, conformément à l'article 276.