= Article 273

Ouverture de la procédure de liquidation et information des autorités de contrôle

1.   Seules les autorités compétentes de l'État membre d'origine sont habilitées à prendre une décision concernant l'ouverture d'une procédure de liquidation à l'égard d'une entreprise d'assurance, y compris pour ses succursales dans d'autres États membres. Cette décision peut être prise en l'absence ou à la suite de l'adoption de mesures d'assainissement.

2.   Une décision concernant l'ouverture d'une procédure de liquidation d'une entreprise d'assurance, y compris de ses succursales dans d'autres États membres, adoptée conformément à la législation de l'État membre d'origine, est reconnue, sans aucune autre formalité, dans toute la Communauté et y produit ses effets dès que la décision produit ses effets dans l'État membre d'ouverture de la procédure.

3.   Les autorités compétentes de l'État membre d'origine informent d'urgence les autorités de contrôle de cet État membre de la décision d'ouvrir une procédure de liquidation, si possible avant l'ouverture de cette procédure ou, à défaut, immédiatement après.

Les autorités de contrôle de l'État membre d'origine informent d'urgence les autorités de contrôle de tous les autres États membres de la décision d'ouvrir une procédure de liquidation, y compris des effets concrets que pourrait avoir cette procédure.