= Article 283

Langues et formulaire

1.   Les informations figurant dans la note visée à l'article 281, paragraphe 1, sont fournies dans la langue officielle de l'État membre d'origine ou l'une des langues officielles de cet État.

Un formulaire portant, dans toutes les langues officielles de l'Union européenne, l'un des titres suivants est utilisé à cet effet:

. a) «Invitation à produire une créance. Délais à respecter»; ou

. b) lorsque le droit de l'État membre d'origine prévoit la présentation d'observations relatives aux créances, «Invitation à présenter des observations relatives à une créance. Délais à respecter».

Cependant, lorsqu'un créancier connu détient une créance d'assurance, les informations figurant dans la note visée à l'article 281, paragraphe 1, sont fournies dans la langue officielle de l'État membre dans lequel celui-ci a sa résidence habituelle, son domicile ou son siège social ou dans l'une des langues officielles de cet État.

2.   Le créancier qui a sa résidence habituelle, son domicile ou son siège social dans un État membre autre que l'État membre d'origine peut produire sa créance, ou présenter des observations relatives à sa créance, dans la langue officielle ou l'une des langues officielles de cet autre État membre.

Cependant, dans ce cas, la production de sa créance ou la présentation des observations sur sa créance, selon le cas, doit porter le titre «Production de créance» ou «Présentation d'observations relatives aux créances» dans la langue officielle de l'État membre d'origine ou l'une des langues officielles de cet État.