= Article 135

Mesures d'exécution

1.   Afin de garantir l'application uniforme de la présente directive, la Commission peut arrêter des mesures d'exécution prévoyant des exigences qualitatives dans les domaines suivants:

. a) l'identification, la mesure, le suivi, la gestion et la déclaration des risques découlant des investissements, en relation avec l'article 132, paragraphe 2, premier alinéa;

. b) l'identification, la mesure, le suivi, la gestion et la déclaration des risques particuliers découlant des investissements réalisés dans des instruments dérivés et dans les actifs visés à l'article 132, paragraphe 4, deuxième alinéa.

2.   Afin de garantir une cohérence entre les secteurs et d'éliminer les divergences d'intérêts entre, d'une part, les sociétés qui «reconditionnent» les prêts dans des valeurs mobilières négociables et d'autres instruments financiers (initiateurs) et, d'autre part, les entreprises d'assurance ou de réassurance qui investissent dans ces valeurs ou ces instruments, la Commission arrête des mesures d'exécution fixant:

. a) les exigences que l'initiateur doit respecter pour qu'une entreprise d'assurance ou de réassurance soit autorisée à investir dans ces valeurs mobilières ou instruments, émis après le 1erjanvier 2011, notamment les exigences visant à garantir que l'initiateur conserve un intérêt économique net non inférieur à 5 %;

. b) les exigences qualitatives que doivent respecter les entreprises d'assurance ou de réassurance investissant dans ces valeurs mobilières ou instruments.

3.   Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

CHAPITRE VII

Entreprises d'assurance et de réassurance en difficulté ou en situation irrégulière