== Article 132

=== Principe de la «personne prudente»

1.   Les États membres veillent à ce que les entreprises d'assurance et de réassurance investissent tous leurs actifs conformément au principe de la «personne prudente», comme indiqué aux paragraphes 2 à 4.

2.   Pour l'ensemble du portefeuille d'actifs, les entreprises d'assurance et de réassurance n'investissent que dans des actifs et instruments présentant des risques qu'elles peuvent identifier, mesurer, suivre, gérer, contrôler et déclarer de manière adéquate ainsi que prendre en compte de manière appropriée dans l'évaluation de leur besoin global de solvabilité conformément à l'article 45, paragraphe 1, deuxième alinéa, point a).

Tous les actifs, et en particulier les actifs couvrant le minimum de capital requis et le capital de solvabilité requis, sont investis de façon à garantir la sécurité, la qualité, la liquidité et la rentabilité de l'ensemble du portefeuille. En outre, la localisation de ces actifs est telle qu'elle garantit leur disponibilité.

Les actifs détenus aux fins de la couverture des provisions techniques sont également investis d'une façon adaptée à la nature et à la durée des engagements d'assurance et de réassurance. Ils sont investis dans le meilleur intérêt de tous les preneurs et de tous les bénéficiaires, compte tenu de tout objectif publié.

En cas de conflit d'intérêts, les entreprises d'assurance, ou les entités qui gèrent leur portefeuille d'actifs, veillent à ce que l'investissement soit réalisé au mieux des intérêts des preneurs et des bénéficiaires.

3.   Sans préjudice du paragraphe 2, pour les actifs détenus en représentation des contrats d'assurance vie dans le cadre desquels le risque d'investissement est supporté par le preneur, les deuxième, troisième et quatrième alinéas du présent paragraphe sont applicables.

Lorsque les prestations prévues par un contrat sont directement liées à la valeur de parts d'un OPCVM au sens de la directive 85/611/CEE ou à la valeur d'actifs contenus dans un fonds interne détenu par l'entreprise d'assurance, généralement divisé en parts, les provisions techniques concernant ces prestations doivent être représentées le plus étroitement possible par ces parts ou, lorsque des parts ne sont pas établies, par ces actifs.

Lorsque les prestations prévues par un contrat sont directement liées à un indice d'actions ou à une valeur de référence autre que celles visées au deuxième alinéa, les provisions techniques afférentes à ces prestations doivent être représentées aussi étroitement que possible soit par les parts réputées représenter la valeur de référence, soit, lorsque des parts ne sont pas établies, par des actifs d'une sûreté et d'une négociabilité appropriées correspondant le plus étroitement possible à ceux sur lesquels se fonde la valeur de référence en question.

Lorsque les prestations visées aux deuxième et troisième alinéas comprennent une garantie de performance financière ou toute autre prestation garantie, les actifs détenus pour couvrir les provisions techniques supplémentaires correspondantes sont soumis aux dispositions du paragraphe 4.

4.   Sans préjudice du paragraphe 2, pour les actifs autres que ceux relevant du paragraphe 3, les deuxième à cinquième alinéas du présent paragraphe sont applicables.

L'utilisation d'instruments dérivés est possible dans la mesure où ils contribuent à réduire les risques ou favorisent une gestion efficace du portefeuille.

Les investissements et les actifs qui ne sont pas admis à la négociation sur un marché financier réglementé sont maintenus à des niveaux prudents.

Les actifs font l'objet d'une diversification appropriée de façon à éviter une dépendance excessive vis-à-vis d'un actif, d'un émetteur ou d'un groupe d'entreprises donnés ou d'une zone géographique donnée et à éviter un cumul excessif de risques dans l'ensemble du portefeuille.

Les investissements dans des actifs émis par un même émetteur ou par des émetteurs appartenant à un même groupe n'exposent pas les entreprises d'assurance à une concentration excessive de risques.