= Article 309

Transposition

1.   Les États membres mettent en vigueur les dispositions législatives, réglementaires et administratives nécessaires pour se conformer aux articles 4, 10, 13, 14, 18, 23, 26 à 32, 34 à 49, 51 à 55, 67, 68, 71, 72, 74 à 85, 87 à 91, 93 à 96, 98, 100 à 110, 112, 113, 115 à 126, 128, 129, 131 à 134, 136 à 142, 144, 146, 148, 162 à 167, 172, 173, 178, 185, 190, 192, 210 à 233, 235 à 240, 243 à 258, 260 à 263, 265, 266, 303 et 304 ainsi qu'aux annexes III et IV au plus tard le 31 octobre 2012.

Lorsque les États membres adoptent ces dispositions, celles-ci contiennent une référence à la présente directive ou sont accompagnées d'une telle référence lors de leur publication officielle. Elles contiennent également une mention précisant que les références faites, dans les dispositions législatives, réglementaires et administratives existantes, aux directives abrogées par la présente directive s'entendent comme faites à la présente directive. Les modalités de cette référence et la formulation de cette mention sont arrêtées par les États membres.

2.   Les États membres communiquent à la Commission le texte des dispositions essentielles de droit national qu'ils adoptent dans le domaine régi par la présente directive.