= Article 232

Exigence de capital supplémentaire relative au groupe

Pour déterminer si le capital de solvabilité requis du groupe sur une base consolidée reflète de manière appropriée le profil de risque du groupe, le contrôleur du groupe accorde une attention particulière à tout cas où les circonstances visées à l'article 37, paragraphe 1, points a) à c), sont susceptibles de se présenter au niveau du groupe et notamment aux cas où:

. a) un risque spécifique existant au niveau du groupe ne serait, du fait qu'il est difficilement quantifiable, pas suffisamment pris en compte par la formule standard ou par le modèle interne utilisé;

. b) une exigence de capital supplémentaire s'ajoutant à leur capital de solvabilité requis est imposée aux entreprises d'assurance ou de réassurance liées, par les autorités de contrôle concernées, en application de l'article 37 et de l'article 231, paragraphe 7.

Lorsque le profil de risque du groupe n'est pas suffisamment pris en compte, une exigence de capital supplémentaire s'ajoutant au capital de solvabilité requis du groupe sur une base consolidée peut être imposée.

L'article 37, paragraphes 1 à 5, ainsi que les mesures d'exécution arrêtées en vertu de l'article 37, paragraphe 6, s'appliquentmutatis mutandis.