== Article 231

=== Modèle interne du groupe

1.   Dans le cas où une entreprise d'assurance ou de réassurance et ses entreprises liées, ou l'ensemble des entreprises liées d'une société holding d'assurance, demandent l'autorisation de calculer, sur la base d'un modèle interne, le capital de solvabilité requis du groupe sur une base consolidée et le capital de solvabilité requis des entreprises d'assurance et de réassurance du groupe, les autorités de contrôle concernées coopèrent pour décider d'accorder ou non cette autorisation et, le cas échéant, pour en définir les conditions.

La demande visée au premier alinéa est adressée au contrôleur du groupe.

Le contrôleur du groupe informe sans délai les autres autorités de contrôle concernées.

2.   Les autorités de contrôle concernées font tout ce qui est en leur pouvoir pour parvenir à une décision conjointe sur la demande dans un délai de six mois à compter de la réception de la demande complète par le contrôleur du groupe.

Le contrôleur du groupe communique sans délai la demande complète aux autres autorités de contrôle concernées.

3.   Pendant la période visée au paragraphe 2, le contrôleur du groupe et chacune des autres autorités de contrôle concernées peuvent consulter le CECAPP. Ce dernier est aussi consulté à la demande de l'entreprise participante.

Lorsque le CECAPP est consulté, toutes les autorités de contrôle concernées en sont informées et la période visée au paragraphe 2 est prolongée de deux mois.

4.   Lorsque le CECAPP n'a pas été consulté conformément au paragraphe 3, premier alinéa, et à défaut d'une décision conjointe des autorités de contrôle concernées dans les six mois suivant la date de réception de la demande complète par le contrôleur du groupe, le contrôleur du groupe demande au CECAPP, dans un nouveau délai de deux mois, de transmettre son avis à toutes les autorités de contrôle concernées. Le contrôleur du groupe prend une décision dans un délai de trois semaines à compter de la transmission de cet avis en tenant pleinement compte de celui-ci.

5.   Que le CECAPP ait été consulté ou non, la décision du contrôleur du groupe est dûment motivée et elle tient compte des avis exprimés par les autres autorités de contrôle concernées.

Le contrôleur du groupe transmet la décision au demandeur et aux autres autorités de contrôle concernées.

Les autorités de contrôle concernées se conforment à la décision.

6.   À défaut de décision conjointe dans les délais prescrits aux paragraphes 2 et 3 respectivement, le contrôleur du groupe se prononce lui-même sur la demande.

Lorsqu'il prend sa décision, le contrôleur du groupe tient dûment compte:

. a) de l'avis et des réserves exprimés par les autres autorités de contrôle concernées dans les délais impartis;

. b) lorsque le CECAPP a été consulté, de l'avis de ce comité.

La décision est dûment motivée et elle comporte une explication de toute divergence significative par rapport aux positions adoptées par le CECAPP.

Le contrôleur du groupe notifie la décision au demandeur et aux autres autorités de contrôle concernées.

Cette décision est considérée comme déterminante et est appliquée par les autorités de contrôle concernées.

7.   Lorsque l'une des autorités de contrôle concernées considère que le profil de risque d'une entreprise d'assurance ou de réassurance qu'elle est chargée de contrôler s'écarte significativement des hypothèses qui sous-tendent le modèle interne approuvé au niveau du groupe, elle peut imposer à cette entreprise, conformément à l'article 37 et aussi longtemps que l'entreprise ne répond pas de manière satisfaisante aux préoccupations de l'autorité de contrôle, une exigence de capital supplémentaire s'ajoutant à son capital de solvabilité requis tel qu'il résulte de l'application dudit modèle.

Dans des circonstances exceptionnelles, lorsque cette exigence de capital supplémentaire serait inappropriée, l'autorité de contrôle peut exiger de l'entreprise concernée qu'elle calcule son capital de solvabilité requis sur la base de la formule standard visée au titre I, chapitre VI, section 4, sous-sections 1 et 2. Conformément à l'article 37, paragraphe 1, points a) et c), l'autorité de contrôle peut imposer une exigence de capital supplémentaire s'ajoutant au capital de solvabilité requis de cette entreprise d'assurance ou de réassurance résultant de l'application de la formule standard.

L'autorité de contrôle explique toute décision visée aux premier et deuxième alinéas à l'entreprise d'assurance ou de réassurance ainsi qu'au contrôleur du groupe.