== Article 90

=== Approbation des fonds propres auxiliaires par les autorités de contrôle

1.   Les montants des éléments des fonds propres auxiliaires à prendre en considération pour déterminer les fonds propres sont soumis à l'approbation préalable des autorités de contrôle.

2.   Le montant attribué à chaque élément de fonds propres auxiliaires reflète la capacité d'absorption des pertes de l'élément concerné et est fondé sur des hypothèses prudentes et réalistes. Lorsqu'une valeur nominale fixe est attachée à un élément de fonds propres auxiliaires, le montant de cet élément est égal à sa valeur nominale, pourvu que celle-ci reflète convenablement sa capacité d'absorption des pertes.

3.   Les autorités de contrôle approuvent l'un ou l'autre des éléments suivants:

. a) un montant monétaire pour chaque élément de fonds propres auxiliaires;

. b) une méthode de calcul du montant de chaque élément de fonds propres auxiliaires, auquel cas l'approbation par les autorités de contrôle du montant ainsi calculé est donnée pour une période déterminée.

4.   Pour chaque élément de fonds propres auxiliaires, les autorités de contrôle fondent leur approbation sur l'évaluation des éléments suivants:

. a) le statut des contreparties concernées, eu égard à leur capacité et à leur disposition à payer;

. b) la possibilité de récupération des fonds, compte tenu de la forme juridique de l'élément considéré, ainsi que toute circonstance qui pourrait empêcher qu'il soit payé ou appelé avec succès;

. c) toute information sur l'issue des appels émis dans le passé par les entreprises d'assurance et de réassurance pour des fonds propres auxiliaires semblables, dans la mesure où cette information peut être raisonnablement utilisée pour estimer l'issue attendue de futurs appels.