= Article 89

Fonds propres auxiliaires

1.   Les fonds propres auxiliaires se composent d'éléments, autres que les fonds propres de base, qui peuvent être appelés pour absorber des pertes.

Les fonds propres auxiliaires peuvent inclure les éléments suivants, dans la mesure où il ne s'agit pas d'éléments de fonds propres de base:

. a) la fraction non versée du capital social ou le fonds initial qui n'a pas été appelé;

. b) les lettres de crédit et les garanties;

. c) tout autre engagement, juridiquement contraignant, reçu par les entreprises d'assurance et de réassurance.

Dans le cas d'une mutuelle ou d'une association de type mutuel à cotisations variables, les fonds propres auxiliaires peuvent également inclure toute créance future que cette mutuelle ou association de type mutuel peut détenir sur ses membres par voie de rappel de cotisations durant les douze mois à venir.

2.   Lorsqu'un élément des fonds propres auxiliaires a été payé ou appelé, il est assimilé à un actif et cesse de faire partie des fonds propres auxiliaires.