= Article 92

Mesures d'exécution

1.   La Commission arrête des mesures d'exécution précisant ce qui suit:

. a) les critères d'octroi de l'approbation par les autorités de contrôle prévue à l'article 90;

. b) le traitement à réserver aux participations, au sens de l'article 212, paragraphe 2, troisième alinéa, détenues dans des établissements de crédit et des établissements financiers, aux fins de la détermination des fonds propres.

Ces mesures, qui visent à modifier des éléments non essentiels de la présente directive en la complétant, sont arrêtées en conformité avec la procédure de réglementation avec contrôle visée à l'article 301, paragraphe 3.

2.   Les participations dans des établissements de crédit et des établissements financiers visées au paragraphe 1, point b), recouvrent ce qui suit:

. a) les participations que les entreprises d'assurance et de réassurance détiennent dans:i)des établissements de crédit et des établissements financiers au sens de l'article 4, points 1) et 5), de la directive 2006/48/CE;ii)des entreprises d'investissement au sens de l'article 4, paragraphe 1, point 1), de la directive 2004/39/CE;

. i) des établissements de crédit et des établissements financiers au sens de l'article 4, points 1) et 5), de la directive 2006/48/CE;

. ii) des entreprises d'investissement au sens de l'article 4, paragraphe 1, point 1), de la directive 2004/39/CE;

. b) les créances subordonnées et les instruments visés à l'article 63 et à l'article 64, paragraphe 3, de la directive 2006/48/CE que les entreprises d'assurance et de réassurance détiennent sur les entités définies au point a) du présent paragraphe dans lesquelles elles détiennent une participation.

Sous-section 2

Classement des fonds propres