== Article 69

=== Communication d'informations aux administrations centrales chargées de la législation financière

Les articles 64 et 67 ne font pas obstacle à ce que les États membres autorisent, en vertu de dispositions législatives, la communication de certaines informations à d'autres départements de leurs administrations centrales chargés de la législation relative au contrôle des établissements de crédit, des établissements financiers, des services d'investissement et des entreprises d'assurance ou de réassurance, ainsi qu'aux inspecteurs mandatés par ces départements.

Ces communications ne sont effectuées que lorsque cela se révèle nécessaire pour des raisons de contrôle prudentiel. Les États membres prévoient cependant que les informations reçues au titre de l'article 65 et de l'article 68, paragraphe 1, et les informations obtenues au moyen de vérifications sur place visées à l'article 32 ne peuvent être divulguées que sous réserve de l'accord explicite de l'autorité de contrôle dont elles proviennent ou de l'autorité de contrôle de l'État membre où la vérification sur place a été effectuée.