= Article 64

Secret professionnel

Les États membres prévoient que toutes les personnes exerçant ou ayant exercé une activité pour le compte des autorités de contrôle ainsi que les personnes chargées du contrôle légal des comptes ou les experts mandatés par ces autorités sont liés par l'obligation de secret professionnel.

Sans préjudice des cas relevant du droit pénal, aucune information confidentielle reçue par ces personnes à titre professionnel n'est divulguée à quelque personne ou autorité que ce soit, excepté sous une forme résumée ou agrégée, de telle sorte que les entreprises d'assurance ou de réassurance ne puissent être identifiées.

Toutefois, lorsqu'une entreprise d'assurance ou de réassurance a été déclarée en faillite ou que sa liquidation forcée a été ordonnée par un tribunal, les informations confidentielles qui ne concernent pas les tiers impliqués dans des tentatives de sauvetage de cette entreprise peuvent être divulguées dans le cadre de procédures civiles ou commerciales.