== Article 68

=== Échange d'informations avec d'autres autorités

1.   Les articles 64 et 67 ne font obstacle à aucune des activités suivantes:

. a) l'échange d'informations entre plusieurs autorités de contrôle du même État membre, pour l'accomplissement de leurs fonctions de contrôle;

. b) l'échange d'informations, pour l'accomplissement de leurs fonctions de contrôle, entre les autorités de contrôle et les autorités, organes ou personnes suivants situés dans le même État membre:i)les autorités investies de la mission de contrôle des établissements de crédit et des autres institutions financières ainsi que les autorités chargées du contrôle des marchés financiers;ii)les organes impliqués dans la liquidation et la faillite des entreprises d'assurance ou des entreprises de réassurance et autres procédures similaires;iii)les personnes chargées du contrôle légal des comptes des entreprises d'assurance, des entreprises de réassurance et des autres établissements financiers;

. i) les autorités investies de la mission de contrôle des établissements de crédit et des autres institutions financières ainsi que les autorités chargées du contrôle des marchés financiers;

. ii) les organes impliqués dans la liquidation et la faillite des entreprises d'assurance ou des entreprises de réassurance et autres procédures similaires;

. iii) les personnes chargées du contrôle légal des comptes des entreprises d'assurance, des entreprises de réassurance et des autres établissements financiers;

. c) la transmission, aux organes chargés de la gestion de procédures de liquidation forcée ou de fonds de garantie, des informations nécessaires à l'accomplissement de leur fonction.

Les échanges d'informations visés aux points b) et c) peuvent également avoir lieu entre différents États membres.

Les informations reçues par ces autorités, organes et personnes sont soumises à l'obligation de secret professionnel prévue à l'article 64.

2.   Les articles 64 à 67 ne font pas obstacle à ce que les États membres autorisent l'échange d'informations entre les autorités de contrôle et les autorités ou personnes suivantes:

. a) les autorités chargées de la surveillance des organes impliqués dans la liquidation et la faillite des entreprises d'assurance ou des entreprises de réassurance et autres procédures similaires;

. b) les autorités chargées de la surveillance des personnes chargées du contrôle légal des comptes des entreprises d'assurance, des entreprises de réassurance, des établissements de crédit, des entreprises d'investissement et des autres établissements financiers;

. c) les actuaires indépendants des entreprises d'assurance ou des entreprises de réassurance exerçant, en vertu de la loi, une fonction de contrôle sur celles-ci ainsi que les organes chargés du contrôle de ces actuaires.

Les États membres qui appliquent le premier alinéa exigent au moins que les conditions suivantes soient remplies:

. a) les informations doivent être destinées à l'accomplissement de la mission de surveillance ou de la fonction de contrôle en vertu de la loi visées au premier alinéa;

. b) les informations reçues doivent être soumises à l'obligation de secret professionnel prévue à l'article 64;

. c) lorsque les informations proviennent d'un autre État membre, elles ne peuvent être divulguées qu'avec l'accord explicite de l'autorité de contrôle dont elles proviennent et, le cas échéant, exclusivement aux fins pour lesquelles ladite autorité a donné son accord.

Les États membres communiquent à la Commission et aux autres États membres l'identité des autorités, personnes ou organes qui peuvent recevoir des informations en vertu des premier et deuxième alinéas.

3.   Les articles 64 à 67 ne font pas obstacle à ce que les États membres autorisent, dans le but de renforcer la stabilité du système financier et son intégrité, l'échange d'informations entre les autorités de contrôle et les autorités ou organes chargés de la détection des infractions au droit des sociétés et des enquêtes sur ces infractions.

Les États membres qui appliquent le premier alinéa exigent que les conditions suivantes au moins soient réunies:

. a) les informations doivent être destinées à la détection des infractions et aux enquêtes visées au premier alinéa;

. b) les informations reçues doivent être soumises à l'obligation de secret professionnel prévue à l'article 64;

. c) lorsque les informations proviennent d'un autre État membre, elles ne sont divulguées qu'avec l'accord explicite de l'autorité de contrôle dont elles proviennent et, le cas échéant, exclusivement aux fins pour lesquelles ladite autorité a donné son accord.

Si, dans un État membre, les autorités ou organes visés au premier alinéa accomplissent leur mission de détection ou d'enquête en faisant appel, au vu de leur compétence spécifique, à des personnes mandatées à cet effet et n'appartenant pas au secteur public, la possibilité d'échanges d'informations prévue au premier alinéa peut être étendue à ces personnes aux conditions prévues au deuxième alinéa.

Aux fins de la mise en œuvre du deuxième alinéa, point c), les autorités ou organes visés au premier alinéa communiquent à l'autorité de contrôle dont les informations proviennent l'identité et le mandat précis des personnes à qui elles seront transmises.

4.   Les États membres communiquent à la Commission et aux autres États membres l'identité des autorités, personnes ou organes qui peuvent recevoir des informations en vertu du paragraphe 3.