= Article 71

Convergence du contrôle

1.   Les États membres veillent à ce que les mandats des autorités de contrôle intègrent de manière appropriée la dimension de l'Union européenne.

2.   Les États membres veillent à ce que, dans l'exercice de leurs fonctions, les autorités de contrôle prennent en compte la convergence en matière d'outils de contrôle et de pratiques de contrôle dans l'application des dispositions législatives, réglementaires et administratives adoptées conformément à la présente directive. À cette fin, les États membres veillent à ce que les autorités de contrôle participent aux activités du CECAPP, conformément à la décision 2009/79/CE, et tiennent dûment compte de ses orientations et recommandations visées au paragraphe 3 du présent article.

3.   Le CECAPP fournit, si nécessaire, des orientations et recommandations, non contraignantes juridiquement, au sujet de la mise en œuvre des dispositions de la présente directive et de ses mesures d'exécution, afin de renforcer la convergence des pratiques de contrôle. Il fait en outre régulièrement rapport, au moins tous les deux ans, au Parlement européen, au Conseil et à la Commission sur les progrès réalisés dans la convergence du contrôle au sein de la Communauté.

Section 6

Rôle des personnes chargées du contrôle des comptes