== Article 2

=== Champ d'application

1.   La présente directive s'applique aux entreprises d'assurance directe vie et non-vie qui sont établies sur le territoire d'un État membre ou qui désirent s'y établir.

Elle s'applique également, à l'exception du titre IV, aux entreprises de réassurance, qui n'exercent que des activités de réassurance et qui sont établies dans un État membre ou qui désirent s'y établir.

2.   Pour ce qui concerne l'assurance non-vie, la présente directive s'applique aux activités des branches qui figurent à l'annexe I, partie A. Aux fins du paragraphe 1, premier alinéa, l'assurance non-vie inclut l'activité consistant à fournir une assistance aux personnes en difficulté au cours de déplacements, d'absences de leur domicile ou de leur résidence habituelle. Elle comporte, moyennant le paiement préalable d'une prime, l'engagement de mettre immédiatement une aide à la disposition du bénéficiaire d'un contrat d'assistance lorsque celui-ci se trouve en difficulté par suite d'un événement fortuit, dans les cas et dans les conditions prévus par le contrat.

L'aide peut comporter des prestations en espèces ou en nature. Les prestations en nature peuvent également être fournies par l'utilisation du personnel ou du matériel propres au prestataire.

L'activité d'assistance ne couvre pas les services d'entretien ou de maintenance, les services après-vente ou la simple indication ou mise à disposition, en tant qu'intermédiaire, d'une aide.

3.   Pour ce qui concerne l'assurance vie, la présente directive s'applique:

. a) aux activités d'assurance vie suivantes, lorsqu'elles découlent d'un contrat:i)l'assurance «vie», qui comprend l'assurance en cas de vie, l'assurance en cas de décès, l'assurance mixte, l'assurance sur la vie avec contre-assurance, l'assurance «nuptialité», l'assurance «natalité»;ii)l'assurance de rente;iii)les assurances complémentaires souscrites en complément d'une assurance vie, et notamment les assurances «atteintes corporelles y compris l'incapacité de travail professionnel», les assurances «décès à la suite d'accident» et les assurances «invalidité à la suite d'accident ou de maladie»;iv)les types d'assurance-maladie permanente, non résiliable, pratiquée actuellement en Irlande et au Royaume-Uni;

. i) l'assurance «vie», qui comprend l'assurance en cas de vie, l'assurance en cas de décès, l'assurance mixte, l'assurance sur la vie avec contre-assurance, l'assurance «nuptialité», l'assurance «natalité»;

. ii) l'assurance de rente;

. iii) les assurances complémentaires souscrites en complément d'une assurance vie, et notamment les assurances «atteintes corporelles y compris l'incapacité de travail professionnel», les assurances «décès à la suite d'accident» et les assurances «invalidité à la suite d'accident ou de maladie»;

. iv) les types d'assurance-maladie permanente, non résiliable, pratiquée actuellement en Irlande et au Royaume-Uni;

. b) aux opérations suivantes lorsqu'elles découlent d'un contrat, pour autant qu'elles soient soumises au contrôle des autorités chargées du contrôle des assurances privées:i)les opérations comportant la constitution d'associations réunissant des adhérents en vue de capitaliser en commun leurs cotisations et de répartir ensuite l'avoir ainsi constitué soit entre les survivants, soit entre les ayants droit des décédés (opérations tontinières);ii)les opérations de capitalisation basées sur une technique actuarielle comportant, en échange de versements uniques ou périodiques fixés à l'avance, des engagements déterminés quant à leur durée et à leur montant;iii)les opérations de gestion de fonds collectifs de retraite, comprenant la gestion des placements et notamment des actifs représentatifs des réserves des organismes qui fournissent des prestations en cas de décès, en cas de vie ou en cas de cessation ou de réduction d'activités;iv)les opérations visées au point iii) lorsqu'elles sont assorties d'une garantie d'assurance portant soit sur la conservation du capital, soit sur le service d'un intérêt minimal;v)les opérations effectuées par des entreprises d'assurance vie, telles que celles visées par le code français des assurances au livre IV, titre 4, chapitre 1;

. i) les opérations comportant la constitution d'associations réunissant des adhérents en vue de capitaliser en commun leurs cotisations et de répartir ensuite l'avoir ainsi constitué soit entre les survivants, soit entre les ayants droit des décédés (opérations tontinières);

. ii) les opérations de capitalisation basées sur une technique actuarielle comportant, en échange de versements uniques ou périodiques fixés à l'avance, des engagements déterminés quant à leur durée et à leur montant;

. iii) les opérations de gestion de fonds collectifs de retraite, comprenant la gestion des placements et notamment des actifs représentatifs des réserves des organismes qui fournissent des prestations en cas de décès, en cas de vie ou en cas de cessation ou de réduction d'activités;

. iv) les opérations visées au point iii) lorsqu'elles sont assorties d'une garantie d'assurance portant soit sur la conservation du capital, soit sur le service d'un intérêt minimal;

. v) les opérations effectuées par des entreprises d'assurance vie, telles que celles visées par le code français des assurances au livre IV, titre 4, chapitre 1;

. c) aux opérations dépendant de la durée de la vie humaine, définies ou prévues par la législation des assurances sociales, pour autant qu'elles soient pratiquées ou gérées par des entreprises d'assurance vie et à leur propre risque, en conformité avec la législation d'un État membre.

Section 2

Exclusions du champ d'application

Sous-section 1

Dispositions générales